### ISSUE TITLE
Supplementaries Stacked Books Crash

### ISSUE THREAD

**Issue by danflech** [Snownee/Jade#100]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

4.4.1

### Modloader version

Forge 39.1.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/pmzqyDhV

### Issue description

Whenever I use Jade to look at a stack of 4 enchanted books from Supplementaries, game instantly crashes. Not sure if this is a one-sided or two-sided issue, but I saw the bug only posted to the Supplementaries team. Figured it was fitting to also post here.

**Comment by Snownee** [comment]
https://github.com/MehVahdJukaar/Supplementaries/issues/215

Seems fixed
