### ISSUE TITLE
Jade Mod Name Tooltips sometimes wrong

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#102]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.1

### Modloader version

Forge 36.2.31

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Hovering the mouse over Industrial Foregoing items in Vanilla's Creative menu shows "Minecraft" as the mod name

I originally thought this was a JEI issue, but with JEI disabled and just Jade and IF installed, go into a creative menu and hover over the IF items

https://imgur.com/a/WmjW4v2

Could we also have a config to disable Jade overriding the tooltips, if possible?

**Comment by Snownee** [comment]
redirect to https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1253
