### ISSUE TITLE
[1.18.2] Linefeed not working in tooltip

### ISSUE THREAD

**Issue by JaisDK** [Snownee/Jade#103]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.0.1

### Modloader version

40.0.34

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://user-images.githubusercontent.com/15868585/161341258-632641d0-1e6a-4a53-864f-6110e41f9bdd.png)

**Comment by JaisDK** [comment]
text is 

`"Repopulation cooldown %s\nUse additional treats to speed up",`

**Comment by Snownee** [comment]
I don't know whether it should be fixed, because it is vanilla's behavior for item
