### ISSUE TITLE
Some mod entity names are not displaying correctly

### ISSUE THREAD

**Issue by carlstrax** [Snownee/Jade#105]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

Jade-1.18.1-4.4.1.jar

### Modloader version

Forge: 39.1.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I've been getting this issue with the Wild Cats mob from the Untamed Wilds mod where its showing "entity.untamedwilds.big_cat" instead of "Big Cat". I havent seen this issue with other mobs as of yet. I'm not sure if this is a bug or if its something from this mob's files that's causing this

![2022-04-30_22 57 35](https://user-images.githubusercontent.com/104706664/166131768-347aa6ec-b517-4cb0-b448-4bec79e4484a.png)

**Comment by Snownee** [comment]
report it to Untamed Wilds
