### ISSUE TITLE
Jade causing crash in custom modpack [1.18.2]

### ISSUE THREAD

**Issue by omegathan** [Snownee/Jade#106]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.1.0

### Modloader version

Forge 40.1.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/create-omega (still waiting on approval from CurseForge...)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I've isolated my game's crashing to Jade. Whenever I remove Jade or disable it, my game runs just fine.

**Comment by Snownee** [comment]
The latest.log file?
