### ISSUE TITLE
Armor points

### ISSUE THREAD

**Issue by akasheeee** [Snownee/Jade#108]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.1

### Modloader version

forge-36.2.34

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

hello, i'm having problems with jade mod, i used wthit and i modified some settings in armor points, but now armor points are big and i can't see hearts, wanted to know how i can reset settings
I'm using google translate, so sorry for any mistakes :)

**Comment by Snownee** [comment]
You can delete `config/waila/waila.json`
