### ISSUE TITLE
Failed to handle packet errors

### ISSUE THREAD

**Issue by Anaerin** [Snownee/Jade#109]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.1.0

### Modloader version

Forge 40.1.20

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/URJwcvmL

### Issue description

Getting this error (which is not causing a crash, but still annoying at least).

**Comment by Snownee** [comment]
it is not a problem with Jade. you should report it to the dev of the block that you were looking at
