### ISSUE TITLE
[Suggestion] Migrate to new config namespace?

### ISSUE THREAD

**Issue by ChloeDawn** [Snownee/Jade#11]
Now that Jade is more than just addons to HWYLA and forks the mod itself, I feel it'd be a good idea to deprecate the legacy `waila` namespace for configs, and start reading/writing to a `jade` directory. Old configs could still be read, but I feel it should not write there anymore, and possibly log a warning to let the end user know that the old namespace is no longer being used if configs are found there

**Comment by Snownee** [comment]
I don't know if this is a good idea. I want to keep the process seamless if user wants to migrate from hwyla to jade.
