### ISSUE TITLE
Imcompatibility with Waystones

### ISSUE THREAD

**Issue by yanang007** [Snownee/Jade#112]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

Jade-1.18.2-5.1.0

### Modloader version

Forge: 40.1.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

java.lang.AbstractMethodError: Method net/blay09/mods/waystones/compat/WailaProvider$WaystoneDataProvider.appendTooltip(Lmcp/mobius/waila/api/ITooltip;Lmcp/mobius/waila/api/BlockAccessor;Lmcp/mobius/waila/api/config/IPluginConfig;)V is abstract

### Issue description

As the related error info is pretty short , I will paste it directly into it. The full log is ready to upload if needed.

Waystones version: forge-1.18.2-10.0.0

This is how the WAILA plugin is implemented in Waystones mod.
https://github.com/ModdingForBlockheads/Waystones/blob/1f425a2d2e882b4a81615d4115410c7559a76f34/forge/src/main/java/net/blay09/mods/waystones/compat/WailaProvider.java#L18-L47

It looks like the API refactoring is probably the cause of this incompatibility. Mods developed for both forge and fabric may still follow the old API conventions as the fabric fork is still using the old ones.

**Comment by Snownee** [comment]
There is nothing I can really do to solve this problem now. I will rename package in 1.19
