### ISSUE TITLE
按键冲突问题

### ISSUE THREAD

**Issue by cqjdzy** [Snownee/Jade#114]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.2

### Modloader version

0.53.0

### Modpack info

无

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

jade的shift键查看容器明细和原版shift下蹲冲突，且会顶掉下蹲键。之前1.16.5玩的时候即使二者共用一个shift键也没影响使用，望指点或修正，谢谢。

**Comment by Snownee** [comment]
无法复现。不存在”顶掉按键“的说法
