### ISSUE TITLE
"Show details" keybind overrides vanilla's "Sneak" keybind

### ISSUE THREAD

**Issue by paulhlschr** [Snownee/Jade#116]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.2

### Modloader version

Quilt Loader 0.16.1 + Quilted Fabric API 1.0.0-beta.14+0.51.1-1.18.2

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/paulhlschr/1064824b0167d880d0cc983feb438e79

### Issue description

It is not possible to sneak without changing or unbinding Jade's"Show details" keybind.

**Comment by Snownee** [comment]
Are you sure you can reproduce this issue with Jade only? Can you reproduce this with Fabric?

**Comment by paulhlschr** [comment]
It is reproducible with the following setup:

## Jade-only setup on Quilt:
### Reproducible?
✅ Kinda. Read notes.
### Minecraft 
1.18.2
### Mod Version 
5.99.2
### Quilt Loader Version
0.16.1
### Installed mods
- Quilt Standard Libraries (Quilted Fabric API) 1.0.0-beta.14+0.51.1-1.18.2
- Architectury 4.4.68
### Log Files
[latest.log](https://github.com/Snownee/Jade/files/8800050/latest.log)
### Notes
While it is possible to sneak, the standard keybind "Left Shift" will not show additional information when used on container blocks. (Tested on filled chests and shulker boxes.)

---

## Jade-only setup on Fabric:
### Reproducible?
✅ Kinda. Read notes.
### Minecraft 
1.18.2
### Mod Version 
5.99.2
### Fabric Loader Version
0.14.6
### Installed mods
- Fabric API 0.53.4+1.18.2
- Architectury 4.4.68
### Log Files
[latest.log](https://github.com/Snownee/Jade/files/8800032/latest.log)
### Notes
While it is possible to sneak, the standard keybind "Left Shift" will not show additional information when used on container blocks. (Tested on filled chests and shulker boxes.)

**Comment by Snownee** [comment]
Hmmmm, what if you change the keybind to another key? Does it work?

**Comment by paulhlschr** [comment]
I changed it to `.`, so there were no other conflicts. It still does not show any details on containers. Sneak works properly now.

**Comment by Snownee** [comment]
I still can't reproduce the "sneak is not possible" part

**Comment by argon000s** [comment]
It does not show container contents for me, only beehives show info.

**Comment by Snownee** [comment]
yes, because I haven't implemented this feature yet

**Comment by tastesliketriangle** [comment]
I can reproduce this with normal fabric, but not with a clean install. I'll see if I can narrow it down on my end.

**Comment by tastesliketriangle** [comment]
Adding `Xaeros_Minimap_22.8.2_Fabric_1.18.2.jar` prevents me from sneaking. Binding the 'show details' hotkey from Jade to something other than left shift fixes it... somehow.

**Comment by argon000s** [comment]
I recommend getting the Amecs mod - it helps with keybinds

**Comment by Snownee** [comment]
Thanks for the testing. Unfortunately Xaero's Minimap is not source-open, so it will probably cost some time
