### ISSUE TITLE
game speaker

### ISSUE THREAD

**Issue by V4kodin** [Snownee/Jade#118]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.1

### Modloader version

36.2.35

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/V4kodin/c1bdb2f8f23b76f188efacfe6b5927e0

### Issue description

I can t turn of game speaker.
it starts voicing the blocks i'm looking at.
ctrl + b and menu turning off not working help

**Comment by V4kodin** [comment]
speaker means narrator, sorry. 
I m playing not EN version

**Comment by V4kodin** [comment]
Speaker means narrator.
Sorry i m using not EN version

**Comment by Snownee** [comment]
Hello, do you know you can press [numpad 0] to open the Jade configs? Hope it helps you!

**Comment by V4kodin** [comment]
Yeah i know but only now find necessary setting. Btw tts not the best name ;).
Excuse for troubling
