### ISSUE TITLE
Entities use inconsistent hearts and heart background

### ISSUE THREAD

**Issue by JuceInUse** [Snownee/Jade#122]
### Mod loader

Fabric

### Minecraft version

1.19

### Mod version

7.1.3

### Modloader version

Fabric Loader v0.14.7 + API v0.55.3

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

The issue is pretty simple. Entities use inconsistent heart background and hearts when viewing them with Jade

![image](https://user-images.githubusercontent.com/85078618/173198985-eb6c9075-d521-4c90-8522-60067d263fd5.png)

![image](https://user-images.githubusercontent.com/85078618/173198997-dfccf031-1ffb-4094-9f01-1d9b53c1e15d.png)

**Comment by Snownee** [comment]
what is your resource pack?

**Comment by JuceInUse** [comment]
Well the hearts are from [this pack here](https://www.planetminecraft.com/texture-pack/hexo-s-hearts/), but the saddle I'm using can only be achieved in the new version by deleting icons.png and renaming "icons (old saddle).png" to "icons.png"
