### ISSUE TITLE
Identified By Windows Defender As A Severe Threat, Trojan

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#123]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.1

### Modloader version

40.1.0

### Issue description

The JAR was acquired from the official CurseForge mod page
![image](https://user-images.githubusercontent.com/30256166/173444123-9b918113-0d2d-4901-9cac-9611df87c3ca.png)

**Comment by ghost** [comment]
### Update
I ran it through [virustotal ](https://www.virustotal.com/gui/file/d1d5c4148c3c94882355a2b033cb71587fab59f0ec760ac579f5e8df37c734dc) and it detected nothing, it could be a false positive with Windows Defender

**Comment by Snownee** [comment]
yeah I agree with you, it is not likely to be a virus
