### ISSUE TITLE
Weird feature

### ISSUE THREAD

**Issue by castilio20** [Snownee/Jade#124]
### Mod loader

Forge

### Minecraft version

1,18,22

### Mod version

5.2.1

### Modloader version

forge-40.1.31

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2022-06-13_23 27 01](https://user-images.githubusercontent.com/76228548/173452665-9698b1b4-108c-4284-9dc2-231f2a966c0e.png)
right now the way that jade tells you how many items is in a drawer is weird and a little anoyng
would be nice if would tell you how many you have from max
(for chest is ok)

**Comment by Snownee** [comment]
This is not a feature. The reason TOP is prettier is because the Functional Storage specifically provides TOP integration.
