### ISSUE TITLE
Show registry name when advanced tooltips is enabled

### ISSUE THREAD

**Issue by SandWoodJones** [Snownee/Jade#129]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.5

### Modloader version

0.14.7 + API 0.56.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Add an option for enabling showing restry names whenever advanced tooltips is also enabled. This would be helpful for debugging and modpack development purposes.

**Comment by Snownee** [comment]
you can just enable it in plugin config

**Comment by SandWoodJones** [comment]
Yeah but as I test modpacks by playing them in survival for long periods of time I don't need it on all the time. But when I do I'd prefer if i could turn it on or off with a button press.
