### ISSUE TITLE
Issue with ae2 interface

### ISSUE THREAD

**Issue by Leclowndu93150** [Snownee/Jade#130]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

latest

### Modloader version

.41

### Modpack info

custom modpack

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

**Comment by Leclowndu93150** [comment]
![2022-06-22_12 46 53](https://user-images.githubusercontent.com/73310949/175011201-5b285f7e-7194-4688-a309-f961999ac53c.png)

**Comment by Leclowndu93150** [comment]
![2022-07-02_12 18 59](https://user-images.githubusercontent.com/73310949/176996432-ea535a88-0872-435d-90f9-eb5c2722627a.png)
good luck

**Comment by CapivaraTupiniquim** [comment]
The same here!
