### ISSUE TITLE
[1.18.2] Feature request- ignore Minecraft Transit railway invisible entity

### ISSUE THREAD

**Issue by ProsperCraft** [Snownee/Jade#131]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

N/A

### Modloader version

N/A

### Modpack info

https://www.curseforge.com/minecraft/modpacks/towncraft

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

https://github.com/jonafanho/Minecraft-Transit-Railway/issues/400

Minecraft Transit Railway has some kind of invisible entity that follows the player to summon trains to it? Anyhow we are seeing this thing everywhere and disturbs play.

Would you be willing to code Jade so it doesn't display it?

**Comment by Snownee** [comment]
Yes, they can hide target using Jade. Here is useful information their devs may want: https://jademc.readthedocs.io/en/latest/plugins17/hiding-target/
