### ISSUE TITLE
Language provider issue

### ISSUE THREAD

**Issue by wbatzle** [Snownee/Jade#133]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

forge-1.18.2-40.1.54

### Modloader version

forge-1.18.2-40.1.54

### Modpack info

none

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I get an error "Mod File Jade-1.19-forge-7.3.0.jar needs language provider javafm1:41 or above to load. we have found 40"

The only mods being loaded are the latest release of JEI and Forge. I tried loading just Jade and that still bombs out.

**Comment by Snownee** [comment]
i literally dont know what you mean. like how do you get minecraft 1.19.2? did you hack mojang?

**Comment by wbatzle** [comment]
Apologies. it's 1.19.1 pre2. Don't mind me I have dain bramage.

**Comment by wbatzle** [comment]
I am closing this issue. I blew out my .minecraft folder entirely. Something must have broken updating Forge for JEI. A rebuild is working. I suggest for anyone that has this issue to blow out their folder(after backing it up somewhere) and install a new instance. Make sure if you are trying to load any mods that you NEVER put all the mods in all at once. Launch the game then add a mod and repeat the process till you are done. This will help you to narrow down incompatibilities in mods.

**Comment by Snownee** [comment]
there is no Forge for 1.19.1-pre2
