### ISSUE TITLE
HTM兼容性

### ISSUE THREAD

**Issue by Dr-WeiAL** [Snownee/Jade#135]
### Mod loader

Fabric

### Minecraft version

1.19

### Mod version

7.4.0

### Modloader version

fabric loader 0.14.8  fabric api 0.57.0

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

https://www.curseforge.com/minecraft/mc-mods/htm
看向锁定的容器会一直提示已锁定，似乎是jade一直在读取内部物品

**Comment by Snownee** [comment]
与我无关。请自行确认问题来源。

**Comment by Dr-WeiAL** [comment]
> 与我无关。请自行确认问题来源。

确定是Jade读取的，但读取不了就一直读取，相关录屏我发送到你的QQ上了
