### ISSUE TITLE
与create冲突

### ISSUE THREAD

**Issue by dajiuji** [Snownee/Jade#136]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.2

### Modloader version

40.1.54

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Jade-forge-5.2.2版本与create最新版本0.5里的火车冲突，具体表现为用准星对上构建完成的火车实体时会崩溃。
对了，我也安装了JadeAddons-2.0.0。

**Comment by Snownee** [comment]
重复提交
