### ISSUE TITLE
时装工坊的时装方块不能正确显示”方块名称“

### ISSUE THREAD

**Issue by luoxiawuchen** [Snownee/Jade#138]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.1

### Modloader version

forge-36.2.34

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

鼠标指向时装方块时，统一显示为”时装方块“，而非对应的方块名称
但在以前hwyla可以正常显示
![20J~_54VX N6FB%DYB@_0EN](https://user-images.githubusercontent.com/64759847/178898326-f5db0a37-2510-4168-b413-69b149c54d72.png)
![DB2`%}21_$668AK{WJQ5@9M](https://user-images.githubusercontent.com/64759847/178898346-4de97523-8672-4238-aadf-ccf4cb8819bf.png)

与时装工坊作者交流得知：
hwyla显示的方块信息包含中键（或者说ctrl+中键？）获取的，但是jade没有

hwyla的效果
![image](https://user-images.githubusercontent.com/64759847/178901024-909dda70-b4c5-4068-afde-c0fb0298a5ed.png)
![image](https://user-images.githubusercontent.com/64759847/178901059-5ac34263-6bc1-426e-82a9-f4d38227686e.png)

**Comment by Snownee** [comment]
正相反，Hwyla显示的名称是错误的：

https://github.com/TehNut-Mods/HWYLA/issues/257

**Comment by Snownee** [comment]
我可以添加一个tag来让方块通过中键的方式获取名称，不过想要自定义的话如果服务器没有相应tag就没法生效了

**Comment by luoxiawuchen** [comment]
> 我可以添加一个tag来让方块通过中键的方式获取名称，不过想要自定义的话如果服务器没有相应tag就没法生效了

ok 谢谢大佬 如果可以 这或许是合适的解决方案

**Comment by luoxiawuchen** [comment]
> 我可以添加一个tag来让方块通过中键的方式获取名称，不过想要自定义的话如果服务器没有相应tag就没法生效了

请问大佬新增的tag名称是什么那？数据类型是？
我在BlockEntityTag中添加了 jade:"pick" (字符型),但没有效果
![image](https://user-images.githubusercontent.com/64759847/179141178-1a90ca5f-0ea6-4ed5-8167-24e9b04c60b9.png)
![image](https://user-images.githubusercontent.com/64759847/179141346-64b2f804-cdf7-48c2-bbe9-ab777a0880bc.png)

**Comment by Snownee** [comment]
https://minecraft.fandom.com/zh/wiki/%E6%A0%87%E7%AD%BE
