### ISSUE TITLE
Add support for Composter level

### ISSUE THREAD

**Issue by ysc3839** [Snownee/Jade#142]
### Mod loader

Fabric

### Minecraft version

1.18.2 & 1.19

### Mod version

latest version

### Modloader version

Fabric latest version

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Please add support for Composter level. Thank you very much!

**Comment by Snownee** [comment]
I don't think this is very necessary

**Comment by ysc3839** [comment]
But I think it's necessary. I can create a pr if you don't want to write code.

**Comment by Snownee** [comment]
well. ok

**Comment by MeeniMc** [comment]
Has this ever been done in the end? Composter fill level is useful when using composters as a redstone component.
