### ISSUE TITLE
with ModernUI and Jade open the Jade config window and slide to the bottom will crash

### ISSUE THREAD

**Issue by rylwl** [Snownee/Jade#143]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.3

### Modloader version

40.1.68

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/rylwl/7a151a939574eef1fb26e94ca1466ce6

### Issue description

I try to only install ModernUI and Jade and find that it will make crash.
(If i open the Jade config(not the plugin config) and not slide to the bottom ,it will not be crash,but when I slide to the bottom to the format config,it will be crash

**Comment by Snownee** [comment]
please report this to Modern UI
