### ISSUE TITLE
Missing API jars

### ISSUE THREAD

**Issue by pupnewfster** [Snownee/Jade#147]
### Mod loader

Forge

### Minecraft version

1.19

### Mod version

7.6.0+

### Modloader version

Irrelevant

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It appears as of Jade 1.19 7.6.0 the API jars have stopped being uploaded to curseforge as secondary files along with the main file.

**Comment by Snownee** [comment]
Hello. I couldn't get CurseForgeGradle to work, so I've been uploading files manually. And because I am lazy and there is no difference from previous versions, I didn't upload api jars.

Anyway I have uploaded for the latest version and will always upload in the future : )
