### ISSUE TITLE
[Sugestion] Configurable nbt info

### ISSUE THREAD

**Issue by LaDaniWapa** [Snownee/Jade#149]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.6

### Modloader version

Fabric Loader: 0.14.8 + Fabric API: 0.57.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello ^^/

I'd like to display the internalCurrentPower, but instead of doing a whole addon for each mod, Im requesting a way to display a custom nbt tag from a given block

Examble:
{
     //some nbt info from minecraft command....
     internalCurrentPower: 3d,
     id: "ae2:energy_cell"
}

**Comment by Snownee** [comment]
Sorry I don't think it is a good idea
