### ISSUE TITLE
Config menus cause game crash

### ISSUE THREAD

**Issue by LackingAGoodName** [Snownee/Jade#151]
### Mod loader

Fabric

### Minecraft version

1.19.1

### Mod version

7.7.1

### Modloader version

Loader: 0.14.8 / API: 0.58.5+1.19.1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Game crashes when attempting to open Jade config and Plugin config menus. Not using any mods except for the required Fabric mods and ModMenu. Crash report: 

[crash-2022-08-01_17.36.56-client.txt](https://github.com/Snownee/Jade/files/9235294/crash-2022-08-01_17.36.56-client.txt)

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/jade/files/3903418
