### ISSUE TITLE
Waystones <ERROR>

### ISSUE THREAD

**Issue by KyrDerz** [Snownee/Jade#156]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.3

### Modloader version

40.1.74

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://user-images.githubusercontent.com/110685473/188272438-1dedfc5e-cba5-4ed4-8776-21074341f4f9.png)
Is there a way to make the ERROR gone?

**Comment by Snownee** [comment]
disable it in plugin configs

**Comment by KyrDerz** [comment]
I've turned everything in jade_plugins.json to false. Still nothing
![image](https://user-images.githubusercontent.com/110685473/188273850-13440066-e9f6-41a1-a565-9a91f78ffe77.png)

**Comment by Snownee** [comment]
https://github.com/ModdingForBlockheads/Waystones/issues/564

I can't help. Maybe you can use WTHIT
