### ISSUE TITLE
Wont let me configure it

### ISSUE THREAD

**Issue by elementfireice** [Snownee/Jade#157]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

7.4.0

### Modloader version

Fabric-loader-0.14.9-1.19.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void snownee.jade.gui.config.WailaOptionsList.method_25311(net.minecraft.class_4587, int, int, int, int, float)' Thats the crashlog and I have no idea what the problem is or if I am just being dumb

**Comment by Snownee** [comment]
please update
