### ISSUE TITLE
1.19.2 support

### ISSUE THREAD

**Issue by ToasterUwU** [Snownee/Jade#159]
### Mod loader

Forge

### Minecraft version

None

### Mod version

None

### Modloader version

None

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hey, i just wanted to ask if 1.19.2 forge support is coming? Since the changelog from 1.19.1 to 1.19.2 suggests that only the chat system was effected and that also was two very little things, it should be most likely just a matter of testing it and releasing it with the new minecraft version offically supported. 

Im asking because im making a server for a few friends and myself and would love to use this mod, but cant because its on of the few mods that are not officaly supported for 1.19.2, but would probably just work fine.

Hope its as easy as i think it would be. And thanks for maintaning this, its so good that i feel weird not having it when i play minecraft, because i feel like something really important is missing.

**Comment by Snownee** [comment]
it is supported
