### ISSUE TITLE
Request: setting to disable showing EMC value

### ISSUE THREAD

**Issue by Sunekaer** [Snownee/Jade#162]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.4

### Modloader version

Forge: 40.1.80

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Option to disable showing the EMC value of the block you're looking at
![billede](https://user-images.githubusercontent.com/18720460/194853426-6f39dd28-6a13-4f37-8533-120eb5df9993.png)

**Comment by Snownee** [comment]
As their codes indicates, I think you can disable it in their server config.

https://github.com/sinkillerj/ProjectE/blob/mc1.18.x/src/main/java/moze_intel/projecte/integration/hwyla/HwylaDataProvider.java

**Comment by Sunekaer** [comment]
Thanks Snownee
