### ISSUE TITLE
polymer(core) error

### ISSUE THREAD

**Issue by Dooepo** [Snownee/Jade#163]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.2.1

### Modloader version

fabric0.14.9

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

方块显示下面有一行红字，error: polymer(core)错误什么的，让我report,应该是Mod兼容问题，只有在显示这个Mod的方块时才有这行红字，https://www.curseforge.com/minecraft/mc-mods/simplevillagers

**Comment by Snownee** [comment]
请提交给polymer
