### ISSUE TITLE
Mob Breeding Cooldown and Growing Timer not showing

### ISSUE THREAD

**Issue by tori1277** [Snownee/Jade#167]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.2.3

### Modloader version

Fabric: Loader 0.14.9 + API 0.62.0

### Modpack info

Fabulously Optimized https://www.curseforge.com/minecraft/modpacks/fabulously-optimized

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

file:///C:/Users/My%20Alt/AppData/Roaming/gdlauncher_next/instances/Fabulously%20Optimized/logs/latest.log

### Issue description

Despite having both Mob Breeding and Mob Growth timers enabled, neither will show in a server, but still will in singleplayer. Horse stats and health still show, however.

**Comment by Snownee** [comment]
I think that is because the server does not have Jade installed
