### ISSUE TITLE
How to reset settings

### ISSUE THREAD

**Issue by BobTopman** [Snownee/Jade#168]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.2.1

### Modloader version

Fabric Loader 0.14.10+ fabric-api-0.63.0+1.19.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hi there was just wondering if there was a way i could reset the settings of the mod back to default as i have changed the position and now cant get it right again to where it wont go of screen and things such as that.

(P.s - Nice mod by the way really enjoying so far)

**Comment by Snownee** [comment]
you can open the "config" folder and delete the "jade" folder in it

**Comment by BobTopman** [comment]
Thank you all back to normal now :)
