### ISSUE TITLE
JAde Error Loading Twilight Forest.Compat plugin

### ISSUE THREAD

**Issue by Zelioth** [Snownee/Jade#169]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.3.2

### Modloader version

43.1.74

### Modpack info

Friends United 2.2.7

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Zelioth/90e5efd6aae30786e72b2a43407cafd1

**Comment by Snownee** [comment]
please report to Twilight Forest devs
