### ISSUE TITLE
1.16.5 Fabric support?

### ISSUE THREAD

**Issue by marlester-dev** [Snownee/Jade#170]
### Mod loader

Fabric

### Minecraft version

1.16.5

### Mod version

latest 1.16.5

### Modloader version

latest fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello, sorry but I do not where to write ideas, there is nothing in https://github.com/Snownee/Jade/issues/new/choose, anyway can you add fabric support on 1.16.5 please? It's important

**Comment by Snownee** [comment]
I have no plan for this. You can consider using WTHIT or Hwyla

**Comment by marlester-dev** [comment]
> I have no plan for this. You can consider using WTHIT or Hwyla
![well-well-well](https://user-images.githubusercontent.com/77095872/200100295-93e7456a-280d-46c6-9f50-9373e6ca8115.gif)

![well-well-well](https://user-images.githubusercontent.com/77095872/200100296-567fe7e8-4a20-467e-9639-2ea023003fbb.gif)
