### ISSUE TITLE
missing color text

### ISSUE THREAD

**Issue by ElfKing94** [Snownee/Jade#171]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

Jade-1.19.1

### Modloader version

fabric-8.2.3.jar

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

hi so i have a banner with colored text and for some reason we cant color the 3 red. heres the code: /give @p lime_banner{display:{Name:'[

{"text":"3 ","italic":false,"color":"dark_red"}
,

{"text":"Kings","color":"green"}
,

{"text":" Banner","color":"#0033ff"}
]',Lore:['[

{"text":"3 Kings United","italic":true,"color":"yellow"}
]']},BlockEntityTag:{Base:5,Patterns:[

{Pattern:ls,Color:14}
,

{Pattern:rs,Color:11}
,

{Pattern:cbo,Color:15}
,

{Pattern:gru,Color:7}
,

{Pattern:ss,Color:15}
,

{Pattern:bts,Color:4}
,

{Pattern:tts,Color:4}
,

{Pattern:flo,Color:4}
]}} 1
![2022-11-04_09 09 03](https://user-images.githubusercontent.com/85055397/200016383-42741502-4ef9-4579-9f61-793dea9ffc4a.png)

**Comment by ElfKing94** [comment]
so after some messing around with fonts, it would seem just the first color has issue showing, not the dark red itself

**Comment by ElfKing94** [comment]
![2022-11-19_00 21 00](https://user-images.githubusercontent.com/85055397/202840403-5017b00b-5c4b-46e0-8363-6719a036cbb4.png)

**Comment by ElfKing94** [comment]
with the newest update, all colored text is broken, what happened?

**Comment by ElfKing94** [comment]
![2022-11-21_09 56 06](https://user-images.githubusercontent.com/85055397/203114304-52356bab-b28b-4353-926b-e6c05ff5be2e.png)

**Comment by Snownee** [comment]
This is intended behavior

**Comment by ElfKing94** [comment]
If you could, perhaps make this a togglable option in a future update, we would be grateful.

**Comment by Snownee** [comment]
ehh i don't like that. it will make text indistinguishable

**Comment by ElfKing94** [comment]
k sorry i tried to help 🤷‍♂️😅
