### ISSUE TITLE
Visual Display Error in Infographic Popup

### ISSUE THREAD

**Issue by Mohrdain** [Snownee/Jade#172]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

1.16.4-2.8.3

### Modloader version

Forge 36.2.39

### Modpack info

https://www.curseforge.com/minecraft/modpacks/strictly-medieval

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Not sure if this is a bug, but I added Quark Odditities to the modpack and this <Error> in the pop-up display started to happen.  When I loaded quark it took two restarts to set the config correctly as I had to turn on Oddities and turn off the Totem of Undying so as not to conflict with Corpse mod.  Once the configs were set correctly the mods worked just fine but the corpse left by the Corpse Mod is showing this weird <Error> display at the bottom.  Please let me know if you need more information and I hope this is helpful.

Thanks!
![2022-11-10_08 22 45](https://user-images.githubusercontent.com/86965936/201105024-0acee2d6-5d25-40c0-91ec-2a0c2c9e390e.png)

**Comment by Snownee** [comment]
Sorry, now I only maintain Jade for 1.18.2 and 1.19.1+
