### ISSUE TITLE
[Suggestion] Add a list of blocks/entities that Jade will not display

### ISSUE THREAD

**Issue by MistakingManx** [Snownee/Jade#177]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.2.3

### Modloader version

Fabric Launcher 0.14.10, Fabric API 0.64.0

### Modpack info

Better MC [Fabric] (I can't find the link for 1.19.2)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Could you add a GUI config option that lets the client stop Jade from displaying information on specific entities or blocks?

I noticed there's an API with a potential way to do this, but I have no idea how to code mods for Java Edition, the reason I'm making this suggestion is because I want to hide Immersive Portal's entity, it makes transitions too obvious.

**Comment by Gamerbolts** [comment]
I would like to second this please. Minecraft Transit Railway (MTR) shows when you are looking down but not close enough to any block. Would love to be able to blacklist MTR from showing.

**Comment by AngellusMortis** [comment]
Is there a way to block a whole mod namespace for this?

**Comment by Snownee** [comment]
> Is there a way to block a whole mod namespace for this?

currently, no

**Comment by Gamerbolts** [comment]
Has there been any work on this? I am not on a Forge Modpack and still the same issue :(

**Comment by aramrw** [comment]
The ability to turn off an entire namespace is needed very badly.

**Comment by Snownee** [comment]
> The ability to turn off an entire namespace is needed very badly.

it supports regex
