### ISSUE TITLE
Blacklist for specific blocks/items in the config so they don't get shown 

### ISSUE THREAD

**Issue by notIkibo** [Snownee/Jade#180]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

1

### Modloader version

Fabric Loader: 0.14.10 + API 0.66.0

### Modpack info

it's my modpack

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It's a general question: I'm setting up a mc server for my friends. Though I setted up a little area where they have to go through as an introduction. Funny stuff with flowing signs etc. 
(Just a little world building here)

The edges are filled with barriers, but it's a pure white room and I don't want them to see the "Barrier" block. It really breaks the immersion.

Is there any way to blacklist creative blocks so they don't get shown?

Other than that: Such a musthave mod. Kudos on that!

**Comment by Madis0** [comment]
How about still making it an option though, as Jade is known for its options.
