### ISSUE TITLE
[Suggestion] Have a server friendly version

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Snownee/Jade#181]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.6.0

### Modloader version

Quilt Loader 0.17.6 + Quilted Fabric API 4.0.0-beta.20+0.66.0-1.19.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Certain servers don't allow mods that give the player and advantage in pvp. This mod falls under that category. I've seen a map mod in the past have a safe version where certain features weren't included. So I was wondering if it'd be possible to do that for this mod? However if you didn't want to do that I'd understand

**Comment by Snownee** [comment]
I have no interests
