### ISSUE TITLE
Crash when looking at a mob (8.6.1 - MC 1.19.2)

### ISSUE THREAD

**Issue by Cynicizm** [Snownee/Jade#182]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.6.1

### Modloader version

Fabric Loader 0.14.10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

https://pastebin.com/wUzEq3P9

**Comment by Snownee** [comment]
please provide latest.log, not crash report

**Comment by Snownee** [comment]
nevermind, i have reproduced it
