### ISSUE TITLE
Crash upon loading world in 8.6.1 Fabric

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#183]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.6.1

### Modloader version

Fabric 0.14.10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/imLkL6R5

### Issue description

Reverting to 8.6.0 fixes the crash.

**Comment by Daihok41** [comment]
Can confirm got same crash
