### ISSUE TITLE
question

### ISSUE THREAD

**Issue by eririKashiwagi** [Snownee/Jade#185]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.6

### Modloader version

40.1.80

### Modpack info

https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Can i somehow enable showing items in containers without shifting?

**Comment by Snownee** [comment]
Plugin Config -> Minecraft ->

**Comment by eririKashiwagi** [comment]
> Plugin Config -> Minecraft ->

There's all on but don't work

**Comment by Snownee** [comment]
it is a number. I forget the exact name

**Comment by Snownee** [comment]
oh nevermind

**Comment by Snownee** [comment]
it is in jade-addons.toml

**Comment by eririKashiwagi** [comment]
> it is in jade-addons.toml

What should I write in it?

**Comment by Snownee** [comment]
normalShowAmount = 54

**Comment by eririKashiwagi** [comment]
> normalShowAmount = 54

But I can't even see those 9 items, what's the point?
Did u really got what i want?)

**Comment by Snownee** [comment]
it does not work in multiplayer

**Comment by eririKashiwagi** [comment]
> it does not work in multiplayer

U think so?
I played oneblock on server and it worked

**Comment by eririKashiwagi** [comment]
![2022-10-30_01 12 24](https://user-images.githubusercontent.com/84137738/204151541-0b831621-fbe2-4dc0-8b93-4bc4ea18069c.png)

**Comment by eririKashiwagi** [comment]
Well.. Anyway.. Thanks for trying to help)
