### ISSUE TITLE
Error When Looking At Entitys.

### ISSUE THREAD

**Issue by skyenyaa** [Snownee/Jade#187]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.6

### Modloader version

Forge: 40.1.86

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.githubusercontent.com/starlesskye/6a756eebe6095869de26eda4508fcf3d/raw/5f2e9401acad63e15b03b3102a9933db5909c386/latest.log

### Issue description

When I look at any entity it displays ERROR underneath the entity name in the infographic.
![2022-12-05_20 11 55](https://user-images.githubusercontent.com/119634839/205812153-135136fe-82f0-47cc-bdb0-55845a7eac38.png)

**Comment by Snownee** [comment]
please send your WailaErrorOutput.txt

**Comment by starlesskye** [comment]
[WailaErrorOutput.txt](https://github.com/Snownee/Jade/files/10163011/WailaErrorOutput.txt)

**Comment by skyenyaa** [comment]
https://gist.githubusercontent.com/starlesskye/1aa9e2aeda51f95b398321fd9c2de60f/raw/bcc2ec1731c2172f8eead4c1c5618243d9a9ec53/WailaErrorOutput.txt

**Comment by Snownee** [comment]
The Vampirism Integrations is incompatible with Jade

**Comment by skyenyaa** [comment]
oh okay! thank you for the information, and for your hard work! 💖
