### ISSUE TITLE
[Suggestion] Config to toggle details to always-on

### ISSUE THREAD

**Issue by Xetaxheb** [Snownee/Jade#188]
### Mod loader

Forge

### Minecraft version

1.18.2/any

### Mod version

5.2.6/any

### Modloader version

Forge 40.1.84

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Adding a toggle so shift or other keybind doesn't need to be held

**Comment by Xetaxheb** [comment]
If this is what Display Mode: Toggle rather than Display Mode: Lite is supposed to do then it's not working right. Lite hides things in a furnace while Toggle shows progress, but Toggle doesn't show things in chests or for example Create Millstone unless shift is held

**Comment by Snownee** [comment]
If you are playing Stoneblock 3, open `jade-addons.toml` and change the `normalShowAmount` option to 54

**Comment by Xetaxheb** [comment]
Yes, that's done it. How silly for that to be off.
