### ISSUE TITLE
[Request] Allow customizable keybind separate from crouch, and allow hold to toggle show

### ISSUE THREAD

**Issue by jengendler** [Snownee/Jade#19]
* Minecraft Version: 1.16.4+
 * Mod Version: Jade-1.16.4-2.3.2

What a BEAUTIFULLY built mod! It's a substantial improvement over the one I was previously using.

I'd like to request that the Show/Hide feature (which can currently be changed to 'on' or 'off' via a keybind) have an option to become toggleable in a way that when you hold the keybind, it shows, and when the keybind is released, it's hidden.

Additionally, I am not a fan of crouching to view storage contents, because, by it's very nature, crouching moves the crosshair. Too often, when looking at a storage block whose contents I wish to preview, I crouch down and now my crosshair is positioned over the block below. For this reason, I prefer changing my keybind from whatever my crouch key is, to something custom. This would be such a nice QoL improvement.

Hope you consider. Thanks for your time!

**Comment by Snownee** [comment]
1. I don't think they makes much differences
2. You can change that in `config/jade-common.toml`

**Comment by jengendler** [comment]
Thanks for replying. Unfortunately, I do not see an option to change the sneak keybind in the config file.

**Comment by Snownee** [comment]
`inventoryNormalShowAmount`

Set the number same as sneaking

**Comment by jengendler** [comment]
Yes, I was already aware of that config, but thank you so much for your assistance. I would still like to request the ability to change the "sneak to show" keybind via the Control menu. Thanks for considering!

**Comment by Snownee** [comment]
implemented in 1.17
