### ISSUE TITLE
Jade Crash on insatll

### ISSUE THREAD

**Issue by Zelioth** [Snownee/Jade#195]
### Mod loader

Forge

### Minecraft version

1.19.3

### Mod version

9.2.2-1.19.3

### Modloader version

44.0.30 Forge

### Modpack info

Friends United 1.19.3 (Testing Update)

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Zelioth/de126e4d74ea6546d6478b9d1c8e48dd

### Issue description

I'm testing and building the 1.19.3 pack for Friends United. I've installed jade and found this issue causing an instant crash. The issue seems to be fine if I install just jade into a 1.19.3 alone. So I assume it's a compatibility error. I've noticed that EVERY mod that has issues so far will for some reason report the exact same 

java.lang.IllegalArgumentException: No model for layer midnight-hats:witch_hat#main

and I'm unsure why. Disabling jade ONLY fixes the issue immediately. 

This file also generated. Jade Error Output
https://gist.github.com/Zelioth/0847b95c0e3fd2f24985035cb2419d79

**Comment by Snownee** [comment]
Please provide your latest.log

**Comment by Zelioth** [comment]
Debug
https://gist.github.com/Zelioth/27f24b1ad7dd1a8d73f5d118c777a88b

Log
https://gist.github.com/Zelioth/916ff9d5c5541967150e6f0a3fe974b4

**Comment by Snownee** [comment]
In log it says:
Mod ae2 only supports jade 8.0.0 or above, and below 9.0.0
Currently, jade is 9.2.2

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/208322241-b41e228e-b744-4403-b8ef-d321cf7fc2e0.png)

**Comment by Zelioth** [comment]
Awe, I guess I missed that. Sorry about that. Issue is fixed removing Ae2 and enabling Jade. Thank you for your assistance and hard work. I'll report it to ae2

**Comment by Snownee** [comment]
Could you help me report it to AE2 devs? Thanks
