### ISSUE TITLE
Duplicate item mod name tooltips with EMI

### ISSUE THREAD

**Issue by emilyploszaj** [Snownee/Jade#196]
### Mod loader

Fabric

### Minecraft version

1.18.2-1.19

### Mod version

*

### Modloader version

*

### Modpack info

N/A

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Both Jade and EMI append mod name to items, this results in 2 being present. I'd fix it on EMI's end, but EMI gets a bit more control when searching if it's able to suppress its mod name tooltip during indexing tooltips, so ideally this should be fixed on Jade's side.

![image](https://user-images.githubusercontent.com/14813658/208552657-b2eb204e-934d-4ff8-92d9-3295385c1338.png)

**Comment by Snownee** [comment]
Actually I don't know what I can do for you. As for users, they can always disable it in the configuration. And this has never been a problem for JEI or REI before, I think?

**Comment by emilyploszaj** [comment]
In the past I believe this method was used? It'd be pretty simple to check if `emi` is loaded and disable behavior like with the 2 other conditions I believe. https://github.com/Snownee/Jade/blob/1.19.1-fabric/src/main/java/snownee/jade/JadeClient.java#L152

**Comment by Snownee** [comment]
What if the user wants to change the color of the name? I don't think EMI has such a feature. They will just think Jade is broken.

**Comment by emilyploszaj** [comment]
This may be true, but as it stands every user knows something's broken, because they get two mod names on everything. And as it stands every recipe viewers display mod name information on contexts that jade doesn't have control over to consistently style, in EMI's case, fluids as stacks, item tags, and recipe categories at a minimum. Either way, one of the two mods is going to need to hide it by default, and it'd be better if that were Jade because otherwise EMI has no recourse to prevent mod names from showing up in tooltip searches.
