### ISSUE TITLE
masa全家桶除了投影都装了时, 打开设置界面会崩溃

### ISSUE THREAD

**Issue by Cjsah** [Snownee/Jade#197]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.10

### Modloader version

Fabric Loader 0.14.9 + API 0.58.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Cjsah/8dcb66e472a255f5f817c4dfaa68a7c9

### Issue description

没装投影, 却调用了这个类, 应该是bug吧...
(找了半天没找到这个lambda表达式)

**Comment by Snownee** [comment]
不要用tweakmyclient
