### ISSUE TITLE
[Feature] Shoulder Surfing Compatibility

### ISSUE THREAD

**Issue by hhamelin** [Snownee/Jade#198]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.6.3

### Modloader version

43.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

There is an incompatibility with the shoulder surfing mod. When in the shoulder surfing perspective, the block highlighted by the cross hair will not match the block shown by Jade. This issue was resolved with WTHIT with the addition of an API, as seen in the issue thread [here](https://github.com/Exopandora/ShoulderSurfing/issues/85).

**Comment by Snownee** [comment]
You can always replace the ray trace target. See https://github.com/Snownee/Jade/blob/1.19.1-forge/src/main/java/snownee/jade/api/IWailaClientRegistration.java#L136 https://jademc.readthedocs.io/en/latest/plugins19/overrides/
