### ISSUE TITLE
Not working with mekanism mod

### ISSUE THREAD

**Issue by hanzupp3r** [Snownee/Jade#199]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

forge-8.6.3

### Modloader version

Forge 43.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Not showing mikanism: liquids, gases, energy
exacly not showing enythink from this mod

**Comment by Snownee** [comment]
Have you installed Jade on the server?
