### ISSUE TITLE
Update for 1.14.4 / 1.15.2?

### ISSUE THREAD

**Issue by Omnimetatron** [Snownee/Jade#2]
* Minecraft Version: 1.14.4 / 1.15.2
 * Mod Version: 0.1.0

This mod looks fantastic, would really appreciate an update if possible.

**Comment by Sol-on-github** [comment]
I 2nd this
Also, is it fabric?

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/jade/files/2953395

**Comment by Snownee** [comment]
> I 2nd this
> Also, is it fabric?

@Sol-on-github Currently no plan
