### ISSUE TITLE
got a ClassCastException by inspecting Player Grave from Universal Graves Mod

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#202]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.7.0

### Modloader version

Fabric Loader 0.14.12 + API 0.72.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/gobletm/0b4c77b4c67ffe23478fd6bcca976774

### Issue description

Well i died, walked to my Grave and Jade showed me the message "Error from Polymer (Core) mod, plz report."
So i opened the log files an saw the error java.lang.ClassCastException: class snownee.jade.addon.core.RegistryNameProvider$Mode cannot be cast to class java.lang.Boolean

I could reproduce the error in a clean install with only the jade and the universal-grades mod installed.

**Comment by Snownee** [comment]
@Patbox Hi. Please take a look at this

**Comment by Patbox** [comment]
Install latest polymer version (for your mc version) and check if it still happens

**Comment by ghost** [comment]
Okey thx for the reply.
i checked with version 0.2.23 and it works now.
