### ISSUE TITLE
[1.18.2_Forge]When looking straight down, MTR information is always displayed.

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#203]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.6

### Modloader version

40.1.93

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/sweetymajo/0bd5c556309f81c271a3a8b84711315f

### Issue description

When installed with the MTR mod, when viewing the block below the character, the item information of the MTR mod will always be displayed instead of the correct information of the block.

**Comment by Snownee** [comment]
Not my issue. Please report it to MTR
