### ISSUE TITLE
Font looks weird compared to other mods

### ISSUE THREAD

**Issue by stantios** [Snownee/Jade#208]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.7.3

### Modloader version

Quilt: 0.17.10 and QFAPI / QSL: QFAPI 4.0.0-beta.27 and QSL 3.0.0-beta.29

### Modpack info

https://modrinth.com/modpack/fabulously-optimized but with some added mods

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/kq5KqxL

### Issue description

Description: The font looks weird compared to other mods like WTHIT (not the best at describing things)

Screenshots - Jade: 
![image](https://user-images.githubusercontent.com/98621617/215863301-8081dfb9-cd3e-4ed2-ab93-7615b8089997.png)

WTHIT: 
![image](https://user-images.githubusercontent.com/98621617/215863867-89b763d6-0569-4bd9-985b-05bd7474c127.png)

**Comment by Snownee** [comment]
Could you send your jade's config folder?

**Comment by stantios** [comment]
Sure! I'll zip it up and send it to you

**Comment by stantios** [comment]
Here you go: 
[Jade.zip](https://github.com/Snownee/Jade/files/10550262/Jade.zip)
