### ISSUE TITLE
Server auto-quits on spawn in

### ISSUE THREAD

**Issue by Vampy482** [Snownee/Jade#210]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

16.5

### Modloader version

Fabric: Loader 0.14.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/uLaBnQwN

### Issue description

Game crashes on launch claiming there's an NBT tag that's too big... image attached of error message. Game is soft-locked and cannot spawn into server without crashing. Fix involved removing mod completely.

![error image](https://user-images.githubusercontent.com/124336533/216527125-489ff296-089f-4c2e-904f-4cea89ba4255.png)

**Comment by suerion** [comment]
If you use Create in the Modback, Create is the problem on our side, It is a Problem with Schematics

**Comment by Snownee** [comment]
"crashes on launch"...? It seems to happen after you join the server.
