### ISSUE TITLE
Missing Keypad

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#211]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.1.0

### Modloader version

Forge: 14.23.5.2860

### Modpack info

RLCraft 2.9.1c

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

No way to enable overlay without a keypad. The keybinding is not shown and unchangeable. This problem potentially affects all laptop users.

**Comment by Snownee** [comment]
Does RLCraft have Jade?

**Comment by ghost** [comment]
I added it myself and it’s now working.

**Comment by Snownee** [comment]
Can't you change it in the vanilla's keybind settings?

**Comment by ghost** [comment]
RLCraft has a keybinding searching mod installed. So, the keybinding interface is not completely vanilla, but I'm sure that jade is not in the in-game keybinding setting page.

**Comment by ghost** [comment]
<img width="699" alt="截屏2023-02-12 下午12 19 45" src="https://user-images.githubusercontent.com/102125628/218329396-3a818948-0fc4-4c56-843e-0d5bbd0c9a8a.png">

**Comment by Snownee** [comment]
1.12.2Jade只是Hwyla的附属，可能是你没安装Hwyla，也可能是Hwyla的问题，总之与Jade无关
