### ISSUE TITLE
Advancement Plaques Compat

### ISSUE THREAD

**Issue by Matthysse** [Snownee/Jade#212]
### Mod loader

Forge

### Minecraft version

x.x.x

### Mod version

x.x.x

### Modloader version

Forge and Fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello!

It would be nice if the HUD would go lower when an advancement plaque from the mod is shown, just as what it does when a boss bar appears.

**Comment by Snownee** [comment]
This is out of the scope of Jade itself. Please contact the developer of that mod
