### ISSUE TITLE
Tooltip not updating with ReplayMod sometimes

### ISSUE THREAD

**Issue by a1375625918** [Snownee/Jade#213]
### Mod loader

Fabric

### Minecraft version

1.19.3

### Mod version

9.3.1

### Modloader version

Fabric Loader 0.14.12 + API 0.73.2

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/krVHFtg6

### Issue description

If I join a Fabric server with Jade first, and a vanilla server then, Jade won't update tooltip for entities and some blocks.

![1](https://user-images.githubusercontent.com/87858091/218924879-e9cf5dec-2717-47ab-9d6a-367098748a48.png)
I join the Fabric server with ReplayMod `Record Server` enabled. Everything works fine.

![2](https://user-images.githubusercontent.com/87858091/218924982-0fbe51a2-2a5f-4212-8658-b31b4d8ee6f9.png)
Then I join a vanilla server. Jade doesn't show any information for the chest I'm looking at even the basic one, but the grass block or the log before I move my pointer to the chest.

**Comment by Snownee** [comment]
https://github.com/ReplayMod/ReplayMod/issues/865
