### ISSUE TITLE
It doesn't show animal owner on multiplayer server

### ISSUE THREAD

**Issue by Hunteriino** [Snownee/Jade#214]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.0

### Modloader version

Forge: 43.2.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/minecolonies-official

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Well, first of all, I don't know if this is an issue, or I'm doing something bad.

I'm hosting server with the same forge I typed before and when looking at some tamed entity, It shows me "**Owner: ???**".
I don't know if it's because of **online mode** set to **false**.
Furthermore, I was confused, so I went to try it in single player world. I launched single player world, tamed a horse, and It did show true owner and not "???" like in server.

**Comment by Snownee** [comment]
This is normal. Sometimes it is not possible to get the user name of the owner, especially if you and the owner were not in the server at the same time
