### ISSUE TITLE
The localization missing with Immersive Engineering plugin setting

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [Snownee/Jade#216]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.0

### Modloader version

Forge 43.2.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I found the localization missing when I visited IE's plugin setting UI.
![2023-02-23_16 56 12](https://user-images.githubusercontent.com/37864486/220861774-77df8661-44bc-4571-8cc5-dcf6490c6238.png)

**Comment by Snownee** [comment]
please report it to the IE devs
