### ISSUE TITLE
Crash when looking at a Soul Crystal containing Souls (Spirit Mod)

### ISSUE THREAD

**Issue by Clark919** [Snownee/Jade#220]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.7.3

### Modloader version

Fabric Loader: 0.14.15 + API: 0.75.1+1.19.2

### Modpack info

https://www.curseforge.com/minecraft/modpacks/origination-fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/VCeCvc1V

### Issue description

When looking at a Soul Crystal from Spirit with Jade installed, a crash occurs. An error message is visible as under the item's description for a moment, assuming you do not crash immediately. I was unable to screenshot this issue as the game immediately closes to desktop. I have provided JadeErrorOutput.txt confirming it is this item in particular causing the fatal error.

**Comment by Snownee** [comment]
please report it to their devs
