### ISSUE TITLE
Feature Request: Disable Item Entity Tooltips

### ISSUE THREAD

**Issue by Boobies** [Snownee/Jade#221]
### Mod loader

Fabric

### Minecraft version

1.19.4

### Mod version

10.0.0

### Modloader version

Loader 0.14.17 + API 0.76.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I've requested this for WTHIT as well but recently moved to Jade. I mostly find Jade useful for mobs but not item entities because while it can be useful under certain circumstances, for the most part I just see something like sand on the floor and get a useless tooltip telling me it's sand.

**Comment by Snownee** [comment]
you can input the entity type ids in `jade/hide-entities.json`

**Comment by Boobies** [comment]
Thanks. That worked. But I think that at the very least, if you're feeling too lazy to add a proper UI to input the entities you should at least have a button that opens the relevant JSON file just so this functionality is exposed. Cause when there is a config screen, no one bothers checking for secret config options in the config files.
