### ISSUE TITLE
Tooltip mistake when Jade shows dropped item entity with socket of Apotheosis.

### ISSUE THREAD

**Issue by rtxyd** [Snownee/Jade#223]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.1

### Modloader version

forge 42.3.6

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

MC version: 1.19.2
placebo: 7.1.7
Apotheosis: 6.1.5
Jade: 8.8.1

This will not influence gameplay. But may provide some message.
Test with the same item.

![4AR~W{KK6N~M%{$G}0N486Q](https://user-images.githubusercontent.com/65117312/227404973-e5f11f04-bf6c-4310-ab4f-be9f116aebca.png)

![image](https://user-images.githubusercontent.com/65117312/227405369-8b88ca7a-e335-4549-9819-094d0e67deb6.png)

**Comment by Snownee** [comment]
This is related to Apotheosis. Nothing I can do about it

**Comment by rtxyd** [comment]
@Snownee Author of apotheosis says this is about jade

![image](https://user-images.githubusercontent.com/65117312/227453193-5c710d78-7d95-483f-b24f-83cadc7695e7.png)
