### ISSUE TITLE
[1.18.2]  Waystones Error Output

### ISSUE THREAD

**Issue by Reshy** [Snownee/Jade#224]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

Jade-1.18.2-forge-5.2.6.jar

### Modloader version

40.2.1

### Modpack info

Custom, includes Integrated Strongholds and required mods.

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Cbu3N4ES

### Issue description

Got an error output when a Waystone was being generated, it pushed out an old Waila Error.  Caused the world to stop rendering properly:

![2023-03-23_23 43 58](https://user-images.githubusercontent.com/2096384/227449765-d82360f9-415a-4f3c-9603-3d90aa98d1d8.png)

**Comment by Snownee** [comment]
How do you know it is Jade causing the world to stop rendering?

**Comment by Reshy** [comment]
I don't, though I can report this on Waystones as well.  Your mod's a fork of Waila, and that's where the error was stated to have originated.

**Comment by Snownee** [comment]
Does it stop rendering only when you point at waystone?

**Comment by Reshy** [comment]
No, the gap remains any time those chunks are in view.

**Comment by Snownee** [comment]
So that's the point. In my opinion, they are different issues. The error output issue has been reported before: #112
