### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Willem07** [Snownee/Jade#225]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.1

### Modloader version

forge-43.2.8

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Is it possible to disable tooltip for specific modified mobs, but leave it for ordinary mobs in the hide-entities.json config?
![2023-03-29_16 22 50](https://user-images.githubusercontent.com/51959206/228553024-eaad1f91-3c90-42c3-9089-aeb4672bd3e5.png)
![2023-03-29_16 29 44](https://user-images.githubusercontent.com/51959206/228553724-cb2428b9-aba0-437b-9d9a-b17bb0991ea2.png)

**Comment by Willem07** [comment]
Thanks, I forgot the double quotes😆

**Comment by Snownee** [comment]
```json
["minecraft:blaze", "minecraft:pig"]
```
