### ISSUE TITLE
Jade Crashes w/ Mcreator

### ISSUE THREAD

**Issue by APrimevalWorld** [Snownee/Jade#226]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Jade-1.19.1-forge-8.8.0

### Modloader version

Forge: 43.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/e54XHvUf

### Issue description

You might be looking at the title and thinking 'Oh no, an Mcreator user' but I just want to make developed mods that can inspire others to do the same. Either way, I've been trying to create an entity for zombies to chase that spawns at the player, but the only way to see it would be to use TOP or Jade. TOP refused to work, but Jade at least got into the loading process before Minecraft gave me an error. If anyone could help out, whether it means changing my code or something, it would be very much appreciated.

The error is a 'java.lang.NoSuchFieldError' followed by 'f_82467'

**Comment by APrimevalWorld** [comment]
PS: I just did a quick test and it also has the same problem with the API or without the API, and on the latest 1.19.2 version published.

**Comment by Snownee** [comment]
https://mcreator.net/plugin/84967/shadowsapis
