### ISSUE TITLE
一些功能添加到低版本

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#227]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

x

### Modloader version

X

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

不知能否将高版本一些功能加到低版本。
![image](https://user-images.githubusercontent.com/83486178/230032140-87967414-01c5-45d7-8e88-7b1af621247c.png)

**Comment by Snownee** [comment]
1.16不再维护
