### ISSUE TITLE
minecraft crashing

### ISSUE THREAD

**Issue by waliser** [Snownee/Jade#230]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.6

### Modloader version

forge 40.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

minecraft keep crashing when i try to launch mc
![image](https://user-images.githubusercontent.com/89495658/231104345-79f2bdab-4f2f-4631-b71f-887c1e2ae012.png)

**Comment by Snownee** [comment]
Please provide your `latest.log` and crash report.
