### ISSUE TITLE
Enhanced Boss Bar Compat

### ISSUE THREAD

**Issue by LunarDev-git** [Snownee/Jade#235]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Jade-1.19.1-forge-8.8.1.jar

### Modloader version

Forge 43.2.8

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

The issue is plain and simple. When using Enhanced Boss Bars, the bar will pop up twice. 

Screenshot: https://imgur.com/a/ayP2HOD
Texture Pack: https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars/

**Comment by Snownee** [comment]
I can't fix it. What this resource pack does is replace the name of the entity with a custom font. There is even no way to get the original name.

**Comment by kasperbjerby** [comment]
Maybe a option (if there are not already one), to disable Jade for entities that have a boss bar? Or hide the name if it has a boss bar or something.. Don't even know if you are able to check if a mob has a boss bar, its just an idea

**Comment by Snownee** [comment]
> Maybe a option (if there are not already one), to disable Jade for entities that have a boss bar? Or hide the name if it has a boss bar or something.. Don't even know if you are able to check if a mob has a boss bar, its just an idea

It is possible. You can create a new issue for it
