### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by deinozirion** [Snownee/Jade#236]
### Mod loader

Forge

### Minecraft version

1.19.4

### Mod version

10.0.0

### Modloader version

Fabric Loader 0.14.18

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/c4QjX7dE

### Issue description

Visual bug when crosshair is on a mob and Jade displays their hearts. Only in The Nether and in The End dimensions, in the overworld works as intended. No other mods leaded.

When "Display Mode" is in Lite, the problem dissapears. There's no visual bug when pressing SHIFT while looking at a mob, but if you press SHIFT and THEN you look at a mob, the visual bug appears. Follow the imgur link for a video reference of the visual bug.

https://imgur.com/gallery/t3mYIth

With Sodium, Lithium and Starlight, the bug is less noticeable.

**Comment by Snownee** [comment]
I don't see where the bug is

**Comment by imjustarock** [comment]
Can reproduce this on Jade 10.0.0 on Fabric, it appears as if all mobs briefly flash when you start looking at one in the Nether/End.

**Comment by deinozirion** [comment]
> I don't see where the bug is

Here's another example...
https://imgur.com/gallery/0zodMrT
notice how the hopper also glitches and some items in my right hand.
