### ISSUE TITLE
Destroying Create train tracks causes ponder

### ISSUE THREAD

**Issue by SerenModz21** [Snownee/Jade#237]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.7.3

### Modloader version

Fabric Loader 0.14.12 + API 0.76.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

I don't think logs are required for this issue

### Issue description

Whilst destroying train tracks and picking them up, the ponder screen is constantly displayed. This occurs whilst running or walking whilst destroying them. This issue has been happening to our users that use Jade.

I originally reported this issue to Create (https://github.com/Fabricators-of-Create/Create/issues/904), however, found out by [Cart3r1234](https://github.com/Cart3r1234) that Jade was the cause of this issue. To test this for myself, I clicked the hotkey to toggle the Jade overlay and as expected, the issue stopped occurring.

I am also using JadeAddons 3.1.0.

A video can be seen below showing a visual of what is happening.

https://user-images.githubusercontent.com/41450647/235393327-d5ecce25-10f9-4f52-ac75-816946c559cc.mp4

**Comment by Snownee** [comment]
Fixed from Jade Addons
