### ISSUE TITLE
Enchanting table not showing Level

### ISSUE THREAD

**Issue by ffuentesm** [Snownee/Jade#246]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.1

### Modloader version

43.2.11

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I am using Easy Magic ver: 4.3.3
It allows the enchanting table to store items and lapis inside of it and display the hidden enchanting options. 

I am not sure if that mod affects Jade in any way, but for some reason, I can not see the enchanting level of the table on display
but the lapis stored inside it.
![image](https://github.com/Snownee/Jade/assets/44974827/3fd24df2-251f-4acb-a8a2-22ffcc27baf9)

**Comment by Snownee** [comment]
I think it is because there is snow between the table and the bookshelves.

**Comment by ffuentesm** [comment]
hum, would be possible to bypass that? 
Easy Magic makes it so that transparent blocks do not block the enchanting level up.

**Comment by Snownee** [comment]
That requires changes from both projects. I have added the support for Jade 1.20. But I am afraid I will be too lazy to backport it
