### ISSUE TITLE
[Forge 1.19.2] Boss Bar Overlap not Working

### ISSUE THREAD

**Issue by Aulberon** [Snownee/Jade#247]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.1

### Modloader version

Forge 43.2.8

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I'm not sure if I could call this a bug, but basically, the option "Push Down Tooltip" for "Boss Bar Overlaps" doesn't work when using the mod "[Advanced Compass](https://www.curseforge.com/minecraft/mc-mods/advanced-compass)".
The tooltip stays over the bar no matter what.
Here is a printscreen to show how it looks:
![image](https://github.com/Snownee/Jade/assets/39103311/ff3561b4-6ac3-441e-8051-f63ca94ba7ce)

**Comment by Snownee** [comment]
Due to the way the mod moves the boss bar, I can't fix it. You can try to report it to their dev
