### ISSUE TITLE
HT's TreeChop mod shows error

### ISSUE THREAD

**Issue by Cape-City** [Snownee/Jade#248]
### Mod loader

Fabric

### Minecraft version

1.19.3

### Mod version

9.4.1

### Modloader version

Fabric: Loader 0.14.21 - fabric-api-0.76.1+1.19.3.jar

### Modpack info

Monty McDonnell's - A New World

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Cape-City/c51dbda8e1c25bb7fbf3a5fd687b4d48

### Issue description

Hi,

this error is shown, don't know if the issue is on your side?

![grafik](https://github.com/Snownee/Jade/assets/122229367/1f2a7757-9815-42c9-a27a-1917b9e76a5d)

**Comment by Snownee** [comment]
Reference: https://github.com/hammertater/treechop/issues/200
