### ISSUE TITLE
Question about Maven/API Jar

### ISSUE THREAD

**Issue by pupnewfster** [Snownee/Jade#25]
* Minecraft Version: 1.16.5
 * Mod Version: 2.4.2 or any?

This is in part a question/request depending on the answer. I started looking at changing the dev version of Hwyla I build against to Jade as Hwyla seems to be end of life, but there are two issues I am running into before doing so.
- First off is there a maven for Jade or is it expected that addon developers just use cursemaven?
- Secondly assuming it is expected to use cursemaven, would you mind also uploading the API jar as an "additional" file? That would allow me to continue declaring in my build.gradle a compileOnly dep against the API and a runtimeOnly against the actual mod. Note: Additional files are a a thing that curse lets you upload when looking at individual existing files and are sort of a "sub file".

**Comment by Snownee** [comment]
Thank you. I will upload API jars in the future
