### ISSUE TITLE
Donkey/Mule stats

### ISSUE THREAD

**Issue by tori1277** [Snownee/Jade#252]
### Mod loader

Fabric

### Minecraft version

1.19.4

### Mod version

10.0.0

### Modloader version

fabric-api-0.77.0+1.19.4

### Modpack info

Fabulously Optimized https://www.curseforge.com/minecraft/modpacks/fabulously-optimized

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Donkeys and Mules have variable stats after being bred, just like horses, but only their health and breeding timer display, not jump and speed stats. Easily replicable in singleplayer.

**Comment by Snownee** [comment]
https://minecraft.fandom.com/wiki/Mule#Movement_speed

**Comment by tori1277** [comment]
Donkeys spawn with the same speed stats, but when they are bred, they can have the same variety of stats as horses. these speed stats do not show in jade, and neither does the jump stat
