### ISSUE TITLE
[Suggestion] Add Blast resistance value

### ISSUE THREAD

**Issue by ffuentesm** [Snownee/Jade#253]
### Mod loader

Forge

### Minecraft version

1.20

### Mod version

11.0.3

### Modloader version

forge 46.0.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Add an ability for the Block blast resistance level and hardness level. In case A mod adds unique mining levels.

**Comment by Snownee** [comment]
> In case A mod adds unique mining levels

what is the relationship?

**Comment by Snownee** [comment]
What is the use case? I think 99.9% of players will not need this feature.
