### ISSUE TITLE
Jade mixin injection fail

### ISSUE THREAD

**Issue by ghost** [Snownee/Jade#254]
### Mod loader

Forge

### Minecraft version

1.20

### Mod version

11.0.3

### Modloader version

Forge 46.01 and 46.0.10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/czwEhHg3

### Issue description

In Dev environment Im trying to update my mod to 1.20.  When I include Jade (which I have for previous versions of my mod) I get critical mixin errors from Jade for Minecraft 1.20

https://pastebin.com/CsGSFDBS

Maybe Ive done something wrong, not updated something?  Tried with Forge 46.0.1 and 46.0.10

**Comment by Snownee** [comment]
I have no clue about this so far. If anyone has the same problem, a reply would be appreciated

But it seems that this method exists:
[https://linkie.shedaniel.dev/mappings?namespace=mojang_srg&version=1.20&search=m_109093_](https://linkie.shedaniel.dev/mappings?namespace=mojang_srg&version=1.20&search=m_109093_)

**Comment by ghost** [comment]
given you access to my very small project in case you want to have a look

**Comment by Snownee** [comment]
it looks good

**Comment by OJayyusiO** [comment]
yep, jade is also causing my game to fail to initialize and crash, i can send you the modpack list of mods and crash report

**Comment by Snownee** [comment]
> yep, jade is also causing my game to fail to initialize and crash, i can send you the modpack list of mods and crash report

Yes, please

**Comment by OJayyusiO** [comment]
nvm, my whole modpack is buggy, even though it runs without jade, other mods arent working properly so could be something else, jade works fine on my other modpack

**Comment by ghost** [comment]
So I updated to Minecraft 1.20.1 and Jade 1.20.1, and all seems to be fine. So I don't really know what was happening

I have a couple of other projects that have Jade integration so I will keep an eye on it, but for now all is good

**Comment by ghost** [comment]
Just to note that I added One Probe support to my CardboardBox mod and Jade is now giving the same mixin issue - I removed all One Probe references and Jade still gives the same mixin error

really dont know whats happening

I should state this is just in DEV that the error happens, seems to run fine outside DEV

**Comment by ghost** [comment]
so I think Ive cured this

I added the following to my build gradle and re-ran genintellijruns and a project that previously failed now works
```
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
```

The project that failed does not use mixins but this seems to work - got the idea from reading the Curios wiki - my failed project does not use Curios, but I thought I would make this change anyway

**Comment by Snownee** [comment]
It seems I can no longer access your repo.

**Comment by ghost** [comment]
it still shows you as a collaborator? - my projects are private now because of someone blatently stealing a mod of mine and CurseForge doing nothing about it

https://github.com/WallyWhip/TheCardboardBoxMod


![image](https://github.com/Snownee/Jade/assets/107043954/d4ce9859-9832-4997-9b82-950ba0797668)
