### ISSUE TITLE
Hide names? 

### ISSUE THREAD

**Issue by Vitaaliyy** [Snownee/Jade#256]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.6

### Modloader version

40.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello, I don't know where to ask this, so I'm doing it here, sorry if it's not the right place! 

Is there any way to hide player names in Jade? We have lore on the server, so we would like to have different characters but it's annoying if we can see the name of the player on top, thank you.

**Comment by Snownee** [comment]
edit `config/jade/hide-entities.json`

**Comment by Vitaaliyy** [comment]
Hello again, I can't find it, in config I only have jade-plugins.json

**Comment by Snownee** [comment]
please update to 5.3.0

**Comment by Vitaaliyy** [comment]
Hello, can I reopen this? Still trying to find the solution for another server, we have the latest version of Jade 11.8.0 for 1.20.1 on Forge. I only have hide-entities.json in my OWN mod folder, not in the server config, right? 

We're trying to find a solution so that none of the players on the server would be able to see people's usernames on Jade. We have a mod to change names, but it doesn't change names on Jade, that's our problem. 

Thank you for you time.

**Comment by Snownee** [comment]
what is the mod?

**Comment by Vitaaliyy** [comment]
The mod is Hidden Names, we tried with another one named "Fake Name" but it made the server crash for some reason, I think we don't have the right Forge version unfortunately

**Comment by Snownee** [comment]
what do you want to do, hide names or show the correct modified names?

**Comment by Vitaaliyy** [comment]
If seeing the correct one is possible, then yeah I would love to be able to see the correct modified names!

**Comment by SaintObstinate** [comment]
Hi there, I'm so sorry  for reopenning this, but I'm still trying to figure it out somehow... I tried the Fakename Mod, and also the Hidden Names that Vitaaliyy mentioned, and it still doesnt work, do I really need to have a plugin to modify the display name on Jade? 
I'm trying to hide the names of the admins on my server, but I dont want to hide the player names... Is there a way to do this without plugins?

**Comment by Snownee** [comment]
> Hi there, I'm so sorry for reopenning this, but I'm still trying to figure it out somehow... I tried the Fakename Mod, and also the Hidden Names that Vitaaliyy mentioned, and it still doesnt work, do I really need to have a plugin to modify the display name on Jade? I'm trying to hide the names of the admins on my server, but I dont want to hide the player names... Is there a way to do this without plugins?

What are your mod versions?

**Comment by SaintObstinate** [comment]
> > Hi there, I'm so sorry for reopenning this, but I'm still trying to figure it out somehow... I tried the Fakename Mod, and also the Hidden Names that Vitaaliyy mentioned, and it still doesnt work, do I really need to have a plugin to modify the display name on Jade? I'm trying to hide the names of the admins on my server, but I dont want to hide the player names... Is there a way to do this without plugins?
> 
> What are your mod versions?

I am using minecraft 1.20.1, and Jade 11.12.3, and fakename-port: 1.3.1

**Comment by SaintObstinate** [comment]
Hey, any news on this? Am I being dumb? so sorry to bother

**Comment by Snownee** [comment]
![Image](https://github.com/user-attachments/assets/491606d5-5095-41b1-bb9f-e1b2ca2342b0)

Fakename is not supported. You can use Hidden Names

**Comment by SaintObstinate** [comment]
I tried hidden names, but it didnt work as well:
![Image](https://github.com/user-attachments/assets/4d300b21-778e-4295-8f2f-b9ac6eb7c83b)

![Image](https://github.com/user-attachments/assets/09c743fc-7752-489f-80eb-c8c00c5ea6c4)

is there a config I need to change?
