### ISSUE TITLE
Required tool will most often display as a box

### ISSUE THREAD

**Issue by DalekCraft2** [Snownee/Jade#26]
* Minecraft Version: 1.16.5
 * Mod Version: 2.4.2

The required tools for most blocks tends to display as a symbol similar to [].

![image](https://user-images.githubusercontent.com/50336832/108910804-61e80e00-75f4-11eb-8920-982929f4eefd.png)

**Comment by brawaru** [comment]
That is probably because you have Unicode font on. Consider going into Languages options and change ‘Force Unicode Font’ to OFF.

**Comment by DalekCraft2** [comment]
But blocks like snow display "Shovel" rather than a shovel icon. May I suggest that an option exists for whether the tool is displayed as an icon or as a word?
