### ISSUE TITLE
jade does not work correctly when displaying the player's nickname when wearing a thief helmet

### ISSUE THREAD

**Issue by GitJhopa** [Snownee/Jade#261]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

latest

### Modloader version

Forge latest 1.19.2

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

no logs.

### Issue description

https://legacy.curseforge.com/minecraft/mc-mods/environmental

This mod has a THIEF HELMET that hides the player's nickname, but when I hover over the player JADE shows his nickname. Please fix it.

**Comment by Snownee** [comment]
This is out of the scope of Jade itself. Please contact the developer of that mod
