### ISSUE TITLE
unnamed horses

### ISSUE THREAD

**Issue by DIVINIUM-115** [Snownee/Jade#262]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.1

### Modloader version

Forge 43.2.14

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

The horses don't have names

### Issue description

I tried without any mod and with mods and the horses are the only ones without a name from what I've seen

**Comment by Snownee** [comment]
please create a new world and disable all resource packs and test it again
