### ISSUE TITLE
Incompatible with OptiFine

### ISSUE THREAD

**Issue by TranMC** [Snownee/Jade#263]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.0.3

### Modloader version

47.0.16

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/TranMC/43a5088c500d41963e03cb25a7fe4907

### Issue description

I can't loaded the mod for some problem, can you check again please?

**Comment by Snownee** [comment]
try removing Optifine

**Comment by ghost** [comment]
I believe this is the same error I was getting in Dev. No Optifine loaded for me. Can confirm it works fine for my chickens mod but not 2 of my smaller simpler mods?

My chickens mod has Jade integration - works sometimes
My other 2 mods simply have jade loaded in Dev - fails with mixin injection failure

its weird  #254

**Comment by TranMC** [comment]
> try removing Optifine

It's work, but kinda sad because i can't use both of them, thanks

Can you make it compatible with optifine pls?

**Comment by Snownee** [comment]
I need time to investigate it

[Why you shouldn’t use OptiFine](https://forum.quiltmc.org/t/why-you-shouldnt-use-optifine/78)

**Comment by Duxtorm** [comment]
> > try removing Optifine
> 
> It's work, but kinda sad because i can't use both of them, thanks
> 
> Can you make it compatible with optifine pls?

I second this

**Comment by youlan2333** [comment]
1.20，too😥

**Comment by Snownee** [comment]
comment below if it is still crashing with the latest beta of Jade
