### ISSUE TITLE
Creative Menu Item Search behavior is changed

### ISSUE THREAD

**Issue by AmongstReality** [Snownee/Jade#265]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.1.3

### Modloader version

Fabric loader 0.14.21-1.20.1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Creative Search just doesn't search anything, as long you input anything from below:
- craft
- craf
- cra
- cr
- c
- raft
- raf
- ra
- r
- aft
- af
- a
- ft
- f
I've tested everything and it is not fault of any other mod, because this happens even when only Jade installed(fabric api included of course)

**Comment by Snownee** [comment]
Can you give me a screenshot? What language are you using?

![image](https://github.com/Snownee/Jade/assets/16059084/ddd7a86c-527b-49bd-b93c-1d5b0c70977e)

**Comment by Snownee** [comment]
That is because all the items are from "Minecraft". You can disable the mod name in the item tooltip, or search in JEI or REI instead
