### ISSUE TITLE
[1.20 forge] failing to get com.modrinth.minotaur

### ISSUE THREAD

**Issue by Christofmeg** [Snownee/Jade#269]
### Mod loader

Forge

### Minecraft version

1.20

### Mod version

11.1.4

### Modloader version

Forge: 46.0.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Christofmeg/0fd6dea61f8942ac019adf7c485b1554

### Issue description

Unable to build the 1.20 forge branch.

**Comment by Snownee** [comment]
I know nothing about gradle. I read the README of Minotaur and can't see what's wrong with it
