### ISSUE TITLE
Configure the format of the text

### ISSUE THREAD

**Issue by hyplant** [Snownee/Jade#270]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.2.0

### Modloader version

fabric loader0.14.21 api0.85.0

### Modpack info

无

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Configure the format of the text.
In WTHIT ,the format of text (for example, the block, fluid and entities)can be edited
 
Screenshot of the config file of WTHIT
![Screenshot_20230710-102441_MT Manager](https://github.com/Snownee/Jade/assets/86937725/b8c0111f-e0db-445e-8c5c-8ebb6345be70)

But in jade, only the format of the mod name can be changed

**Comment by Snownee** [comment]
I don't like this feature. It's useless and can cause many problems.
