### ISSUE TITLE
No changelogs?

### ISSUE THREAD

**Issue by MenacingPerson** [Snownee/Jade#271]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.2.0

### Modloader version

n/a

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Why are there no changelogs? Please add them (at least in future versions). Thanks.

I'm asking cause the latest fabric 1.20.1 release is suddenly marked as a beta. I'm not sure as to why exactly.

**Comment by Snownee** [comment]
> Why are there no changelogs?

Because it takes effort

There will be changelogs for future versions in 1.20+.

A beta version means it might be unstable, you can choose to update it or not. It does not really matter

**Comment by MenacingPerson** [comment]
oh alright then

Thank you!
