### ISSUE TITLE
【1.20.X】考古更新中的可疑的砂砾以及可疑的沙子未能正确识别

### ISSUE THREAD

**Issue by Strl3aker** [Snownee/Jade#272]
### Mod loader

Fabric

### Minecraft version

1.20and1.20.1

### Mod version

Jade-1.20-fabric-11.2.2

### Modloader version

Fabric 0.14.21+Fabric api 0.84.0

### Modpack info

No response

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

No response

### Issue description

在游戏中，生存模式以及冒险模式未能正确识别**可疑的砂砾/可疑的沙子**，但在创造模式以及旁观者模式中可以正确识别**可疑的砂砾/可疑的沙子**

**Comment by Snownee** [comment]
这是特性
