### ISSUE TITLE
Jade is not showing info for the things im looking at in 1.12.2

### ISSUE THREAD

**Issue by Devilswarchild** [Snownee/Jade#273]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

Jade-0.1.0.jar

### Modloader version

Forge - 14.23.5.2860

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

[latest_log](https://mclo.gs/vKB5ZTQ)

### Issue description

just looking around and testing certain things in what is essentially a remodel of my modpack for 1.12.2 and I have quickly noticed throughout all of my tests that the tooltips for what im actually looking at be it a grass block, leaves or whatever is not showing at all.
however that being said, anything newer than 1.12.2 works just fine. not sure what's causing it not to load
screenshot for proof

![Screenshot_1](https://github.com/Snownee/Jade/assets/27385258/ee064fe1-f5df-440e-969c-77405652a748)

**Comment by Snownee** [comment]
Can you see the overlay without jade?

**Comment by Devilswarchild** [comment]
what do you mean by overlay? like the tooltip overlay or?

**Comment by Snownee** [comment]
the tooltip overlay

**Comment by Devilswarchild** [comment]
uhhh not as far as ive seen, i dont even see the control hotkeys listed for jade in the controls options menu in-game either

**Comment by Snownee** [comment]
this has nothing with Jade. Jade does not provide keybinds in 1.12.2, Hwyla provides them. I doubt you have Hwyla installed correctly.

**Comment by Devilswarchild** [comment]
then why this?
![Screenshot_3](https://github.com/Snownee/Jade/assets/27385258/737334a3-c93f-41a2-802d-886f0ae65e83)

**Comment by Snownee** [comment]
This is for 1.16+. Jade for 1.12.2 is no longer maintained
