### ISSUE TITLE
Toggle narrator stutter

### ISSUE THREAD

**Issue by catherinedoyel** [Snownee/Jade#275]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.1.4

### Modloader version

Quilt 0.19.1 qfapi-7.0.4_qsl-6.0.3_fapi-0.84.0

### Modpack info

Sodium Plus 2.2.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I don't know how else to describe this issue. I found out about the narrator feature in this mod which is great when you use the "Press" mode but on "Toggle" it will cause a stutter each time you look at a new object. I have turned the vanilla narrator on and off to no difference. In attached video I press N to turn the feature on and off. Frame rate looks the same as on 200MB recording but can't put that on github.
[2023-07-18_tiny.webm](https://github.com/Snownee/Jade/assets/65094027/ba501b6a-5858-428b-8ad1-a7b036059079)

**Comment by Snownee** [comment]
might be related: [MC-263969](https://bugs.mojang.com/browse/MC-263969)

**Comment by catherinedoyel** [comment]
As soon as I see 11.3.0 for fabric on modrinth I will download and try. Thanks a lot :)
