### ISSUE TITLE
Suspicious blocks labeled as their normal variants

### ISSUE THREAD

**Issue by milkev** [Snownee/Jade#277]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.3.0

### Modloader version

Loader0.14.21, api 0.85.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When you look at a suspicious block (the new archeology variants of gravel & a few other blocks) jade just says its the regular block.

**Comment by Snownee** [comment]
Duplicate of #250

**Comment by milkev** [comment]
strange, it didnt show up when i searched the github, my bad.

**Comment by bernzrdo** [comment]
@milkev GitHub automatically filters closed issues.

**Comment by milkev** [comment]
> @milkev GitHub automatically filters closed issues.

yeah, i searched closed issues too, maybe i misspelled suspicious. oh well. this is why we have 'mark as duplicate'
