### ISSUE TITLE
[Feature Request] Increased customizability of overlay anchor on the screen

### ISSUE THREAD

**Issue by Abicce** [Snownee/Jade#279]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.7.3

### Modloader version

Fabric 0.14.21, Fabric API 0.75

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Currently, this version of the mod (latest version available for Fabric 1.19.2) only allows users to anchor the overlay to the top of the screen. However, it interferes with other HUD overlays from various mods. It might be beneficial to have more customizability of where the overlay can be anchored to so, like perhaps the right-middle of the screen, we can have it just where we want it. I'd greatly appreciate it if you'd consider this! :)

**Comment by Snownee** [comment]
![image](https://github.com/Snownee/Jade/assets/16059084/87a553b5-2657-40b1-973c-8781b70332fa)

Do you mean this?

**Comment by Abicce** [comment]
> ![image](https://user-images.githubusercontent.com/16059084/255533220-87a553b5-2657-40b1-973c-8781b70332fa.png)
> 
> Do you mean this?

hi, thanks for checking this issue out! Yes, I did mean the sliders shown in the image, but on my end, at vertical anchor 0, the overlay is still anchored to the top of the screen.
![2023-07-24_16 46 13](https://github.com/Snownee/Jade/assets/131329994/9ba25729-9822-4f2c-8f98-06fab9d4e87a)

Increasing the vertical anchor pushes the overlay off screen.
![2023-07-24_16 46 31](https://github.com/Snownee/Jade/assets/131329994/f3c9f9fc-1941-46de-a136-b0ea8ccc1833)
![2023-07-24_16 46 39](https://github.com/Snownee/Jade/assets/131329994/319903ae-b3d8-47df-bff2-e396f00a37f1)

Additionally, horizontal anchor values never reach the edge of the screen for me. 
![2023-07-24_16 46 21](https://github.com/Snownee/Jade/assets/131329994/a0072469-f5e2-42f2-a07a-f69ad2e525f5)

**Comment by Snownee** [comment]
do you see the vertical ratio?

**Comment by Abicce** [comment]
> do you see the vertical ratio?

Indeed I do! Apologies for wasting your time, I thought that would alter the dimensions of the overlay so I didn’t wanna mess with it. Thank you so much! I’ll close the issue now
