### ISSUE TITLE
Crash using 1.18.2 Epic Knights Pavise shield being placed as a Block

### ISSUE THREAD

**Issue by Dolphos** [Snownee/Jade#285]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.2.6

### Modloader version

Forge: 40.2.0

### Modpack info

private modpack

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://bytebin.lucko.me/QLqa4xY16V

### Issue description

I was testing my modpack and placed the Pavise Shield of Epic Knights mod onto the ground. Everything worked as intended at first, but I placed another one and then the game crashed. Since I'm using the Not Enough Crashes mod, it stated that Jade might be the issue, which leads me to post this.
The attachment is the same crashlog again.
[crash-2023-08-05_20.46.11-client.txt](https://github.com/Snownee/Jade/files/12267968/crash-2023-08-05_20.46.11-client.txt)
I hope, there is something to be figured out.
Greetings, Dolphos.

**Comment by Snownee** [comment]
looks like they have fixed it
