### ISSUE TITLE
Jade is lagging my game?

### ISSUE THREAD

**Issue by MenacingPerson** [Snownee/Jade#287]
### Mod loader

Fabric

### Minecraft version

1.19.4

### Mod version

10.4.0

### Modloader version

Fabric 0.14.21

### Modpack info

(Custom)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

To preface this:

I play on a minecraft server called "Wynncraft". It's really cool, but it's not relevant here. I only thought to mention it because it might be relevant.

I get really random lag spikes that go on for a solid minute and are really annoying, so I profiled my client by following https://spark.lucko.me/docs/guides/Finding-lag-spikes
and it turns out that somehow Jade is causing lag.

Look at this spark profile (client):

https://spark.lucko.me/5iRsMfM8rE

It's profiled with ticks that take >100ms, during one of those lag spikes.

https://spark.lucko.me/h5kR7DkhIV

Here is a normal profile with no custom options where a lag spike did not occur, and jade is only taking up 1% compared to the 28% in the previous one.

![image](https://github.com/Snownee/Jade/assets/59611020/1421b4c3-7016-465d-84ca-86ccc704937d)

All it seems to be doing is converting something to JSON. I wonder how that's causing lag. Is it writing to a file or something?

Or is maybe Jade showing up falsely because it's trying to write to my drive or something and it's getting bottlenecked?

**Comment by Snownee** [comment]
Can you tell me the file size of `config/jade/usernamecache.json`?

**Comment by MenacingPerson** [comment]
it says 4MiB

**Comment by MenacingPerson** [comment]
It's filled with crap like this btw
![image](https://github.com/Snownee/Jade/assets/59611020/3d65afe4-b9e2-4ceb-b3b3-17a828e6cd6a)

Because of fake players generated by server

**Comment by Snownee** [comment]
Fixed in 1.20+ but I don't have time to backport it to 1.19.4 in the next few weeks

**Comment by MenacingPerson** [comment]
Thank you!
