### ISSUE TITLE
Add support for fabric permission API

### ISSUE THREAD

**Issue by LazyDope** [Snownee/Jade#290]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.4.3

### Modloader version

Fabric: Loader 0.14.21 + API 0.87.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/darkrpg

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I am trying to setup a server that uses fabric's permission API instead of vanilla permissions, but it seems that there's no way to provide the permission to use the command block hover info without giving operator, even if the player has the ability to view command blocks from other methods.

Any help with this would be appreciated.

**Comment by Snownee** [comment]
What kind of support do you want? I don't think it is the Fabric permissions API itself that provides the ability to use the command block

**Comment by LazyDope** [comment]
I was thinking to either just add your own node or add support for the same syntax that [DrexHD's Vanilla Permissions](https://github.com/DrexHD/VanillaPermissions) uses, as that is what I'm using, which would be the `minecraft.operator_block.command_block.view`

**Comment by Snownee** [comment]
I am not too interested in adding integration for this mod. Perhaps you could ask the author of DrexHD's Vanilla Permissions to do it, but it seems that the project is not maintained very actively.

**Comment by LazyDope** [comment]
What about adding your own permission node then, one that gives access to viewing command blocks' command with Jade without having OP level 2.

**Comment by Snownee** [comment]
I can't arbitrarily provide support for third-party mods in Jade. Like, I don't want to port or compile the mod for Minecraft snapshots

**Comment by LazyDope** [comment]
In that case, so I may look into doing it myself, what branch builds for 1.20.1?
