### ISSUE TITLE
Fabric API is not flagged as dependency.

### ISSUE THREAD

**Issue by WerLunar** [Snownee/Jade#291]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.5.1

### Modloader version

0.14.21

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Fabric API is required for Jade, but it's not flagged as dependency. The game will crash without Fabric API if Jade presents.
Same thing happens with Quilt and Quilted Fabric API and Quilt Standard Libraries.

**Comment by Snownee** [comment]
This is intended because Fabric and Quilt share the same jar file. You should choose the correct one yourself
