### ISSUE TITLE
JEI Tooltips

### ISSUE THREAD

**Issue by bobo6** [Snownee/Jade#292]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

next one

### Modloader version

Forge

### Modpack info

None

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hi, 

thank you for your time. You made a really god mod. 

Is there a way to add a function for tooltips on JEI to have the same apperance like Jade Block tip?

would be happy if there is a way. If it is not already there, is it possible to install something like this?

Best Regards
Bobo

**Comment by Snownee** [comment]
Hi, I don't think this should be a part of Jade. You should use mods like Legendary Tooltips instead.
