### ISSUE TITLE
Mod Name duplicated in 1.19.2

### ISSUE THREAD

**Issue by ekerseyc** [Snownee/Jade#294]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.0

### Modloader version

43.2.21

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I am having the mod name in tooltips duplicate. Thank you for your hard work!

Mods used:
Jade-1.19.1-forge-8.9.0
jei-1.19.2-forge-11.6.0.1018

![image](https://github.com/Snownee/Jade/assets/98485122/f4fa3078-c488-4dd2-b5de-2d72d344a2c8)

**Comment by qznfbnj** [comment]
Do you have EMI installed?

**Comment by PersuGames** [comment]
Also happens on  1.20.1
A fix I found:
In Jade mod config "Item Mod Name" should be disabled manually.
Devs can add compat by disabling it automatically when jei is detected.
