### ISSUE TITLE
Key binds is acting weird

### ISSUE THREAD

**Issue by AlisonHuang777** [Snownee/Jade#296]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.4.3

### Modloader version

Forge 47.1.46

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I set the key bind for "Show Overlay" to [I], "Open Config" to [Shift + I]. But when I pressed [I] only, "Open Config" is triggered.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by AlisonHuang777** [comment]
The bug solved itself miraculously recently. Consider that happening, the bug itself is maybe just a rare occurrence of something malfunctions.
By the way, since it's not the first time that I encounter bugs that cannot be reproduced by devs, I want to ask that what could be a potential reason for a bug to occur, besides the common factors like Forge version, mod version, optimization mods... etc.? (For example, can inappropriate Java version be a cause for bugs to occur?)

**Comment by Snownee** [comment]
Mostly because of incompatible mods
