### ISSUE TITLE
Reach incompatible with axiom mod infinite reach

### ISSUE THREAD

**Issue by freerig** [Snownee/Jade#297]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.5.1

### Modloader version

Fabric 0.14.22, API v0.87.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

The tooltip isn't shown when I use the Infinite Reach module of the [Axiom](https://axiom.moulberry.com/) mod
I say that because it works however with pehkui (tooltip shown when `/scale set pehkui:reach 10`)
I don't have Pehkui installed, just Axiom, Jade and some others.

**Comment by Snownee** [comment]
Sorry, I am not interested in adding integration to the mod you mentioned.
