### ISSUE TITLE
[1.20.x] Break progress bar too dark too see (Need to go back to being white)

### ISSUE THREAD

**Issue by ffuentesm** [Snownee/Jade#298]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.5.1

### Modloader version

forge 47.1.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

The breaking progress bar is no longer white, which causes it to blend with the window. 
![image](https://github.com/Snownee/Jade/assets/44974827/d0da4bc5-5083-4037-b9e4-fc38eeaed2cc)

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by ffuentesm** [comment]
Strange, I tested this on a Vanilla world with just Jade and Jade Ad-ons installed, and the white progress break bar is black, not white. Could you add a setting that allows the user to change the bar color of the UI?
![image](https://github.com/Snownee/Jade/assets/44974827/63942471-0b94-4a7c-9724-53869ac0177e)

**Comment by Snownee** [comment]
![](https://media.discordapp.net/attachments/742802494438244372/1148886002937630720/image.png?width=1083&height=581)
![](https://media.discordapp.net/attachments/742802494438244372/1148886086572060692/image.png?width=1083&height=581)

**Comment by ffuentesm** [comment]
I think I found the problem, is something in the Vanilla Tweaks Resource pack, but I am not sure which asset is causing the problem.
Here is the pack I am using.
[VanillaTweaks_r1.20.zip](https://github.com/Snownee/Jade/files/12566831/VanillaTweaks_r1.20.zip)
