### ISSUE TITLE
Buildscript Publishing Tokens Missing Guard Clauses

### ISSUE THREAD

**Issue by ChloeDawn** [Snownee/Jade#299]
### Issue description

The following lines in the buildscript do not have guard clauses, resulting in a build error for external contributors.

https://github.com/Snownee/Jade/blob/fe13b0f0d7cfa0d83c58db72cbf67189e138007b/build.gradle#L157
https://github.com/Snownee/Jade/blob/fe13b0f0d7cfa0d83c58db72cbf67189e138007b/build.gradle#L167

**Comment by ChloeDawn** [comment]
The proxy arguments here also cause errors.
https://github.com/Snownee/Jade/blob/fe13b0f0d7cfa0d83c58db72cbf67189e138007b/gradle.properties#L1

**Comment by Snownee** [comment]
Hi, I am not familiar with Gradle. So if someone can send me a PR, I will accept it
