### ISSUE TITLE
[Feature Request] Display whether a block must be harvested with Silk Touch

### ISSUE THREAD

**Issue by DalekCraft2** [Snownee/Jade#30]
Pretty much explained in the title. Perhaps it could be written out, or perhaps the icon for the harvest tool could be different for those blocks.

**Comment by Snownee** [comment]
The data to determine whether the block can be silk touched is only stored on server-side. I don't think it is worth to sync data for every single block

**Comment by DalekCraft2** [comment]
But blocks like glass are always only obtainable with silk touch, correct? And the mod already knows which blocks require which tools, and can tell what the block is, so it would make sense for it to be able to determine whether the block must be silked.

**Comment by Snownee** [comment]
no, you can tweak it by loot table

**Comment by DalekCraft2** [comment]
Oh. I did not know that.
