### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sachitheavali** [Snownee/Jade#306]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.6.0

### Modloader version

Fabric Loader: 0.14.22 Fabric API: 0.88.0+1.20.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/tYipsEJ3

### Issue description

When I've opened the inventory, after moving the mouse around for a while it freezes then crashes

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue
