### ISSUE TITLE
Issue with Ht's Treechop mod

### ISSUE THREAD

**Issue by LOTAIM123** [Snownee/Jade#307]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.0

### Modloader version

Forge: 43.2.23

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

So in HTs Treechop mod when looking at full log it shows ok but in any other stages (when choped) it says error its been since one of the updates.

**Comment by Snownee** [comment]
It has to be fixed on their end: https://github.com/hammertater/treechop/issues/221
