### ISSUE TITLE
Very wierd display on ME Interface and Extended ME Interface. Mekanism issue.

### ISSUE THREAD

**Issue by ballsconnoisseur** [Snownee/Jade#311]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.6.1

### Modloader version

47.1.3

### Modpack info

ATM9

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

doesnt matter

### Issue description

So new mod has been added to ATM9, mekanism this comes with mekanism addon to JADE. This then causes this visibility issue. If i disable Mekanism Plugin in JADE, it will no longer show this liquid/gas/idk containers. https://imgur.com/a/0rk2TFB

**Comment by Snownee** [comment]
Please report this to the Mekanism devs
