### ISSUE TITLE
Cannot invoke "net.minecraft.world.item.Tier.getTag()" because the return value of "java.util.List.get(int)" is null

### ISSUE THREAD

**Issue by Trapsaru** [Snownee/Jade#312]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.6.1

### Modloader version

47.2.1

### Modpack info

https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

<Error from jade mod, plz report> Its just when I look at blocks, that I get that popup.
![image_2023-10-06_210107707](https://github.com/Snownee/Jade/assets/147217589/b9a22699-9cff-46dc-918b-9559f2d5d64c)

**Comment by Snownee** [comment]
Please provide your `latest.log`.

**Comment by Trapsaru** [comment]
[latest.log](https://github.com/Snownee/Jade/files/12911015/latest.log)

**Comment by Snownee** [comment]
And your `JadeErrorOutput.txt`, please

**Comment by Trapsaru** [comment]
[JadeErrorOutput.txt](https://github.com/Snownee/Jade/files/12911054/JadeErrorOutput.txt)

**Comment by Snownee** [comment]
it looks like a bug in Forge that occurs when the client mods do not match the server

**Comment by Snownee** [comment]
I assume it will not happen in singleplayer?

**Comment by Trapsaru** [comment]
Nope, doesn't happen in singleplayer.

**Comment by Snownee** [comment]
blame Forge developers
