### ISSUE TITLE
Jade not showing while looking at a block [fixed]

### ISSUE THREAD

**Issue by InterPlay02** [Snownee/Jade#314]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.6.1

### Modloader version

47.1.3

### Modpack info

All the mods 9

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Well...

After I've set the hotkey to Left Ctrl, hold and no, and it stopped showing me the window on the top of the screen.
Then, it wasn't showing even with any other hotkey I tried to set.
I literally didn't changed anything on the modpack. Just downloaded and started to play.

I've changed only these on the mod itself:
Toggle overlay = from "Number 1" to "Left Ctrl".
The action = from "toggle" to "hold".
Item mod names = from "yes" to "no".

And then, even if I tried to set everything back to default, it wouldn't work yet.
The only solution I found was to delete the config folder and re-enter my world map.
Now it works as intended.

I only thought you should know about this.
Here is the old config folder that I needed to delete for it to work:
[jade.zip](https://github.com/Snownee/Jade/files/12840861/jade.zip)

**Comment by Snownee** [comment]
Please make sure the "show overlay" keybind does not conflict with other keys

**Comment by InterPlay02** [comment]
It is not. I've removed every single other keybinds just to make sure, but didn't worked. The only thing that worked was to delete the folder and re-enter the world.

But yesterday I've noticed something else:
I tried to remove the icon hint that appears on the side of the name of the block we are looking at. (The one that show us which item can be used to harvest or break that block) and then... guess what... the window stopped showing on the top again. But this time it came back as soon I reset the setting I've changed.

I don't know what is causing this behavior... but maybe you can try it out for yourself. Just download atm9 and try these changes.

**Comment by Snownee** [comment]
Forge's keybinding system is bugged
