### ISSUE TITLE
Cannot read field "f_82470_" because "translate" is null

### ISSUE THREAD

**Issue by scottycool64** [Snownee/Jade#316]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.3.0

### Modloader version

40.2.10

### Modpack info

(none)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/525819185712988180/1162915078312571020/latest.log?ex=653dac10&is=652b3710&hm=78abce68a0df5b336554bf03dfd8bf74c30ad1823d2bc354528da67ed3235611&&raw=false

### Issue description

https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/525819185712988180/1162915297536249916/crash-2023-10-14_20.47.51-client.txt?ex=653dac44&is=652b3744&hm=c0a8e081188b9a7e78f899135c5ef2c4c801ef2bfd852d0c28a628b1fc32e249&&raw=false - Minecraft Crash Log
Whenever I look at a Mekanism bin my game immediately crashes. My world is now basically bricked because as soon as I spawn in I'm already looking at it again.

**Comment by Snownee** [comment]
Hi. Please use this instead and try again: [mod.zip](https://github.com/Snownee/Jade/files/12908515/mod.zip)

**Comment by scottycool64** [comment]
Yes, this fixed it. Now the Mekanism bin says \<ERROR> in the thing, though, but that's fine. Thank you!
Edit, actually most of my containers say \<ERROR> at the top of the Jade window

**Comment by Snownee** [comment]
Please do not use Saturn for the time being. It is causing the crash.
