### ISSUE TITLE
Add support for SecretRoomsMod

### ISSUE THREAD

**Issue by EnderMelody** [Snownee/Jade#32]
* Minecraft Version: 1.16.5
 * Mod Version: 1.16.4-2.5.1
Currently, hidden blocks such as the 'Torch lever' are displayed as their real name. 
![2021-03-13_11 24 39](https://user-images.githubusercontent.com/12649140/111036728-b52ccf80-83ee-11eb-85e9-adcbd83a4ebf.png)
They should instead be using the block the are mimicking's name instead.

**Comment by embeddedt** [comment]
Secret Rooms for 1.16+ didn't have plugins to show the fake block's information. I implemented this upstream, it's just waiting on a release: https://github.com/Wyn-Price/SecretRooms/pull/71

I don't think it's an issue with any particular Hwyla implementation, so this can probably be closed now?

**Comment by Snownee** [comment]
@embeddedt no, the API you are using is added by WTHIT. there is even no IBlockComponentProvider in Hwyla

**Comment by Snownee** [comment]
I will just address this issue to Snownee/JadeAddons#2

**Comment by Snownee** [comment]
@embeddedt and one more thing: I don't think your PR will work for the Torch Lever

**Comment by embeddedt** [comment]
Hmm.. it's my understanding that WTHIT [renamed the original interface from Hwyla](https://github.com/badasintended/wthit/issues/110), making it impossible to support both mods simultaneously.
