### ISSUE TITLE
[Plugin] Hidding Container Items in the Tooltip

### ISSUE THREAD

**Issue by Corgam** [Snownee/Jade#322]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.6.3

### Modloader version

Forge 47.1.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hi, I am currently implementing the Jade compatibility in my mod,
and I was wondering if it is possible to hide the container's contents inside the Tooltip. I don't want them to render twice :)

![Untitled](https://github.com/Snownee/Jade/assets/9498156/0c4151cf-9de8-4783-a64e-98022cd8189f)

**Comment by Snownee** [comment]
You can implement an `IServerExtensionProvider`:

```java
public class HideItemsProvider implements IServerExtensionProvider<HopperBlockEntity, ItemStack> {

	public static final ResourceLocation UID = new ResourceLocation("debug:hide_items");

	@Override
	public ResourceLocation getUid() {
		return UID;
	}

	@Override
	@Nullable
	public List<ViewGroup<ItemStack>> getGroups(ServerPlayer player, ServerLevel world, HopperBlockEntity target, boolean showDetails) {
		return List.of();
	}

}
```

and register it:

```java
@Override
public void register(IWailaCommonRegistration registration) {
	registration.registerItemStorage(new HideItemsProvider(), HopperBlockEntity.class);
}
```

**Comment by Corgam** [comment]
Thank you, works exactly as I wanted! :)
