### ISSUE TITLE
Doesn't show correct block icon

### ISSUE THREAD

**Issue by 909oce** [Snownee/Jade#325]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.6.2

### Modloader version

Fabric Loader 0.14.23 + API 0.90.4+1.20.1

### Modpack info

https://modrinth.com/modpack/909-pack/

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://github.com/Snownee/Jade/assets/21692038/98606aaf-1dd5-4dbd-b5e8-80c8e9e49a77)

Some blocks don't show the correct icon, like here the hopper is a pickaxe, but if I look at glass for example, it'll show correctly.

**Comment by Snownee** [comment]
it seems you are using a mod that modifies the pick result
