### ISSUE TITLE
Incorrect item amount displayed for Create's Vaults

### ISSUE THREAD

**Issue by MaximilienMoritz** [Snownee/Jade#328]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.1

### Modloader version

Forge 43.3.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/3P3ifpdS

### Issue description

When looking at a vault, Jade is not able to display the correct amount of items inside after Create's config for Vault sizes has been changed. This can be verified by hooking up a display link to a Smart Observer and setting it to "show item count".

Jade seems to still consider the vaults to be in their original config (ie. 20 stacks/vault block), and thus the tooltip shows incorrect values.

**Comment by Snownee** [comment]
Jade 1.20+ has added support for large item storage. Currently, there are no plans to backport it to 1.19.2.

**Comment by mikkolukas** [comment]
@Snownee Could Jade be amended, so it shows a different text or no text at all?

Maybe one of these alternatives instead:
* Show the text `minimum 10,3k [item name]`
* Show the text:
  * Line 1: `10,3k [item name]`
  * Bottom line: `(not all items shown)`
* or just `not supported`.

... or something else

Rather have missing or incomplete information than wrong information. It is very confusing when Jade lies about the amount in the container.
