### ISSUE TITLE
Changing the display scale causes the hud to offset weirdly

### ISSUE THREAD

**Issue by EnderMelody** [Snownee/Jade#33]
* Minecraft Version: 1.16.5
 * Mod Version: 1.16.4-2.5.1
![2021-03-13_11 28 57](https://user-images.githubusercontent.com/12649140/111036868-7ba89400-83ef-11eb-8ab0-0270cdd0d319.png)
![2021-03-13_11 29 03](https://user-images.githubusercontent.com/12649140/111036869-7d725780-83ef-11eb-976f-58fa6d996f09.png)

**Comment by Snownee** [comment]
This feature is unavailable in 1.16 and will be supported in 1.17
