### ISSUE TITLE
Are Redirects supported?

### ISSUE THREAD

**Issue by Speiger** [Snownee/Jade#331]
### Mod loader

Forge

### Minecraft version

1.19.2 or newer

### Mod version

Any

### Modloader version

Any

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

o/
Another question.

Does jade support Redirects in any form?
Like if i look at a stone block, but we have it part of a multiblock, can we redirect the info gatherers to said multiblock owner?
That is one feature I have implemented into one probe, but the difference there is that it's server side rendered so not sure how to do it with jade.

And if it isn't present do you consider adding that?

**Comment by Snownee** [comment]
https://jademc.readthedocs.io/en/latest/plugins20/overrides/

**Comment by Speiger** [comment]
@Snownee does that include ServerData Fetching?

**Comment by Snownee** [comment]
yes
