### ISSUE TITLE
[Suggestion] Hide Supplementaries presents content or trapped present name

### ISSUE THREAD

**Issue by nimbXnumb** [Snownee/Jade#335]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.6.2

### Modloader version

Fabric 0.14.24

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I suggest to hide Supplementaries present's content as I haven't find how to do it. If you can't that's ok. Then is it possible to switch trapped present name to normal present (like trapped chest and infested blocks). Would be great addition for upcoming New Year :)

**Comment by Snownee** [comment]
will be added from the Supplementaries side recently
