### ISSUE TITLE
Suggestion: add a way to get block entity information for more than one tall blocks

### ISSUE THREAD

**Issue by IchHabeHunger54** [Snownee/Jade#337]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.1

### Modloader version

Forge 43.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

In my mod, there is a furnace-like block (the Obelisk) that is three blocks tall, but has only one block entity that is attached to the bottom block state. This results in the block entity information only showing when looking at the bottom block.

A video that portrays the issue quite well is attached.

https://github.com/Snownee/Jade/assets/52419336/f13c278b-e364-43a0-9523-1f0080ef962c

I would kindly ask for a solution to this problem.

**Comment by Snownee** [comment]
Through your activity on Github, it seems you have found a solution
