### ISSUE TITLE
[Suggestion] Allow customize fake blocks like powder snows

### ISSUE THREAD

**Issue by No3371** [Snownee/Jade#340]
### Mod loader

Fabric

### Minecraft version

-

### Mod version

-

### Modloader version

-

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It could be an useful addition for mod pack developer.
https://sourcegraph.com/github.com/Snownee/Jade@866dde8dd070ae7f7f2881b2489783cd3b761da5/-/blob/src/main/java/snownee/jade/JadeClient.java?L196=

**Comment by Snownee** [comment]
Out of curiosity, I wonder what modpack project you are working on?

**Comment by No3371** [comment]
To be honest I just make private packs for fun and friends every now and then, the packs would usually contain several hundred mods and not all of them got finished, depends on when my attention shift to other games.

Of course, these big packs usually becomes time sinks and takes me a lot of time to provide hardcore experience which I prefer, and sometimes I get bothered by the fact with these lovely info HUD mods I can't fake mimic mobs into chests, or quick sand blocks to sand blocks.

**Comment by Snownee** [comment]
In my opinion, this is supposed to be added by the original mod. But well, we will see if it is possible to add a customizable way.

**Comment by No3371** [comment]
Is there a way for mods to tell Jade, or maybe all general HUD mods to show a different block? If so, I think that's a valid point.

**Comment by Snownee** [comment]
for Jade, sure yeah

**Comment by No3371** [comment]
Cool, though it requires modders to actively support Jade, that's indeed enough done on Jade's side.
