### ISSUE TITLE
[Suggestion] Config option to disable the "hidden" blocks such as Infested Stone in Survival Mode

### ISSUE THREAD

**Issue by Nataly171** [Snownee/Jade#341]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Mod version

11.6.3

### Modloader version

47.1.81

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When looking at a block such as Infested Stone in Survival Mode, the overlay will display "Stone". The same applies to other blocks, such as Powder Snow displaying as Snow, and Suspicious Sand displaying as Sand. Switching to Creative Mode displays the correct block information. I believe the user should have control over this behavior and allow seeing correct block information in Survival Mode.

**Comment by spinodal23** [comment]
Camouflage option unable in 1.20.2 mod?

**Comment by lexi-the-cute** [comment]
Could we backport this feature to 1.20.1+? I'm currently trying to remap the latest version of the mod to 1.20.1 from the 1.20.3 branch to no avail
