### ISSUE TITLE
Waterlogged light blocks show up as light when swimming

### ISSUE THREAD

**Issue by steve-the-player** [Snownee/Jade#342]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.6.2

### Modloader version

Loader v0.14.25 API v1.91.0+1.20.1

### Modpack info

https://modrinth.com/modpack/adventurous

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

Note: This can be done purely in vanilla+Jade mod. 

I'm running a set of custom repeating commands 
`/execute as @e[type=player] at @e[type=player] run fill ~-3 ~-3 ~-3 ~3 ~3 ~3 light[level=1,waterlogged=true] replace water[level=0]` and `/execute as @e[type=player] at @e[type=player] run fill ~-3 ~-1 ~-3 ~3 ~2 ~3 minecraft:light[level=1,waterlogged=false] replace air`, which surrounds all players with light blocks, light level 1. There's also a version that only does it when the player has the "glowing" effect, but I'm including the base command since it doesn't really matter. Anyways, the light blocks do not show up in the air around you on the Jade display, but the moment you dive underwater, the display is constantly there. Regular water doesn't do this when you're underwater targeting water, regular air doesn't do this, regular lights don't do this, but waterlogged lights do. It's a little weird.

**Comment by Snownee** [comment]
How will you remove the light blocks?

**Comment by Snownee** [comment]
I can't reproduce it. Can you record a video?

**Comment by steve-the-player** [comment]
sure thing, let me fire up OBS rq

**Comment by steve-the-player** [comment]
https://www.youtube.com/watch?v=ofmkzw8xykM Github wouldn't let me directly upload the file

**Comment by steve-the-player** [comment]
> How will you remove the light blocks?

once everything is set up, only players with the glowing effect will leave trails of the light blocks, but players with the darkness effect remove them (That's the other two command blocks in the video). Placing blocks also deletes them, I suppose.

**Comment by Snownee** [comment]
Reproduced now. Thanks for your help!
