### ISSUE TITLE
Tortoise Shell from Sully's mod shows an error

### ISSUE THREAD

**Issue by Carmenboy1** [Snownee/Jade#345]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.6.4

### Modloader version

47.2.6

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/4N4z6FRZ

### Issue description

if you place down a tortoise shell from sullys mod and look at it the error message appears 
![2023-12-21_11 01 01](https://github.com/Snownee/Jade/assets/76805533/d9ddc61f-b634-4ed1-bd56-7f4f06e9aafe)

here are the mods involved: 
![image](https://github.com/Snownee/Jade/assets/76805533/4c54e8d2-867f-4f32-8532-b55d038acef5)

**Comment by Snownee** [comment]
I can't reproduce it. And your latest.log shows you are using Forge 47.2.17, not 47.2.6. Can you find the JadeErrorOutput.txt in the logs folder?

**Comment by Carmenboy1** [comment]
yes https://pastebin.com/bDfs4JRp (also i got my forge versions mixed up, whoops!)

**Comment by Snownee** [comment]
Addressed to https://github.com/Uraneptus/Sullys-Mod/issues/81
