### ISSUE TITLE
Silent Gear Crash

### ISSUE THREAD

**Issue by loopel** [Snownee/Jade#347]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.7.0

### Modloader version

Forge: 47.2.16

### Modpack info

I'm using my own modpack and I use a ton of mods so I'll just upload my mod list: https://pastebin.com/sF9Mp4xL

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

JadeErrorOutput.txt: https://pastebin.com/3sHUJa0D

### Issue description

I've had this issue for a while and its kind of bugging me because I really want to use silent gear and it crashes whenever I hover over the blueprint item and some other certain key items in the mod. I can just use things like create auto crafting to get past the issue but some items that have crafting slots not next to it (like the bow blueprint) make this kind of an issue.

**Comment by loopel** [comment]
couldn't fit the log into a paste bin so heres a gist: https://gist.github.com/loopel/31e27c98d217791c3ff117b9f2c62201

**Comment by Snownee** [comment]
did it crash the game?

**Comment by loopel** [comment]
yes

**Comment by loopel** [comment]
also I'm not sure if this is important, but if I craft the blueprint item via create auto crafter, the jade popup says error with jade, report to issue tracker or something like that

**Comment by Snownee** [comment]
have you tried to remove Jade?

**Comment by loopel** [comment]
no but I can try that, but if the problem is jade is there another mod like jade or a fix for this?

**Comment by Snownee** [comment]
Not our problem
