### ISSUE TITLE
[Suggestion] Entities in "Love Mode" indicator

### ISSUE THREAD

**Issue by Nataly171** [Snownee/Jade#349]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.7.0

### Modloader version

NeoForge 47.1.81

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Just something I think would be nice, would be to be able to see when an animal is in love mode by looking at it with Jade

**Comment by Snownee** [comment]
I don't think this is necessary
