### ISSUE TITLE
Error with Valhelsia Structures

### ISSUE THREAD

**Issue by cartooneric84** [Snownee/Jade#350]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.7.1

### Modloader version

Forge 47.2.19

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2023-12-29_12 02 59](https://github.com/Snownee/Jade/assets/86167550/4994c544-1189-4e8f-a3fa-b8bedec5e4db)

The error said to report to the mods of Jade.  So here I am.

**Comment by cartooneric84** [comment]
Also if I dared to touch that the game will crash.

**Comment by Snownee** [comment]
Hi. Can you find the JadeErrorOutput.txt in the logs folder?

**Comment by cartooneric84** [comment]
> Hi. Can you find the JadeErrorOutput.txt in the logs folder?

[JadeErrorOutput.txt](https://github.com/Snownee/Jade/files/13795794/JadeErrorOutput.txt)

You mean this one?

**Comment by Snownee** [comment]
This may help you: https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/188
