### ISSUE TITLE
Display Mode: Hold does not work

### ISSUE THREAD

**Issue by 2iqPlays** [Snownee/Jade#352]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.7.1

### Modloader version

forge 47.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

This may just be a problem on my end but when I try to set my display mode from "toggle" to "hold" and hold the designated key nothing happens. I'm not sure why, there are no hotkey overlaps. Any help would be appreciated.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue
