### ISSUE TITLE
chat spammed with project mmo

### ISSUE THREAD

**Issue by acxjet** [Snownee/Jade#356]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.7.1

### Modloader version

Forge-47.2.19

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/5zydPm70

### Issue description

There is a bug in the interaction between Jade and Project MMO. I have already made a bug report on their end which you can see [here](https://github.com/Caltinor/Project-MMO-2.0/issues/449). Their maintainer has requested asking you if, for checking if blocks can be broken, you simulate a block break event. 
If this is the case, it means that anyone using both Jade and Project MMO gets their chat log spammed with Project MMO's "You are not skilled enough to "

Maybe you can work together with Project MMO's maintainer to come up with a solution?

**Comment by Snownee** [comment]
Discussed on their side
