### ISSUE TITLE
Showing the wrong icon

### ISSUE THREAD

**Issue by szunakabeats** [Snownee/Jade#357]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.7.0

### Modloader version

Fabric 0.15.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

when i switch betweeen my tools in my hotbar, it shows the last tool used as the block icon which im lookin at.
![image](https://github.com/Snownee/Jade/assets/88375166/d63888d0-9398-4c4b-8c19-938cad68b442)

but when i hold a block for example it shows the right info.
![image](https://github.com/Snownee/Jade/assets/88375166/f9d9e849-874a-4520-81d7-8f3d3f94c029)

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by szunakabeats** [comment]
hm i think it bugs with some mod i have installed then, i made a fresh instance with only jade installed and now the problem is gone

**Comment by szunakabeats** [comment]
is it possible for you to look over my pack ? it must be some optimization mod interfering with jade.
i could export my pack from curseforge for you. or if you need some logfiles i can attach them here.

thx for your time
