### ISSUE TITLE
Crash looking at fruit

### ISSUE THREAD

**Issue by Enterprise12nx01** [Snownee/Jade#358]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

1.16.4-2.8.3

### Modloader version

Forge 36.2.39

### Modpack info

https://www.curseforge.com/minecraft/modpacks/industrial-age-the-turning/files/5013114

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

i reported the issue here for Amber, but it also applied when i switched to Jade
it does not happen with Hwyla.
https://github.com/Hellish-Mods/Amber/issues/5
my latest version of the pack isnt running with Jade/Amber due to the crash.

**Comment by Snownee** [comment]
This is a bug in Dynamic Trees
