### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2350.method_10166()" because "side" is null

### ISSUE THREAD

**Issue by wzieciak** [Snownee/Jade#359]
### Mod loader

Quilt

### Minecraft version

1.20.1

### Mod version

11.7.00

### Modloader version

0.23.0 / QFAPI 7.2.2 and QSL 6.1.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/xYundy/ad028535e7b1fe1428a2b8ebd585f8c9

### Issue description

Hey! I got this error on dedicated server recently.
It's look like some problem with fluids, maybe with Create ones..

**Comment by Snownee** [comment]
@MarbleGateKeeper @IThundxr please fix it

**Comment by IThundxr** [comment]
Fixed in 1.2.12
