### ISSUE TITLE
TTS toast issue

### ISSUE THREAD

**Issue by Jimmy-sheep** [Snownee/Jade#363]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

13.2.1

### Modloader version

fabric-api-0.94.0+1.20.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When first time toggle tts feature, the toast `toast.jade.tts_hint` (top-right blue banner) will show, but after that, it won't show again anymore, even restart game. I'm not sure `toast.jade.toggle_hint` also have this problem or not.

(I found this issue when I translate lang file, so I use the string key to show what I mean)

**Comment by Snownee** [comment]
This is the intended behavior

**Comment by Jimmy-sheep** [comment]
> This is the intended behavior

Oh, ok
