### ISSUE TITLE
Crash with banner. Epic Knight + Jade

### ISSUE THREAD

**Issue by matteo335** [Snownee/Jade#367]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.3.1

### Modloader version

40.2.14

### Modpack info

https://legacy.curseforge.com/minecraft/modpacks/imperium

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/matteo335/649e80438bb7b072b491f65c242d8077

### Issue description

The client crash when rendering almost any banners (especially ominous banner) on a short distance.
it can be temporarily fixed by deleting the Epic Knights server/multiplayer-side configs.
I've tried to rebuild Epic Knights by removing/remaking anything that was conflicting/making the issue, but it seems difficult to fix it in the Epic Knights side.

I hope you can do something on your side/that this problem isn't too directly related to Epic Knight.

**Comment by Snownee** [comment]
not my fault
