### ISSUE TITLE
[Bug] Crash when TileEntity has an ItemHandler, but getStackInSlot is abstract

### ISSUE THREAD

**Issue by Lazialize** [Snownee/Jade#37]
* Forge Version: 36.1.0
 * Mod Version: 2.6.1

[crash-2021-03-20_18.53.54-server.txt](https://github.com/Snownee/Jade/files/6175268/crash-2021-03-20_18.53.54-server.txt)

The title says it all.
I don't know if I can say that this is a bug in this mod.
However, since there is a possibility that similar TileEntity exists in other mods, I think it would be a good idea to deal with it in this mod.

Sorry if my English is wrong.

**Comment by Snownee** [comment]
try updating Mana and Artifice. if crash still occurs, then reopen this issue
