### ISSUE TITLE
Crash when trying to break anything that requires a pickaxe with a pickaxe

### ISSUE THREAD

**Issue by minigamerking** [Snownee/Jade#370]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.2

### Modloader version

Forge 43.3.6

### Modpack info

https://www.curseforge.com/minecraft/modpacks/creattopia/files/5083586/changelog

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/minigamerking/61cb20d1afca097478bd5cd0c0b30276

### Issue description

I join the server and I see that I can't see what tools can break blocks. This is fine since I know what tools can and can't break blocks, but the weird thing is that whenever i try mining anything that requires a pickaxe with a pickaxe it crashes my game.
1. Get a pickaxe
2. Find something that requires a pickaxe to mine
3. Mine it and crash

**Comment by Snownee** [comment]
This is a Forge bug and has nothing with Jade. Please report on the Forge forum instead
