### ISSUE TITLE
mod name display can't disable

### ISSUE THREAD

**Issue by westernat** [Snownee/Jade#372]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.7.1

### Modloader version

Forge: 47.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I am tried to disable mod name display, but it doesn't works

**Comment by westernat** [comment]
wait, mod loader is forge, i chosen a worse one

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue
