### ISSUE TITLE
Can't see entity health on multiplayer server

### ISSUE THREAD

**Issue by Kryiip** [Snownee/Jade#373]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.7.1

### Modloader version

Forge 47.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I can't see entity health and I don't know why, I can't find how to change it in the server files. Is it possible ?

**Comment by Snownee** [comment]
Hello, do you know you can press [numpad 0] to open the Jade configs? Hope it helps you!

**Comment by Snownee** [comment]
make sure you have the same jade version on server
