### ISSUE TITLE
Showing time to breed/grow animals

### ISSUE THREAD

**Issue by Alethephobe** [Snownee/Jade#377]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

13.3.1

### Modloader version

Fabric: Loader 0.15.7 + API 0.96.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I would love to have a timer for breeding adults and growing kid animals!
I would like to know how much time is left till they grow or will be breedable again!

![image](https://github.com/Snownee/Jade/assets/38894389/df29bdfc-3a91-4ad6-a1ba-a3ee38a2aeeb)

**Comment by Snownee** [comment]
please install Jade on your server
