### ISSUE TITLE
Problem with a sword for mystical agriculture

### ISSUE THREAD

**Issue by idk-something95** [Snownee/Jade#380]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

MysticalAgriculture-1.20.1-7.0.9

### Modloader version

Forge - 47.2.20

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

to be honest I don't know if it really is jade's fault but is says to report it 
![image_2024-03-02_174205277](https://github.com/Snownee/Jade/assets/119735898/7ba2d4c8-8e86-4987-9c5a-86d33c425856)

nothing happens when I swing or hold this sword  but when I hover my mouse on it in my inventory my whole game crashes

https://pastebin.com/rTZrcqYz 
/\ this is the pastebin for the last crash from this sword

**Comment by Snownee** [comment]
Thank you for the report, it's not Jade's fault
