### ISSUE TITLE
Custom themes 

### ISSUE THREAD

**Issue by CrossVas** [Snownee/Jade#382]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Jade-1.19.1-forge-8.9.2

### Modloader version

Forge: 43.3.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Currently there is no direct way to add custom themes other than changing Jade's config files.
My suggestion/request is to add ability for plugins to add custom themes via api (or any) using `IWailaClientRegistration`, etc., which then could be accessed from the Jade's menu in game.

**Comment by Snownee** [comment]
already implemented on 1.20+
