### ISSUE TITLE
[Suggestion] Add a config option to change the info update rate

### ISSUE THREAD

**Issue by AlisonHuang777** [Snownee/Jade#386]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Mod version

11.6.3

### Modloader version

47.1.99

### Modpack info

Prominence II Classic v2.6.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Described in title.

**Comment by Snownee** [comment]
There are no plans or specific reasons to add this feature. This will increase the load on the server.
