### ISSUE TITLE
entities stopped showing up on Jade

### ISSUE THREAD

**Issue by MidnightsCrow** [Snownee/Jade#388]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.18.0

### Modloader version

Fabric: Loader 0.15.7, API: 0.92.0

### Modpack info

Jade Addons Mod

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

My entities randomly stopped showing up and they are enabled in jade settings.

**Comment by Snownee** [comment]
please make sure you have the same jade version as the server

**Comment by MidnightsCrow** [comment]
> please make sure you have the same jade version as the server
the server doesent have jade, it was working earlier on the server however, showing dropped item tooltips via jade. even tho the server is not modded, also, heads stopped showing up in jade too
it no longer says "Dream's player head" instead just showing the block behind it

**Comment by Snownee** [comment]
can you test this in a singleplayer world?

**Comment by MidnightsCrow** [comment]
> can you test this in a singleplayer world?

it works in singleplayer, it worked earlier on multiplayer tho.

**Comment by Snownee** [comment]
which means the server now has Jade
