### ISSUE TITLE
[Bug] Nether Chests

### ISSUE THREAD

**Issue by nco2k** [Snownee/Jade#389]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

13.3.1

### Modloader version

0.15.7

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

when you place a [nether chest](https://github.com/Kir-Antipov/nether-chest) on the ground and then look at it, it wont show its content. but when you log out and log back in, then the content will show.

**Comment by Snownee** [comment]
This should be fixed on their end. Their inventory is not available immediately after the block is placed, which conflicts with Jade's caching strategy
