### ISSUE TITLE
SecurityCraft Password Chests

### ISSUE THREAD

**Issue by CagyTrain** [Snownee/Jade#390]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.8.1

### Modloader version

43.3.9

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hey! I’m using Jade with SecurityCraft and whenever I look at a password locked chest, I can see the password no matter if it’s mine or not.
Is there a way to make it not appear?

**Comment by Snownee** [comment]
https://github.com/Geforce132/SecurityCraft/issues/369
