### ISSUE TITLE
Question: Anyway to show info if we've renamed something? (like storage containers)  (On Multiplayer servers)

### ISSUE THREAD

**Issue by Etrit1** [Snownee/Jade#392]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

13.3.1

### Modloader version

Fabric uh, latest version

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I know this wasn't possible with HYALIA etc but I'm hoping you've figured out a way to do it.

I like renaming my storage containers and it would be REALLY nice to see the name with Jade when I look at them. 

After all, the name IS in the NBT data

After testing it in Singleplayer: Jade DOES show the name in Single player but not on a server??

**Comment by Snownee** [comment]
you need to install Jade on the server

**Comment by Etrit1** [comment]
Ah, I was kinda afraid that was the answer.  I'm in not in charge of the server so sigh. Oh well.

Thanks for the response AND for keeping Jade current!  

I do love using it for Everything else.
