### ISSUE TITLE
[1.20.1] theme color options are gone

### ISSUE THREAD

**Issue by LTCatt** [Snownee/Jade#396]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.8.0

### Modloader version

Forge 47.2.23

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I am migrating from 1.16.5 to 1.20.1, but I wasn't able to find any theme color options in 1.20.1.
Were they removed?
![image](https://github.com/Snownee/Jade/assets/40348278/b4b0d27a-b346-4009-8bfd-cb58c9d829ad)

**Comment by Snownee** [comment]
They are now defined in resource packs. For the details please read the documentation
