### ISSUE TITLE
Jade doesn't show Panda (vanilla) info like personality

### ISSUE THREAD

**Issue by Sirfirelord1** [Snownee/Jade#397]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.7.1

### Modloader version

Forge: 47.2.0

### Modpack info

https://curseforge.com/minecraft/modpacks/pettys-cozycraft

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

No log

### Issue description

As stated in the title, Jade does not show tooltip info for pandas like personality and traits (see attached images, with WTHIT tooltip for comparison)
![WTHIT-panda](https://github.com/Snownee/Jade/assets/115722472/637a381d-aa84-4e1b-8ddf-0fecfb158782)
![Jade-panda](https://github.com/Snownee/Jade/assets/115722472/2bb5fdbf-f470-4178-8d03-658fb40f167d)

Full disclosure: Jade is a better tooltip mod than WTHIT in many other aspects (especially for my modpack, which has both Productive Bees and Resource Chickens, and Jade has integration for both while WTHIT does not)

https://github.com/Sirfirelord1/Petty-s-Cozycraft/issues/13

**Comment by Snownee** [comment]
Currently I don't plan to add this feature. If you really want this, you could ask someone to make an addon for you

**Comment by Snownee** [comment]
for those who want this feature, I've made a KubeJS plugin for it (1.21, not tested with 1.20). You need to unzip it to install it

[jade_panda_genes.zip](https://github.com/user-attachments/files/16732349/jade_panda_genes.zip)

**Comment by QingSu6** [comment]
> 对于那些需要此功能的人，我为它制作了一个 KubeJS 插件（1.21，未使用 1.20 进行测试）。您需要解压缩它才能安装
> 
> [jade_panda_genes.zip](https://github.com/user-attachments/files/16732349/jade_panda_genes.zip)

Unfortunately, KubeJS does not support Fabric and Forge above 1.20.2
