### ISSUE TITLE
Crash when trying to load on NeoForge 20.5.14-beta or newer

### ISSUE THREAD

**Issue by bl4ckscor3** [Snownee/Jade#398]
### Mod loader

NeoForge

### Minecraft version

1.20.5

### Mod version

14.0.2

### Modloader version

20.5.20-beta

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/bl4ckscor3/a4c9a15d622fb7e0842484591567a54e

### Issue description

Loading Jade using NeoForge 20.5.14-beta or newer fails, because NeoForge changed how tick events work. NeoForge 20.5.13-beta works fine.

**Comment by Snownee** [comment]
If there aren't too many demands, I'll wait for NeoForge to leave the beta stage before fixing it

**Comment by Minecraftschurli** [comment]
little info from a neoforge maintainer, beta in neoforge is what the breaking changes period before the first recommended version on forge was, this can take a while, we have a milestone to track the PRs that need to be merged before we will make a stable release https://github.com/neoforged/NeoForge/milestone/3
