### ISSUE TITLE
Storage Drawers support

### ISSUE THREAD

**Issue by mouse0270** [Snownee/Jade#4]
* Forge Version: 31.1.70
 * Mod Version: 1.0.1

Storage Draweres removed the support for Hwyla and I have seen a pull request for it on their thing for some time now, though it looks like the author is currently inactive. I get this might be out of the scope of your mod, but it would be really nice to see what is in a drawer and how much is being stored when lookin at a drawer in the world when using Hwyla.

I don't know anything about modding minecraft, so I figured I would ask someone who might now. lol

**Comment by Snownee** [comment]
Moved this issue to Snownee/JadeAddons#2
