### ISSUE TITLE
Jade 🔍 does not show up in the CurseForge app

### ISSUE THREAD

**Issue by EwyBoy** [Snownee/Jade#40]
Jade does not show up when trying to assemble a CurseForge pack with the mod.

Go to the curse forge app.
Create a Custom Profile for Minecraft 1.16.5
Press Add More Content
Search: Jade or Jade 🔍
Mod does not show up.

I think the emoji in the title is creating issues.
Searching for "Snownee_" works.

Just thought I let you know cause you are missing out on a few potential downloads and people not able to find your mod.
I suggest you change the title of your mod or talk to CurseForge about a fix. They can be reach on their discord server or by @ em on twitter.

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/115635371-250f6d80-a33e-11eb-8fc5-66af57d1f5cf.png)
![image](https://user-images.githubusercontent.com/16059084/115635387-30629900-a33e-11eb-9ede-b968f2c17cc7.png)
Thanks for your suggestion. I don't know why but it works for me

**Comment by EwyBoy** [comment]
All the sudden it works for me now to..
I don't know what was wrong at the time of me posting this issue but it seem to have resolved itself.
