### ISSUE TITLE
Some errors in logs

### ISSUE THREAD

**Issue by Fleepe** [Snownee/Jade#400]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.9.0

### Modloader version

Fabric Loader 0.15.10 + API 0.92.1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Fleepe/e35f0220f4e3d3da36f15a268af507c2

### Issue description

After the game crashed (not the fault of your mod), I saw errors related to your mod in the logs. Can you fix them?
If necessary, I can post the full log and crash report here.

**Comment by Snownee** [comment]
Jade is not fully compatible with notenoughcrashes. and next time send the full log if you want your problem to be solved
