### ISSUE TITLE
[Feature Request] Ability to change config files from blacklist(hide entities/blocks.json) to whitelist

### ISSUE THREAD

**Issue by rikatwo** [Snownee/Jade#401]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.8.0

### Modloader version

0.15.10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I would like for Jade to only show the overlay when looking at some specific mods' specific entities/blocks. With the current blacklist style config files, I would have to write all vanilla and other non relevant mods' blocks & entities to achieve this. 
If there is a way to change mode of the config file to a whitelist, I can list out only the specific blocks/entities I want Jade to show to achieve this.

Sorry if I somehow missed that this is already a feature you can do.

**Comment by Snownee** [comment]
I don't plan to add this feature since I want to keep it simple. You can already do this by generating a config file using a mod like KubeJS
