### ISSUE TITLE
Dutch Translations

### ISSUE THREAD

**Issue by luhcartimods** [Snownee/Jade#406]
### Mod loader

Forge

### Minecraft version

All

### Mod version

All

### Modloader version

All

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

[nl_nl.json](https://github.com/Snownee/Jade/files/15349235/nl_nl.json)
Made Dutch Translations but it didnt allow me to make pr for it!

**Comment by Snownee** [comment]
> Made Dutch Translations but it didnt allow me to make pr for it!

Could you provide more details about this?

**Comment by Snownee** [comment]
Also, please tell me which game version this translation is for.

**Comment by luhcartimods** [comment]
1. About the pr I'm not a collaborator so it didn't allow me 2. I did it for 1.21 fabric

**Comment by Snownee** [comment]
You don't have to be a collaborator to do so. But anyway, I will take the translation, thank you.

**Comment by luhcartimods** [comment]
![image](https://github.com/Snownee/Jade/assets/160168419/a5202f3c-fe57-4a6e-874b-ddc1c3ddedf6)
 
I dont know if I did something wrong but I get this everytime I try to pr

**Comment by Snownee** [comment]
I have no idea. But 4 days ago, it's possible: https://github.com/Snownee/Jade/pull/405

**Comment by luhcartimods** [comment]
I guess, will I still be credited somehow? Kinda want this on my resume lol

**Comment by Snownee** [comment]
```
"gui.jade.translated_by": "Engelse lokalisatie door %s",
"gui.jade.translators": "Bob, Alice, Charlie",
```

Please translate the first line according to your language and use your name on the second line.

**Comment by luhcartimods** [comment]
"gui.jade.translated_by": "Nederlandse vertaling door %s",
"gui.jade.translators": "luhcartimods",

**Comment by Snownee** [comment]
All right, it's done.
