### ISSUE TITLE
Feature request: Expand Applied Energistics 2 support

### ISSUE THREAD

**Issue by ronsardis** [Snownee/Jade#41]
* Forge Version: 36.1.13
 * Mod Version: Jade-1.16.4-2.6.2

Our pack author recently dropped using the One probe and switched to Jade.  I am liking the switch to Jade, the Mekanism support is great on mouse-over for example. I noticed a particularly useful feature is not present in Jade when it comes to AE2. 

When I mouse over a 'Smart Cable' from AE2 it does not tell me the number of channels being used on the info window (eg. 2 out of 8).  If this could be added that would be amazing.  

I have also noted that some of the mouseover data is not very precise.  It does not say exactly what I am looking at in some cases, just a general category like 'AE2 Cable and/or Bus'

Thanks for the work you do on this mod.

**Comment by Snownee** [comment]
It is AE2 does not port their WAILA support to 1.16. They have that in 1.12.

The precise block name is 'AE2 Cable and/or Bus', this is set by AE2. The name you want is the name of the item you pick up from the block. This can be modified by adding WAILA support
