### ISSUE TITLE
Create mod Creative worldshaper error

### ISSUE THREAD

**Issue by NotFish256** [Snownee/Jade#411]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.8.0

### Modloader version

Fabric - 0.15.11

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Create mod Creative worldshaper description of item on ground gives error, it says report it, so I am
![image](https://github.com/Snownee/Jade/assets/105836440/91677f08-5481-425a-975a-5e14ab927788)

**Comment by Snownee** [comment]
could you send your `logs/JadeErrorOutput.txt`?
