### ISSUE TITLE
[Suggestion] Shouldn't Tall Grass & Leaves tooltips show... shears as (one of) the tool(s)?

### ISSUE THREAD

**Issue by BgueC6595** [Snownee/Jade#415]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.9.2 Beta

### Modloader version

0.15.11

### Issue description

When hovering over tall grass and leaf blocks, the tools to break them show up as axe and hoe respectively.

Not sure what the axe is about, but hoe does make sense for leaves.

However both these blocks can also be destroyed (and maybe more importantly obtained) via shears. Shouldn't shears show up for both these blocks?

**Comment by Snownee** [comment]
The problem is that there is no normal way to know if a block can be harvested with shears. Manually maintaining a block list for this purpose is also painful
