### ISSUE TITLE
[BUG] Liquid volume in cauldron is not displayed correctly after installing Amendments

### ISSUE THREAD

**Issue by PTALTS-LK** [Snownee/Jade#416]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.9.3

### Modloader version

47.2.32

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

![image](https://github.com/Snownee/Jade/assets/62936489/01937b1d-0399-423c-a98c-49999113714e)

**Comment by Snownee** [comment]
please report to Amendments first
