### ISSUE TITLE
New Feature request: Show block states require hot key

### ISSUE THREAD

**Issue by acaciachan** [Snownee/Jade#417]
### Mod loader

Please select

### Minecraft version

1.20.1

### Mod version

11.9.2

### Modloader version

Fabric 0.15.11 + API 0.92.2

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

![Clip_2024-06-15_20-02-23](https://github.com/Snownee/Jade/assets/73088428/38179d7e-f01c-472e-b492-8ebbb7add30a)
some block have many block states, and you always dont need it every time, so ...
It would be even better if other information displays, such as coordinate display, could also be made into hotkey-enabled like this.

**Comment by Snownee** [comment]
I don't plan to add it at the moment. For me it's just a debug feature.
