### ISSUE TITLE
Please separate Bosses from Entities in earlier versions of Minecraft in Jade

### ISSUE THREAD

**Issue by Alpha-HDL** [Snownee/Jade#418]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.2

### Modloader version

Forge: 43.3.5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Please separate entities from bosses in earlier versions of Minecraft. In 1.19.2, the "enhanced boss bars" resource pack copies all boss powers and replaces entity names with them. All we need to do is turn boss bars off but we can't in earlier versions of Minecraft. Please add this change so that we can turn only boss bars off just like in 1.20.1 and higher versions of Minecraft!

**Comment by Snownee** [comment]
I don't want to maintain old versions. You can add all the bosses to the blocklist instead
