### ISSUE TITLE
Information about mobs is not shown

### ISSUE THREAD

**Issue by BazZziliuS** [Snownee/Jade#419]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

Jade-1.20.1-forge-11.7.1.jar

### Modloader version

Forge 47.2.32

### Modpack info

https://centurymine.net/server/MagicRPG

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

client https://paste.fuix.net/NgIC3wz
in server [JadeErrorOutput.txt](https://paste.fuix.net/Md9EP7V)

### Issue description

Information about mobs is not shown
![image](https://github.com/Snownee/Jade/assets/18011884/6aa237c3-ce32-4d06-a174-ff7f45d5cf2f)

**Comment by Snownee** [comment]
update Jade
