### ISSUE TITLE
指向采掘工具为剑的方块时无法显示适配工具图标

### ISSUE THREAD

**Issue by ChromaPIE** [Snownee/Jade#42]
如题。

**Comment by Snownee** [comment]
比如？

**Comment by Snownee** [comment]
https://minecraft.fandom.com/zh/wiki/%E5%89%91#.E7.94.A8.E5.89.91.E7.A0.B4.E5.9D.8F.E6.96.B9.E5.9D.97
现在不存在一个方块它的挖掘工具为剑。现在在代码里已经没有剑这种挖掘工具类型了。

**Comment by ChromaPIE** [comment]
> 比如？

譬如安装NoTreePunching模组时的花卉
