### ISSUE TITLE
[Tinkers Construct] Does not show casting table and basin contents and level

### ISSUE THREAD

**Issue by simian-kernel** [Snownee/Jade#421]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

Jade-1.16.4-2.8.3.jar

### Modloader version

Forge: 36.2.42

### Modpack info

-

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://docs.google.com/document/d/1snEwoFW6EWbVDyvqU_ZDwLYgvdtnTfCMJqneho2by74/edit?usp=sharing

### Issue description

In 1.12.2, Jade would show the amount of fluid and it's name in a Tinker's Construct Basin and Table.
In 1.16.5, it does not show these. It treats the table like a chest, ie, only shows the cast name on crouching but no liquid name/levels.

**Comment by Snownee** [comment]
Jade does not provide mod integrations itself

**Comment by Snownee** [comment]
also I don't think there is a feature that shows fluid info on 1.16
