### ISSUE TITLE
Why does Jade Disappear when i open a gui?

### ISSUE THREAD

**Issue by Speiger** [Snownee/Jade#422]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Latest 1.19.2 version

### Modloader version

Latest 1.19.2 version

### Modpack info

Custom

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Question.
Why does Jade Disappear when I open a gui?
We are using an IC2C plugin that adds Jade integration since i wanted to try it out to evaluate if it is worth taking with the next version we port to.
And i realized everytime i open a gui the jade plugin Disappears.
Now normally i wouldn't mind, but i wanted to use the overlay to adjust my overclockers and see how much energy it would consume and thanks to jade Disappearing i had to close the gui after every change.

Is this configurable? Is that intended? Would you considering changing that in the furture?

**Comment by Snownee** [comment]
Because otherwise it will sometimes overlap with the gui and distract the user. I will probably add an option for this in 1.21, but there's no guarantee in 1.20

**Comment by Speiger** [comment]
How would it overlap?
Its an overlay and it means its rendered behind every single gui.
Unless you break minecrafts framebuffer.
If people want a better view of it they can choose a different position.

Also don't worry about if it is 21 or 20, i don't mind it not being backported, i am asking for future releases so issues are solved if we decide we are going with jade instead of TOP ^^"

So far its decent.
