### ISSUE TITLE
Capacity for MI Quantum tanks is read incorrectly

### ISSUE THREAD

**Issue by Tractix** [Snownee/Jade#423]
### Mod loader

NeoForge

### Minecraft version

1.20.4

### Mod version

13.3.1

### Modloader version

Neoforge 20.4.237

### Modpack info

Not using a modpack

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/Tractix/3e03055dab72095b0cdb6d7809dbc571

### Issue description

As the title suggests, it seems Jade thinks the max capacity for the Modern Industrialization Quantum tank is 2.14 million buckets (2147483647 mB I assume) when is it in fact 2147483647000 mB (2.14 billion buckets).

This is also proven by the fact that while Jade thinks the tank is full at 2.14 million I can still fill up the tank.

![image](https://github.com/Snownee/Jade/assets/53498442/c14bd204-74f9-4768-be6a-06f14836ab3f)

**Comment by Snownee** [comment]
On Forge/NeoForge, capacity greater than the 32-bit integer maximum must be supported exceptionally.
