### ISSUE TITLE
关于模组的建议

### ISSUE THREAD

**Issue by Janu-C** [Snownee/Jade#425]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.9.2

### Modloader version

Fabric: Loader 0.14.21 + API 0.91.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

能否像tweakeroo一样能够查看更多容器的内容，比如村民的背包之类的。谢谢！

**Comment by Snownee** [comment]
暂无此计划
