### ISSUE TITLE
[1.21 NeoForge] Jade and Remove Reloading Screen conflict

### ISSUE THREAD

**Issue by Starexify** [Snownee/Jade#427]
### Mod loader

NeoForge

### Minecraft version

1.21

### Mod version

15.1.2

### Modloader version

NeoForge - 21.0.43

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/17JZ6Svw

### Issue description

On 1.21 latest versions of the mods and neoforge. It doesn't show the overlay anymore. And the overlay renderer is crashed if trying to adjust it.

I tried only to load minecraft with Jade and Remove Reloading Screen together. I tested myself. Also reported to Remove Reloading Screen's creator.

I don't know if this is needed but I still give this aswell may help?:
[JadeErrorOutput.txt](https://github.com/user-attachments/files/16051555/JadeErrorOutput.txt)

**Comment by dima-dencep** [comment]
In https://github.com/dima-dencep/rrls/issues/87 I wrote why this happens (I don't know the jade code well), but I don't know how to fix it in rrls.

You can simply add a check to load the theme at the beginning of the ClientProxy#onRenderTick method.
(Everything works fine on fabric)

**Comment by dima-dencep** [comment]
I noticed that on fabric you have a couple checks in the form of shouldShowAfterGui/shouldShowBeforeGui that are missing on neoforge

https://github.com/Snownee/Jade/blob/1.21-fabric/src/main/java/snownee/jade/util/ClientProxy.java#L269-L277

Edit: In vanilla minecraft every reloader waits for each other, I fixed it but not in a good way, still better to fix it in jade
