### ISSUE TITLE
Config not working properly

### ISSUE THREAD

**Issue by FreeMarcher** [Snownee/Jade#431]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.9.2

### Modloader version

Forge 47.3.5

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

The only Display setting that works is Lite (where it always shows the tooltip), and trying to set it to Toggle or Hold causes the tooltip to never display even when pressing my dedicated keybind. Also, Jade always displays the mod name when that setting is turned off.

**Comment by FreeMarcher** [comment]
I actually did just notice that the Mod Name issue can be resolved by changing it in the Plugin settings but not by changing the Mod settings. Keybinds still don't work, though.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue
