### ISSUE TITLE
Blocks in tooltip are showing no texture

### ISSUE THREAD

**Issue by ZestyBlaze** [Snownee/Jade#433]
### Mod loader

NeoForge

### Minecraft version

1.21

### Mod version

15.1.3

### Modloader version

21.0.82

### Modpack info

N/A

### [IMPORTANT] If bug:

- [x] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/ZestyBlaze/49033a291050b4d8d3dd7d85f195c6de

### Issue description

I haven't been able to recreate this in a minimal environment, but when launching the game with these mods installed, all the blocks in the tooltip are showing up as a missing texture instead, might be a incompatibility with a combination of mods as I tested it one on one with most of the mods and couldn't recreate it
![2024-07-12_14 39 59](https://github.com/user-attachments/assets/d065ea94-6b60-4ed7-8d1c-f9710cf35c6c)

**Comment by ZestyBlaze** [comment]
Edit: I've located the issue, it seems to be an issue when the mods Jade, ModernFix and FerriteCore are all present together. 
Jade + FerriteCore seems to be fine, so if I had to guess then it's Jade+ModernFix, but ModernFix crashes without FerriteCore present. 
After removing ModernFix from the pack, they show up properly in the tooltip again

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue. Update mods and try again

**Comment by ZestyBlaze** [comment]
Seems like the ModernFix update that released after I made this report fixed it!
