### ISSUE TITLE
See JadeErrorOutput.txt for more information

### ISSUE THREAD

**Issue by A5ho9999** [Snownee/Jade#434]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.10.0+fabric

### Modloader version

Fabric 0.15.11 | API: 0.92.2+1.20.1

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/A5ho9999/37cf599d0b890940097414e2923aebd6

### Issue description

To reproduce:
1. Install following mods
 - https://modrinth.com/mod/minecells/version/1.8.3
 - https://modrinth.com/mod/pandas-falling-trees/version/0.12.5
 - https://modrinth.com/mod/pandalib/version/0.3.1-1.20
 - https://modrinth.com/mod/jade/version/11.10.0+fabric
 2. Enter the minecells dimension "Promenade of The Condemned"
 - `/execute in minecells:promenade run tp @p 0 90 0`
 3. Look at any large tree in survival mode

**Comment by Snownee** [comment]
please report to Panda's Falling Trees
