### ISSUE TITLE
[Incompatibility] Jade + Conquest Reforged causes strange issues

### ISSUE THREAD

**Issue by TheBrambleShark** [Snownee/Jade#435]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.9.2

### Modloader version

Fabric Loader 1.20.1+0.15.11, Fabric API version: 0.9.2+1.20.1

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/Foxtrek64/c2c39f6c0d3265855847fa3b5c4b537c

### Issue description

**Reproduction Steps**

1. Install Jade, Conquest Reforged, and Fabric API. Conquest Reforged needs a bunch of other mods (like sodium) to look right but this is intended to be a bare minimum setup.
1. Create a new creative world.
1. Enter the game, look at the ground, and press left control.
1. Note that a grass block (or whatever block you're standing on) is now in the hotbar as though you had middle clicked.
1. Move the selector to slot 2. Press left control again. The hotbar selector moves to slot 1.

**Other Notes**
I have created a corresponding issue at Conquest-Reforged/ConquestReforged#409, however for visibility I am creating this issue here. The log file included doesn't log any relevant information, and although it does show I'm playing with a modpack, this is the modpack that I was using when I discovered the issue. The minimal setup above is able to consistently replicate the issue, though nothing is logged to the console.

It seems both of these mods fight over something and the game gets confused. Disabling either Conquest or Jade resolves the issue, but I would strongly prefer to have both in my game.

**Comment by Snownee** [comment]
It's not source-visible so I can't provide help
