### ISSUE TITLE
Client Locks Up Trying to Draw a Progress Bar of Width=Infinity

### ISSUE THREAD

**Issue by shartte** [Snownee/Jade#436]
### Mod loader

NeoForge

### Minecraft version

1.21

### Mod version

Jade-1.21-NeoForge-15.1.3

### Modloader version

21.0.112-beta

### Modpack info

Custom

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

This happened when hovering over a "Cutting Machine" from Modern Industrialization. Their progress integration is here:
https://github.com/AztechMC/Modern-Industrialization/blob/1.21.x/src/main/java/aztech/modern_industrialization/compat/jade/server/MachineComponentProvider.java#L175

It's unclear to me whether this is caused by their progress value, or by the smoothing on the Jade side.

**Comment by shartte** [comment]
When this was happening, I attached a debugger and here are a few screenshots of the state. 
The progress=Infinity is obviously causing it to go into an infinite loop trying to draw this progress bar:
![image](https://github.com/user-attachments/assets/c3319b1b-e74b-43ee-9241-638387eb141d)

The progress on the class itself isn't infinity:
![image](https://github.com/user-attachments/assets/2df5c296-0061-4fb8-a9c8-7db7a73198c1)

But the "smooth progress" has a speed of infinity & value of infinity:
![image](https://github.com/user-attachments/assets/a4a0efef-1188-404e-80f4-6e2250f25f82)

**Comment by Snownee** [comment]
I have no idea how this occurred. But I can add a check to avoid crashing 🤔

**Comment by shartte** [comment]
Probably some division by zero (or near zero?) at some point in-between.
Hard to track down after it already flipped to infinity :-|

**Comment by Snownee** [comment]
yeah that is the check I have added
