### ISSUE TITLE
ExtendedAE - ME Extended Pattern Provider displays all slots

### ISSUE THREAD

**Issue by pcolb1** [Snownee/Jade#438]
### Mod loader

NeoForge

### Minecraft version

1.21

### Mod version

1.5.1.4

### Modloader version

21.0.117

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-10

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

When hovering over an ME Extended Patter Provider the Jade display shows every slot:

https://imgur.com/a/SaYfJmM

Can this be added as a configuration to reduce the number of lines?

Thanks

**Comment by Snownee** [comment]
please upload images directly

**Comment by pcolb1** [comment]
The issue looks to be resolved in the latest ATM 10 pack (0.20) so not sure why it was doing this previously.

ExtendedAE is the same version still (1.1.3), but the Neoforge loader has been upgraded to 21.0.134 so perhaps it was a Neoforge funny :)

Screen shot added anyway for completeness.

![Jade_ExtendedAE_Extended_Pattern_Provider_Hover](https://github.com/user-attachments/assets/5f31b5d6-fe5f-4c37-bc10-23dd9a568a16)

**Comment by Snownee** [comment]
I can't reproduce it either
