### ISSUE TITLE
Health render [Suggestion] (important)

### ISSUE THREAD

**Issue by Jszp03** [Snownee/Jade#440]
### Mod loader

Fabric

### Minecraft version

-

### Mod version

-

### Modloader version

-

### [IMPORTANT] If bug:

- [x] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

You could make it (or add config) so that enity health renders in wider area if rows/amount of hearts is > X
I think the aspect ratio of 2:1 (or 16:9) both look good
EXAMPLE:

==================== Current behaviour: ====================
Entity name: Big Mob
Health:
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️

Current behaviour 2 (if you incerase the hearts per row):
Health:
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

==================== [THIS LOOKS BETTER + MORE COMPACT] =========================
Modified behaviour: (if health rows > 4)
Health:
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

Modified behaviour 2: (if rows <4)
Health:
❤️❤️❤️❤️
❤️❤️❤️❤️
❤️❤️

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time. The core goal of this feature should be to allow user to easily count the health, and I have changed the behavior to make the display more compact since 1.21

**Comment by Jszp03** [comment]
Its nice to hear, are you planning to backport this feature to 1.20.1 as its the most popular version for now?
