### ISSUE TITLE
So...What does the show details keybind actually do? If anything

### ISSUE THREAD

**Issue by scarletwolf134** [Snownee/Jade#443]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.9.4

### Modloader version

Latest Curse forge

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I bound this function Show Details to keypad 6 assuming it would show me a block or creature's id when pressed or its actual stats like hardness but it to my knowledge seems to do nothing? I've been wildly pressing it over every possible thing in and out of my inventory to try and find out what its for and nothing is popping up so is it not working at all or am I just using it wrong?

**Comment by Snownee** [comment]
In Jade itself, you can use this keybind to show more items in an item storage, or show the capacity of the fluid storage
