### ISSUE TITLE
Suggestion: entity names conditionally display

### ISSUE THREAD

**Issue by davidjjung** [Snownee/Jade#445]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.9.2

### Modloader version

Forge 43.3.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I'd like to suggest that entities/players do not display their names/`EntityType`/username if `Entity.shouldShowName()`/`Entity.isCustomNameVisible` is false, or if (specifically for Forge) something like a hook into `RenderNameTagEvent` would return `Event.Result.DENY`.

The version isn't particularly important (assuming this feature hasn't been implemented in later versions, in that case whoops my bad haha). I was mostly asking to tackle [this issue](https://github.com/team-abnormals/environmental/issues/407) and perhaps others in one fell swoop via a sensible-enough feature suggestion. I did want to try mixin-ing before names are rendered in a separate workspace, but I haven't found the specific Jade method for showing the entity's username/entitytype😅. Thanks for your time

**Comment by Snownee** [comment]
The methods you mention only control how the name tag is rendered. It will still appear somewhere else. For Jade, you can replace the entity name with anything else in a plugin

**Comment by davidjjung** [comment]
Just figured out how to do it (currently via a mixin to ObjectNameProvider's appendTooltip). thanks for the tip!
