### ISSUE TITLE
Show books in chiseled bookshelf

### ISSUE THREAD

**Issue by Entropy159** [Snownee/Jade#446]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

15.1.5

### Modloader version

Fabric: Loader 0.16.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

It would be very nice if the mod could display the targeted book's name when looking at a chiseled bookshelf. I could not find a mod to do this, and I think it would fit nicely with this mod.

**Comment by Snownee** [comment]
already implemented
