### ISSUE TITLE
[Lootr] Jade showing as not opened after looting the chest

### ISSUE THREAD

**Issue by Svetrikk** [Snownee/Jade#448]
### Mod loader

Please select

### Minecraft version

1.20.1

### Mod version

5.2.2

### Modloader version

Forge 47.3.0

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

After opening and taking all items from a Lootr chest, the Jade shows the chest as not opened yet

**Comment by Snownee** [comment]
![image](https://github.com/user-attachments/assets/08e7f535-0d68-4a1f-acea-d11d30d1ebc3)
Hello, I can't reproduce this issue

**Comment by Svetrikk** [comment]
Hey, sorry for a late respons. When you open the chest the first time it shows the content of the chest. However, if you take everything from the chest then jade says “Items not generated”.

**Comment by Snownee** [comment]
oh, I can reproduce it now
