### ISSUE TITLE
Incompatibility with Cobblemon Fossil Restoration machine

### ISSUE THREAD

**Issue by Blaize6363** [Snownee/Jade#449]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.9.2

### Modloader version

0.15.11

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Looking at the fossil restoration machine, it says this
![image](https://github.com/user-attachments/assets/465b5d59-e2f2-47a8-9829-487820344b9e)

**Comment by Snownee** [comment]
please report to Cobblemon Integrations
