### ISSUE TITLE
Crash on world join

### ISSUE THREAD

**Issue by NielsPilgaard** [Snownee/Jade#45]
* Forge Version: 1.16.5-36.1.16
 * Mod Version: 1.16.4-2.7.1

https://gist.github.com/NillerMedDild/ddf6592f448f680d4b76ebf6038a9434

**Comment by NielsPilgaard** [comment]
It seems to happen when I leave the world in creative mode, and then log back in.

**Comment by Snownee** [comment]
I did some investigation. The EasyPaxelLITE mod passes an illegal null value to the tool types, so Jade failed to register things.

so not my mistake 😋

**Comment by NielsPilgaard** [comment]
Ah I see, thanks :)
