### ISSUE TITLE
Wrong name showing in tooltip

### ISSUE THREAD

**Issue by BelleBernice** [Snownee/Jade#451]
### Mod loader

NeoForge

### Minecraft version

1.21

### Mod version

15.1.6

### Modloader version

21.0.167

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-10

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

The name of all the Comb Blocks from the mod '[Productive Bees](https://www.curseforge.com/minecraft/mc-mods/productivebees)' isn't correct!

I compared Jade with the '[WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit)' mod and the '[One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)' and only the one probe have the correct block names. Is it fixable for Jade maybe? 

![javaw_nFDFGuhJxe](https://github.com/user-attachments/assets/f546b61e-3b76-4b24-a589-cbfda88b5edd)

**Comment by Snownee** [comment]
TOP's implementation is wrong. You should contact the devs of Productive Bees to fix this issue: https://github.com/TehNut-Mods/HWYLA/issues/257

**Comment by JaisDK** [comment]
How is this something I should fix? You're using a method that Forge/NeoForge has created a more accurate alternative to and declared the old vanilla one as deprecated. I am implementing the "new" and more accurate one and you should be using it.

![image](https://github.com/user-attachments/assets/4b2e2995-4b80-4729-bab8-061e5223f52d)

<https://github.com/JDKDigital/productive-bees/blob/dev-1.21.0/src/main/java/cy/jdkdigital/productivebees/common/block/ConfigurableCombBlock.java#L56>

**Comment by Snownee** [comment]
@JaisDK You are referring to the item name, not the block name. If you want to show the item name instead, use `IWailaClientRegistration#usePickedResult`
