### ISSUE TITLE
Mod turns off by itself

### ISSUE THREAD

**Issue by oreo1477** [Snownee/Jade#452]
### Mod loader

Fabric

### Minecraft version

1.20,4

### Mod version

13.3.1

### Modloader version

Fabric - 0.15.11

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Baically, the "Display Tooltip" setting randomly turns off by itself, no idea why.

**Comment by Snownee** [comment]
you can press 1 on your numpad to turn it on
