### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [Snownee/Jade#457]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.10.1 Forge

### Modloader version

47.3.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

How can I disable the display of the modification name in Jade? For example, this is necessary when you want a unique passage so that players cannot understand which items belong to which fashion and Google a certain guide. It's just that the display of the fashion name is turned off in EMI. But there is one here anyway.
![image](https://github.com/user-attachments/assets/3e871fab-9a8f-43df-831a-c58e242a67b9)
![image](https://github.com/user-attachments/assets/16713033-87b0-4b96-b9a5-08b85fd2dad4)
![image](https://github.com/user-attachments/assets/d649cafd-fc71-4291-84f2-058aad29d491)

**Comment by Snownee** [comment]
disable it in the plugin settings
