### ISSUE TITLE
Undesireable interaction/game freezing and/or crash with Jade and Iron's Spells and Spellbooks.

### ISSUE THREAD

**Issue by ExiledMiner04** [Snownee/Jade#464]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

15.1.8+neoforge

### Modloader version

Neoforge 1.21.1 21.1.31

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/ExiledMiner04/319c196ea8156b0f2a9a0770b66d93ea

### Issue description

Observed behaviour (taken from my report in iron's spells and spellbooks git hub):

I found a priest village to have died fighting a mob when it wandered over water. It dropped a lot of stuff including some scrolls, ink of various rarities and even holy runes. It dropped an inscribed spell scroll and a blank one probably one that is Null that I seen back in 1.20.1. I checked the bugged scroll (by hovering over it or scrolling to it) and the game will freeze to a halt and become unresponsive, no crash report can be generated though. I had one occur during looting said item or related to something else on the mod? I can post it here.

New observation: it can also crash instead of hang when looted and moused to (gist attached of latest.log). I even have an image of the bugged item with looking at it with Jade. It says to report to Jade.

![image](https://github.com/user-attachments/assets/6932cfe3-68cc-42f4-be98-799a62db4bbc)

Other mods that have been used to get to this result faster:

Jade-1.21.1-NeoForge-15.1.8
geckolib-neoforge-1.21.1-4.6.2
jei-1.21-neoforge-19.8.2.99
alllootdrops-1.21.1-3.4
collective-1.21.1-7.84

**Comment by ExiledMiner04** [comment]
Its more on Irons' end and Alllootdrops end it seems.

**Comment by Snownee** [comment]
Thanks. Please report to irons_spellbooks mod
