### ISSUE TITLE
Powder Snow appearing as a Snow Block on servers

### ISSUE THREAD

**Issue by The-Crimson-V** [Snownee/Jade#465]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.2.1

### Modloader version

Fabric: Loader 0.16.2

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

When viewing Powder Snow on a server, Jade lists it as a regular Snow Block. This does not occur for me on singleplayer. The server I am on uses a few plugins (unsure which) and no mods. I have yet to test it on any other server.

**Comment by The-Crimson-V** [comment]
Fabric API is 0.102.1 in case you need that.

**Comment by Snownee** [comment]
Duplicate of #341
