### ISSUE TITLE
forge support for 1.21.1

### ISSUE THREAD

**Issue by AnimalLover2143** [Snownee/Jade#469]
### Mod loader

Forge

### Minecraft version

1.21.1

### Mod version

a new one

### Modloader version

the newest forge version

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

1.21.1 Forge support

**Comment by Snownee** [comment]
use NeoForge

**Comment by AnimalLover2143** [comment]
ok

**Comment by AnimalLover2143** [comment]
i found out i shoud just use fabric
not right now what i mean is when i posted this i was gonna use forge
but i realized its better to use fabric
