### ISSUE TITLE
Jade reports blocks behind the world boarder

### ISSUE THREAD

**Issue by BrailleBennett** [Snownee/Jade#474]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.4.1

### Modloader version

FL 1.16.5 FAPI 0.105.0

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

If you look at the world boarder, jade will provide information on blocks behind it, and not on either the world boarder itself or nothing. This could be seen as an unfair advantage in certain situations.

**Comment by Snownee** [comment]
Thanks for the suggestion. The advantages gained are not significant. So I don't plan to add this feature in the near future
