### ISSUE TITLE
[1.21.1][NeoForge][!Connector!] Incompatible with the Flashback mod, crashes when entering  a replay.

### ISSUE THREAD

**Issue by VOLKOUL** [Snownee/Jade#477]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

[NeoForge 1.21.1] 15.4.1

### Modloader version

NeoForge 21.1.62

### Modpack info

-

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/pJu5nm2 (Go to line 878, ignore resource pack spam plz)

### Issue description

Flashback is running via the Connector mod (perfectly fine when it's by itself). Flashback's mod Author requested that no Forge/NeoForge issues be reported directly to their Github/Discord, therefore if there's an issue with a non Fabric mod, I have to rely on said mod to add compatibility. Flashback is a must have mod imo and I hope that something can be done about this :D

**Additional Info**
Launcher Error Message: The game crashed whilst exception in server tick loop
Error: java.lang.UnsupportedOperationException: Payload jade:server_ping_v1 may not be sent to the client!

**Comment by Snownee** [comment]
I can't fix it. Please report to Connector
