### ISSUE TITLE
Enchantment book displaying mod tooltip first and the the name of the enchatment

### ISSUE THREAD

**Issue by Kloytz** [Snownee/Jade#480]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.4.1

### Modloader version

0.16.5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

![image](https://github.com/user-attachments/assets/d9cdab5b-8791-4620-a08b-cb74327a47f5)
As seen on the image the mod which adds this enchantment is displayed first and latter the enchantment name, asked the creator of the mod and he seems to have no idea, so any piece of information regarding this and how to solved it would be very nice.

**Comment by Snownee** [comment]
![image](https://github.com/user-attachments/assets/bd0b8c38-90d6-471c-b5a7-79de089928e9)
Hello, I can't reproduce this issue

**Comment by Kloytz** [comment]
The issue does not appear with minecraft enchantments, it only appears on an enchantment from another mod
https://modrinth.com/mod/vein-mining
I was able to reproduce it with only vein mining, fabric api and jade.
