### ISSUE TITLE
jade error

### ISSUE THREAD

**Issue by shenyx110** [Snownee/Jade#481]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

15.4.1

### Modloader version

neoforge21.1.65

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

[crash-2024-10-03_21.44.41-client.txt](https://github.com/user-attachments/files/17245164/crash-2024-10-03_21.44.41-client.txt)
[debug.log](https://github.com/user-attachments/files/17245166/debug.log)
[JadeErrorOutput.txt](https://github.com/user-attachments/files/17245170/JadeErrorOutput.txt)
[latest.log](https://github.com/user-attachments/files/17245171/latest.log)
[log.txt](https://github.com/user-attachments/files/17245173/log.txt)
![截屏2024-10-03 21 42 53](https://github.com/user-attachments/assets/7a4c1011-b5fc-477f-8fd5-1cb8c90889ac)

**Comment by shenyx110** [comment]
![截屏2024-10-03 22 58 04](https://github.com/user-attachments/assets/fe6de714-ca0c-4da8-90cd-c598f3892e49)
[minecraft-exported-crash-info-2024-10-03T22-58-56.zip](https://github.com/user-attachments/files/17246160/minecraft-exported-crash-info-2024-10-03T22-58-56.zip)
[minecraft-exported-logs-2024-10-03T22-58-43.log](https://github.com/user-attachments/files/17246162/minecraft-exported-logs-2024-10-03T22-58-43.log)

**Comment by Snownee** [comment]
please report it to Improvable Skills
