### ISSUE TITLE
[Bug(?)]Compatibility with older versions Jade on server

### ISSUE THREAD

**Issue by E0x72-21** [Snownee/Jade#482]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.5.1

### Modloader version

fabric0.16.5 api0.105.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

When I use Viafabricplus 1.21.1 client(with jade) enter a server that also have jade but the game version is 1.20.4, Jade can not get block/entity information from server normally.

**Comment by Snownee** [comment]
Sorry, I have no interest in cross-version support
