### ISSUE TITLE
(Bug) Error on startup, can't figure out why it happens

### ISSUE THREAD

**Issue by KiraKayn** [Snownee/Jade#483]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.12.1

### Modloader version

Forge: 47.3.7

### Modpack info

Its my modpack but unfinished, no link yet

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/KiraKayn/e8ce60596978b3e41cf99427ccb8b0c7

### Issue description

I get this error when starting up the modpack, some mixin stuff, not much I can say about it.
![image](https://github.com/user-attachments/assets/e761fc9f-bb4e-4fab-b8d9-942252b1628a)

**Comment by Snownee** [comment]
delete nyfscompat
