### ISSUE TITLE
TerraFirmaGreg StackOverFlow 1.20.1

### ISSUE THREAD

**Issue by KoboDev** [Snownee/Jade#484]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.9.4

### Modloader version

Forge 47.2.6

### Modpack info

https://www.curseforge.com/minecraft/modpacks/terrafirmagreg

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/KoboDev/18fb61861c6e88f53c814a6c3287dccb

### Issue description

I was walking around in LAN enabled, going to a nearby volcano when the Trees started showing this.
![image](https://github.com/user-attachments/assets/6ba50683-e0c3-4500-b97f-9ef291b7c2cd)

Looking into the ErrorReport first it says it was a StackOverflow
And after some lines keeps repeating me.pandamods.fallingtrees.*

**Comment by Snownee** [comment]
This is a bug in PandasFallingTrees
