### ISSUE TITLE
Custom payload jade:receive_data contains NBT data that exceeds limit causing a crash

### ISSUE THREAD

**Issue by klugemonkey** [Snownee/Jade#487]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

15.4.1

### Modloader version

NeoForge 21.1.61

### Modpack info

Direwolf20 1.21

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/klugemonkey/d2cafaecc424526e7e966d8f5535f2e9

### Issue description

Custom Payload not bounds checking and handling gracefully.  Something in the player inventory received from loot from a Bastion Chest on Direwolf20 1.21 might have caused Jade custom payload to be created that exceeeds the NBT tag limit causing a client side crash.  Not sure what mod initiated the item.  The player is kicked upon login repetively, so something in the inventory is causing, but Jade should probably check limits on packets its creating and not try to display.  May be related to other mixins.  Will follow up as well with Modpack creator and server host.

**Comment by Snownee** [comment]
Update Jade. It's 1.21.1, not 1.20.1

**Comment by klugemonkey** [comment]
file says, Jade-1.21.1-NeoForge-15.4.1.jar.

**Comment by klugemonkey** [comment]
Disabled "displayBlocks" under general and can login.  Happens when looking at the AE2 ME Drive when trying to display the block.  The drive has a lot of storage items.  Does it look at every item in the storage?

Also, under plugins.json, under "ae2" list, is there a setting for disabling just the ME Drive?

**Comment by Snownee** [comment]
update the mod

**Comment by klugemonkey** [comment]
ok was able to put "ae2:drive" under the "values" list under hide-blocks.json and am able to use this as a workaround.
I'll try with latest mod on client side.

**Comment by klugemonkey** [comment]
I tried replacing with Jade-1.21.1-NeoForge-15.5.2 and the problem still occurs in that release.

Then, I tried with Jade-1.21.1-NeoForge-15.6.0 however this version is incompatible with the older version on the server, as the older uses version:3 of jade:receive_data and the newer version:4.  So, I'm unable to test if the problem is resolved or not since the FTB Direwolf20 1.21 server is not mine.

**Comment by klugemonkey** [comment]
Not sure there is much left for me to do, other that see if its a specific item in the drive by removing storage by storage, item by item.  Sorry, that I can not be of further assistance in resolving this issue.  For now I guess I'll just use the workaround until they update to the 15.6.0 release.

**Comment by klugemonkey** [comment]
One more note, this doesn't occur with 2 of the other ME Drives, only a particular ME Drive, so I'm wondering if it is in fact some item that is causing this issue.  I'll try to narrow it down, see if there is a culprit, and maybe be able to reproduce on a local server.

**Comment by Snownee** [comment]
should be completely fixed in [15.7.1](https://modrinth.com/mod/jade/version/zoXpBSpm)

**Comment by klugemonkey** [comment]
strange that it happens when I move the item storage over to a chest, looking at the chest fails.  And when I have some in the chest, some in the drive, neither fails.   I'm thinking it's less of a specific item issue and more of too many items issue.

**Comment by klugemonkey** [comment]
Thanks for the updates.
