### ISSUE TITLE
RayTracer for Extended Reach > 1 bugged

### ISSUE THREAD

**Issue by thimblebird** [Snownee/Jade#489]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.12.0+fabric

### Modloader version

Fabric: Loader 0.16.7 + API 0.92.2+1.20.1

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/wgGEbp9s

### description:
seems like the end of the raytracer becomes slightly off, as you can see in the following demonstration - crouching while targeting a block. sandstone is briefly the target of the raytracer, even though i'm looking at the blast furnace according to my crosshair.

you can see it takes a few frames before reaching the actual crosshair target. in the video, the distance is jumping from 5.8 (🎯) to 5.7, then 5.8 (both sandstone), until finally reaching 5.8 again (🎯).

🎯 _= target block_

the frames, in order:
![jadebug](https://github.com/user-attachments/assets/73396088-d9d6-4e0a-8f86-96a68af7ac52)

### demonstration video:
https://github.com/user-attachments/assets/daf67921-7457-40d4-8857-f1aff0a71a87

### jade configs:
[jade.zip](https://github.com/user-attachments/files/17368006/jade.zip)

**Comment by Snownee** [comment]
what is the exact minecraft version you are on?

**Comment by thimblebird** [comment]
> what is the exact minecraft version you are on?

1.20.1

//e:
i see the fabric api (and mod version) saying 1.21.1 above. i initially wanted to reproduce in 1.21.1, but the extended reach option is completely non-functional there (and i didn't create an issue yet as i don't play on 1.21.1).

updated versions above.

**Comment by Snownee** [comment]
could you try to reproduce this problem on Jade 11.11.0?

**Comment by thimblebird** [comment]
> could you try to reproduce this problem on Jade 11.11.0?

i tried, and i can't reproduce it on `11.11.0`.

//e:
https://github.com/Snownee/Jade/pull/387 oh god, math. good luck!

**Comment by thimblebird** [comment]
Are you planning to update the 1.20.1 version, too? (not that I really need it just yet, I'm just curious)

**Comment by Snownee** [comment]
yes, most likely

**Comment by thimblebird** [comment]
❤️🐛
