### ISSUE TITLE
[Mod支持]能否添加植物魔法的魔力池支持?

### ISSUE THREAD

**Issue by Duorhs** [Snownee/Jade#49]
在1.12版本的植物魔法附属mod：额外植物学 中，mod作者添加了waila与botania的联动，其中支持魔力池显示魔力量的相关源码如下：https://github.com/ExtraMeteorP/Extra-Botany/blob/master/src/main/java/com/meteor/extrabotany/client/integration/waila/WailaPool.java
希望能够得到支持，谢谢

**Comment by Snownee** [comment]
不会支持的。植物魔法作者不喜欢这样
