### ISSUE TITLE
[Suggestion] Show dog/cat breed info in tooltip (helpful for older/custom resource packs)

### ISSUE THREAD

**Issue by BlueJayofEvil** [Snownee/Jade#490]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.8.0

### Modloader version

Fabric 0.16.7 + Fabric API 0.106.0

### Modpack info

https://modrinth.com/modpack/arcomua

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

This is a simple request to show information about dog/cat breeds in the entity tooltip. Various dog breeds were introduced in 1.20.5 and many custom resource packs (especially older ones) don't account for this change, making determining breeds difficult without some kind of external tool/mod. Cats have long since had various breeds, and the same issue applies to them.

Thank you.

**Comment by Snownee** [comment]
how would you like to display them?

**Comment by BlueJayofEvil** [comment]
A line in the tooltip with the variant name and a small icon next to it should work.
Like this:
![wolf variants](https://github.com/user-attachments/assets/65ed3a94-91b0-4751-8e14-3585e9ea08e9)

Same style for cats should also work.

**Comment by BlueJayofEvil** [comment]
I forgot to add parrots to this request as well.
Thank you!

**Comment by Snownee** [comment]
Icon is another topic that is much more difficult. To see entity variants, you can enable the accessibility plugin in the mod settings
