### ISSUE TITLE
[Suggestion] Add the capability of a whitelist, instead of only an ignore list for blocks/entities

### ISSUE THREAD

**Issue by IgnacioRodriguez01** [Snownee/Jade#491]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.3.4

### Modloader version

Fabric: Loader 0.16.7 + API 0.105.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

This idea came to my mind when trying to config Jade to show only on container and ore blocks, and I came upon the only option is adding values that will be ignored on the hide-blocks.json file. Technically, I can achieve what i want adding ALL kinds of blocks except the ones that I want to display, but is obvious the inconvenience this approach presents.

**Comment by Snownee** [comment]
Use regular expression:
```json
{
	"values": [
		"minecraft:barrier",
		"/^(?!^(.+_ore|minecraft:ancient_debris|minecraft:chest|minecraft:barrel)$).+$/"
	]
}
```
