### ISSUE TITLE
Human-readable cauldron level indicators

### ISSUE THREAD

**Issue by Hebgbs** [Snownee/Jade#492]
### Mod loader

Fabric

### Minecraft version

any?

### Mod version

any?

### Modloader version

any?

### Modpack info

N / A

### [IMPORTANT] If bug:

- [x] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

As it says on the tin. Presently, using water as an example; the levels show as `1B` (full-block), `666 ⅔ mB` (Huh? I presume this is meant to be two-thirds) and `333 ⅓ mB`. Why not omit the "1B" for empty, change `333 ⅓ mB` to `1`, change `666 ⅔ mB` to `2` and `1B` to `3`?

**Comment by Hebgbs** [comment]
There might be more to it; Idk how water levels truly work in Minecraft and I am sure the way it's done now accounts for water from dripstone, but it's just _hella_ weird.

**Comment by Snownee** [comment]
because modded fluid containers need them
