### ISSUE TITLE
[Suggestion] Show goat information in entity tooltip

### ISSUE THREAD

**Issue by BlueJayofEvil** [Snownee/Jade#493]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

1.5.80

### Modloader version

Fabric Loader 0.16.7 + Fabric API 0.106.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Similar to my previous request about dog/cat/bird breed info, could goat details be added to the accessibility details?
The main one I'm looking for is showing the "Screaming Goat" tag if it's a screaming goat. I was thinking something like "Screaming Goat: true/false", maybe formatting the "true" to be brighter and/or bold for easier seeing. As long as the info is there is fine, I'm not too picky.

Secondary request would be horn information. A simple "Has Horns: Left/Right/Both/None" would be simple enough.

Thank you!

**Comment by Snownee** [comment]
If you look at a hornless goat with the accessibility plugin on, it will be displayed. I don't have the plan to add the screaming goat feature for now.
