### ISSUE TITLE
Mod name tooltip doesn’t show in creative mode

### ISSUE THREAD

**Issue by Nevrai** [Snownee/Jade#498]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.12.1

### Modloader version

47.3.11

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Though the mod name tooltip, enabled by default, appears as expected in survival, adventure, and spectator mode, it doesn’t appear in creative mode. Instead, it just shows the creative tab name.

Tested with no mods except Jade installed.

**Comment by Snownee** [comment]
This is intended. Otherwise people will complain about why two mod names are shown in the tooltip

**Comment by Nevrai** [comment]
> This is intended. Otherwise people will complain about why two mod names are shown in the tooltip

I see. It would be great if you could add an option in the client config to enable mod name tooltip in creative mode. (Creative mode shows category tooltips, not mod name tooltips, though occasionally they can be the same.)

Ideally, you’d, if this is feasible, check if the category and the mod name are identical, and if so, hide the mod name tooltip. However, that’s not entirely necessary, and I’d appreciate just having the option to enable Jade’s mod name tooltip on items in creative mode.
