### ISSUE TITLE
Add Handshake

### ISSUE THREAD

**Issue by s-yh-china** [Snownee/Jade#499]
### Mod loader

Fabric

### Minecraft version

1.21.2

### Mod version

16.0.4

### Modloader version

Not important

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

In the current network, if the protocol between the client and server is inconsistent, the client will be directly kicked, is not conducive to use.
If we add `ClientPingPacket`, we can declare the client mod version in it, allowing the server to selectively send/not send packet, thereby achieving gentler and more reliable functionality.
If you don't have time, I can create a PR to increase this support, but I need to see your attitude before working on it

**Comment by Snownee** [comment]
That sounds good. You can PR it. I think you will need to store if a player is supported on the server side

**Comment by Snownee** [comment]
Also it would be nice if it can notify the player of the mod version on the server
