### ISSUE TITLE
[MOD兼容]能否支持与双语同屏MOD兼容？

### ISSUE THREAD

**Issue by AiryC7** [Snownee/Jade#50]
我注意到在1.16.4/5下双语同屏mod : https://www.curseforge.com/minecraft/mc-mods/untranslated-items  与 Hwyla : https://www.curseforge.com/minecraft/mc-mods/hwyla  可以完美兼容,  效果是hud上一排英文一排中文.  可Jade与双语同屏在一起却显示的是两排中文.  “ 1.16+: Jade is a fork of HWYLA that includes many additional features and bug fixes. Which means it is incompatible with Hwyla (because it has included it) ”  希望能够与双语同屏mod兼容.  感谢!

**Comment by Snownee** [comment]
更新双语同屏
