### ISSUE TITLE
Option to only show mod name for non-vanilla targets

### ISSUE THREAD

**Issue by ChloeDawn** [Snownee/Jade#501]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.12.0

### Modloader version

Fabric 0.16.9

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I am trying to keep the tooltip as concise as possible, so an option to only show the mod name for non-vanilla blocks, items, and entities would be great.

**Comment by ChloeDawn** [comment]
Additionally I'd love an option to have it only show the mod name when Advanced Tooltips are off, to pair with registry name only showing when they are on.

**Comment by Snownee** [comment]
Sorry but I don't favor these ideas. They don't seem very necessary. I don't want the options to be too bloated. You can implement them yourself
