### ISSUE TITLE
Resource Pack GUI shows on-top of jade interface

### ISSUE THREAD

**Issue by DenizUe** [Snownee/Jade#502]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.8.3

### Modloader version

Fabric: Loader 0.16.9 + API 0.107.0

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/eDXZ9rI

### Issue description

Everything worked just fine until I changed the order of two resource packs (for enchanting books) and reloaded the game. Then the chest GUI started to kay on top of the Jade GUI whenever I looked at a chest/large chest. Barrels still work without any issues. I am using Colourful containers GUI, but I also tried with other GUI resource packs, the same issue.
Tried to reproduce the bug on a new instance, still there. 
![CleanShot 2024-11-10 at 01 37 48@2x](https://github.com/user-attachments/assets/05aa5b0f-af30-48d7-95fd-7de39c43b7c3)

**Comment by dedouwe26** [comment]
I have the same issue on 15.1.5+fabric in 1.21. I also use the [Colourful Containers GUI](https://modrinth.com/resourcepack/colourful-containers-gui) and [Even Better Enchants](https://modrinth.com/resourcepack/even-better-enchants) along with [OptiGUI](https://modrinth.com/mod/optigui).
