### ISSUE TITLE
Looking at a Zombie Villager throws Exception

### ISSUE THREAD

**Issue by Doeniel** [Snownee/Jade#504]
### Mod loader

Fabric

### Minecraft version

tested on 1.21.1 and 1.21.3

### Mod version

tested on 16.0.4 and 15.8.3

### Modloader version

tested on Fabric 0.16.7 with Fabric API 0.109.0 and Fabric 0.16.9 with Fabric API 0.109.0

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/Doeniel/a7c9d61772d81352161cc1e9c86c1be3

### Issue description

When looking at a Zombie Villager, the game doesnt show anything at the top and throws a ClassCastException.

**Comment by ExiledMiner04** [comment]
Happens in neoforge version 1.21.1 of this as well, but with nothing thrown, just nothing is displayed rather.
