### ISSUE TITLE
Breaks when using Faithful ressource pack

### ISSUE THREAD

**Issue by Nierninwa** [Snownee/Jade#517]
### Mod loader

Fabric

### Minecraft version

1.21.4

### Mod version

17.0.0

### Modloader version

Fabric Loader 0.16.9 + Fabric API 0.110.5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

<script src="https://gist.github.com/Nierninwa/828fe1c7eb6866de6d7aa50c4ca3e2a6.js"></script>

### Issue description

When using Faithful 64x or 32x, all text disappears from the mod. It doesn't do it with Alacrity, which is also a 32x pack, and it still does it with all other mods turned off. Older releases of Faithful 64x also cause the bug (I tried up to release 4).

![Screenshot 2024-12-05 200216](https://github.com/user-attachments/assets/659ec6a7-ebde-4678-8dd0-ee5441f77eb7)

![Screenshot 2024-12-05 200452](https://github.com/user-attachments/assets/100bb52a-eb6e-44f3-ab31-fec7ff0b8cd9)

**Comment by Ahmad2304** [comment]
Yeah, this is also happening to me with Vanilla Tweaks, I think it's just any Resource Pack that changes the font that breaks it.
![2024-12-05_22 07 24](https://github.com/user-attachments/assets/d1b83383-446f-4010-b69e-a5e331fc093a)
