### ISSUE TITLE
NeoForge Energy is no longer displayed in Jade as of 15.8.3

### ISSUE THREAD

**Issue by MuteTiefling** [Snownee/Jade#523]
### Mod loader

Please select

### Minecraft version

1.21.1

### Mod version

15.9.0

### Modloader version

NeoForge 21.1.85

### Modpack info

https://www.curseforge.com/minecraft/modpacks/enigmatica10

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Haven't yet had a chance to full break things down and test on an individual level. But currently Energy will not display in Jade versions 15.8.3 and 15.9.0. I've had to downgrade as far as 15.8.2 in order to be able to see Energy in Jade.

**Comment by theboo** [comment]
Reported to Theurgy as well but seems to be an issue between theurgy and jade 15.8.3+, removing either theurgy or downgrading Jade to 15.8.2 "fixes" the issue.

**Comment by klikli-dev** [comment]
That looks like it is on me, not 100% sure yet what I need to do but will look into it! 

EDIT: I did a quick comparison of my [MercuryFluxEnergyProvider](https://github.com/klikli-dev/theurgy/blob/version/1.21.1/src/main/java/com/klikli_dev/theurgy/integration/jade/MercuryFluxEnergyProvider.java) and the [Theurgy Jade Plugin](https://github.com/klikli-dev/theurgy/blob/version/1.21.1/src/main/java/com/klikli_dev/theurgy/integration/jade/JadePlugin.java) to the universal energy storage provider supplied with Jade and I could not find anything immediately obvious that would cause this behaviour.

@Snownee if you have any ideas on what I am doing wrong input would be appreciated. Mercury Flux is intentionally not compatible with forge energy (or whatever it is now called), it works the same way but is a magical energy system. Hence the use of mercury flux capabilities.

**Comment by Snownee** [comment]
hopefully fixed now. thanks for testing out
