### ISSUE TITLE
Just Dire Things  Paxel and jade crashes client when looking at blocks 

### ISSUE THREAD

**Issue by kapatchie** [Snownee/Jade#524]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

15.9.0

### Modloader version

Neoforge: 21.1.89

### Modpack info

ATM10 V2.5 https://www.curseforge.com/minecraft/modpacks/all-the-mods-10

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/qDhNnJQS

### Issue description

Having a Celistigem Paxel equipped, Crashes Client Side only, Muliplayer server is unaffected, unable to reproduce in single player

**Comment by Snownee** [comment]
update Relics: Artifacts Compat
