### ISSUE TITLE
villager info not updated

### ISSUE THREAD

**Issue by yzqdev** [Snownee/Jade#527]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

15.9.1 neoforge

### Modloader version

neoforge 21.1.84

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I have made a minimal repo, here is the  code. https://github.com/yzqdev/jade-villager/blob/main/src/main/java/com/example/examplemod/MaidProvider.java

**village inventory have changed, while data from entity accessor still the old data.**

as the video, i use data get command to get the village's inventory, it has some carrots, while when debugging ,the entity of villager(`entityAccessor.getEntity() instanceof Villager ` ) shows it's inventory is null

https://github.com/user-attachments/assets/7413f73b-c4bc-4ef0-8de0-72624b3b39fc

**Comment by Snownee** [comment]
By default, entity data will not sync to the client.

Please do not ask dev questions here. Thanks.
