### ISSUE TITLE
Suggestion: Show block hardness & item durability

### ISSUE THREAD

**Issue by thecrazy** [Snownee/Jade#528]
### Mod loader

Please select

### Minecraft version

1.20.1

### Mod version

11.11.1

### Modloader version

Forge 47.3.11

### Modpack info

https://www.curseforge.com/minecraft/modpacks/cave-horror-project

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Some mobs introduced by mods can break blocks up to a certain hardness to get to you. It would be very useful to be able to see the hardness info when base building. Also, item durability would be nice to compare tools from all the different mods.

**Comment by Snownee** [comment]
Block hardness has been implemented in newer versions. Item durability can be viewed in advanced tooltips mode
