### ISSUE TITLE
Please allow me to close it

### ISSUE THREAD

**Issue by Dazzle-sys** [Snownee/Jade#53]
![image](https://user-images.githubusercontent.com/55978588/124341461-2a671f00-dbef-11eb-996d-b8055223d39d.png)

If bug:

 * Forge Version: 
 * Mod Version: 
 * Can you reproduce this issue with relevant mods only?: yes/no

Paste your crash report to somewhere like https://paste.ubuntu.com/ , instead of directly here.

** Bug reports please follow the format! or it might be closed! **

**Comment by Snownee** [comment]
You can. It is in plugin settings
