### ISSUE TITLE
Internal Jade Error Crashes Game when Breaking Block in Multiplayer

### ISSUE THREAD

**Issue by Alexius25** [Snownee/Jade#534]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

15.9.2

### Modloader version

21.1.89

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-the-mods-10

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/CVuNQ7wi

### Issue description

Im playing on ATM 10 on an Steam Deck Oled

On the GUI it said an Internal error occurred and if I try to break an block it Crashes the Game. I tried Updating the Mod and restarting both the Server and the Client. Nothing Worked. Could that come of an bad Internet Connection?

**Comment by Snownee** [comment]
Duplicate of #524

**Comment by Alexius25** [comment]
I have updated the RAR Mod and the Relics Mod but now my game crashes, any fixes for that?

**Comment by Snownee** [comment]
it's not related to Jade

**Comment by Alexius25** [comment]
Oh Sorry, But thaks for your Help!
