### ISSUE TITLE
[2.7.1-1.16.5]盔甲值不一定能正确显示

### ISSUE THREAD

**Issue by AlanightCreeper** [Snownee/Jade#58]
forge: 36.2.0
mod: 2.7.1

如图所示，龙鳞套总护甲值26点，但只显示了20点，然而下面这个总护甲值为50的龙钢套(护甲值是自己魔改的)却成功地以数字的形式显示了出来，经多次试验，发现区间 (20, 40] 中的护甲值只能以10个盔甲值图标(即20护甲值)的形式显示。
尽管是用盔甲架做的实验，但实际上显示有护甲值的生物之时也存在这种问题，故应该可排除实体种类造成的影响。
![2021-07-24_20 06 31](https://user-images.githubusercontent.com/82942121/126886740-1d0ffdc1-1d16-493c-8a4a-094e4d29317a.png)
![2021-07-24_20 07 01](https://user-images.githubusercontent.com/82942121/126886758-e4760689-57d2-4669-a5d1-c2058461c096.png)

**Comment by Snownee** [comment]
修复了
