### ISSUE TITLE
Crash ( Exit Code 0 )

### ISSUE THREAD

**Issue by MLMII** [Snownee/Jade#6]
Minecraft Version: 1.16.3
Mod Version: 2.0.0
Forge Version: 34.1.35

While attempting to start the game crashes with an "Exit Code 0" error and no crash log that I can find.

Thanks

**Comment by realTIMematrix** [comment]
Same problem for me. Does not work with newest 1.16.3 Forge.

**Comment by Snownee** [comment]
I can't reproduce it. Have you installed Hwyla? It is incompatible with Hwyla

**Comment by realTIMematrix** [comment]
I see that you do not require HWYLA, but this is not useful because of other HWYLA add-on like "Waila Harvestability" or "Wawla - What Are We Looking At" does not work in twitch launcher. If you turn of HWYLA the other add ons will also turn of. And if you turn the other add-ons on HWYLA turns on again... why not making a version like in 1.15.x?

**Comment by Snownee** [comment]
> I see that you do not require HWYLA, but this is not useful because of other HWYLA add-on like "Waila Harvestability" or "Wawla - What Are We Looking At" does not work in twitch launcher. If you turn of HWYLA the other add ons will also turn of. And if you turn the other add-ons on HWYLA turns on again... why not making a version like in 1.15.x?

I didn't expect this will become an issue. This is an issue with the design of Twitch, but I will try to implement all features that Waila Harvestability and Wawla have. It seems the author of Hwyla does not have time to maintain it and leaves many bugs there. I want to provide user a better experience so I decide to make a fork. Another reason is I used hack that requires to modify code of Hwyla in 1.16

**Comment by MLMII** [comment]
I'm sorry, I missed that Jade had HWYLA included and thought it was just an addon.


Thank you for clearing that up.
