### ISSUE TITLE
服務器啟動崩潰 1.16.5 Forge

### ISSUE THREAD

**Issue by Edel-Lilies** [Snownee/Jade#60]
Forge:36.2.2
Mod:Jade 2.7.2
服務器啟動崩潰,而2.7.1版本則沒有此問題
[crash-2021-08-07_11.38.36-fml.txt](https://github.com/Snownee/Jade/files/6948496/crash-2021-08-07_11.38.36-fml.txt)

**Comment by chimericdream** [comment]
I came to report this as well. My crash log looks nearly identical, and I am on the same versions as the person above.

**Comment by Snownee** [comment]
Report this to tinyredstone author
