### ISSUE TITLE
[Running Into Issue When Running Client with Jade in Our Modern Environment ]

### ISSUE THREAD

**Issue by ModernGamingWorld** [Snownee/Jade#62]
If bug:

 * Forge Version: 1.17.1-37.0.39
 * Mod Version: 1.17.1-3.1.1
 * Can you reproduce this issue with relevant mods only?: yes/no
 * no

Paste your crash report to somewhere like https://paste.ubuntu.com/ , instead of directly here.
Waila(Jade) (waila) encountered an error during the complete event phase java.lang.NoClassDefFoundError: net/minecraftforge/common/ToolType
** Bug reports please follow the format! or it might be closed! **

**Comment by Snownee** [comment]
Make sure you are using the latest version

**Comment by ModernGamingWorld** [comment]
@Snownee what is the latest version?
I have it posted here https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/blob/main/gradle.properties and here
https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/blob/main/build.gradle

**Comment by Snownee** [comment]
Did you refresh your workspace? I don't think I referenced ToolType class in 3.1.1

**Comment by ModernGamingWorld** [comment]
@Snownee Can still confirm that after refreshing my Workspace that its still doing this, The Tooltype thing has to do with this

Build: 1.17.1-37.0.31 - Tue Aug 10 22:45:23 GMT 2021
    gigaherz:
        Redesign the tool system to rely on the new vanilla tags. (#7970)
        
        Changed:
        - ToolType is replaced with ToolAction, which can selectively represent which actions are supported by an item.
        - Added a canPerformAction method to query ToolActions.
        - Renamed canHarvestBlock to isCorrectToolForDrops to match vanilla.
        - Added TierSortingRegistry, which can be used to add custom tiers and supports sorting between vanilla or with other mods.
        
        How to use:
        
        For the breaking system there's 2 methods:
        - getDestroySpeed decides if an item *can* mine the block fast. Override if you have multiple tags or your item isn't a DiggerItem.
        - isCorrectToolForDrops decides if an item will get drops. Returning false will also slow down mining, regardless of getDestroySpeed. Override if you have type-dependant tiers or your item isn't a DiggerItem.
        
        For the tier system mods can just call `TierSortingRegistry.registerTier(tier, "name", List.of(lesser tiers), List.of(better tiers));` to register their tiers.
        There's helper methods to query tiers such as TierSortingRegsitry.isCorrectTierForDrops.
        
        The ToolActions solve 2 problems:
        1. distinguishing which kind of digger an item can be
        2. querying if the item can perform specific secondary actions.
        Any item can override `canPerformAction` to customize which actions it performs.

**Comment by Snownee** [comment]
there is no ToolType: https://github.com/Snownee/Jade/search?q=ToolType
