### ISSUE TITLE
[1.17.1] Failing to start server with Jade installed

### ISSUE THREAD

**Issue by sergeh** [Snownee/Jade#63]
* Forge Version: 37.0.43
 * Mod Version: 3.1.1
 * Can you reproduce this issue with relevant mods only? **yes**

See crash report https://paste.ubuntu.com/p/YsbgKJrtW3/

**Comment by Snownee** [comment]
Please provide full report

**Comment by sergeh** [comment]
@Snownee sure, here it is https://pastebin.ubuntu.com/p/p82fJJfQ39/

**Comment by Snownee** [comment]
thanks. should be fixed now

**Comment by sergeh** [comment]
Thanks!
