### ISSUE TITLE
图标位置问题

### ISSUE THREAD

**Issue by Lyaiya** [Snownee/Jade#64]
![image](https://user-images.githubusercontent.com/9733114/130801087-774adab6-3e3a-435f-8190-e5acd2e6fb42.png)

以前左边的图标位置是垂直居中的，是特意改成现在这样的吗？

**Comment by Snownee** [comment]
是

**Comment by Lyaiya** [comment]
既然不居中，那是不是把图标和名称放在一行会更好呢，这样图标下面就不会空出一大块地方，或者给图标垂直居中加个选项。
