### ISSUE TITLE
[1.17.1] Render bug

### ISSUE THREAD

**Issue by Khytwel** [Snownee/Jade#65]
* Forge Version: 37.0.44 and old.
 * Mod Version: 1.17.1-3.1.3
 * Can you reproduce this issue with relevant mods only?: yes

When I set the "alpha" to 0 so that the background is transparent, the rendering bug at the level of the mod name and it adds differents characters before the mod name (see the screen below).
![image](https://user-images.githubusercontent.com/54046029/130942862-bde91e6e-2a11-4698-be87-0b29f1c2fb78.png)

Config file: https://gist.github.com/Khytwel/9ff48c2d409851dc207ee79a59aceb73

**Comment by Snownee** [comment]
Hello, you need to delete the config file to let it regenerate a new one.
This issue is fixed in 3.1.4

**Comment by Khytwel** [comment]
Perfect thanks!
