### ISSUE TITLE
[1.17.1] Crash on load - 

### ISSUE THREAD

**Issue by ProsperCraft** [Snownee/Jade#67]
If bug:

 * Forge Version: 1.17.1 - 37.0.51
 * Mod Version:  Jade-1.17.1-3.1.4
 * Can you reproduce this issue with relevant mods only?: yes/no /shrug

Crashlog-
https://gist.github.com/ProsperCraft/a4ca2dc0b71f74d69705262590efba4a
Debug log-
https://gist.github.com/ProsperCraft/32b7930104b98425e85be5c685b64c91

** Bug reports please follow the format! or it might be closed! **

**Comment by Snownee** [comment]
Immersive Weapons uses an API that does not exist in Jade. Maybe from other HWYLA fork

**Comment by Snownee** [comment]
The crash will be muted in v3.1.5
