### ISSUE TITLE
[1.16.5] Crash with Concrete Conversion Tech

### ISSUE THREAD

**Issue by sirben99** [Snownee/Jade#68]
Forge Version: 36.2.4
Jade Version: 2.7.4
Concrete Conversion Tech version: 5.0.0.0
mrp Library version: 2.0.1.0
Can you reproduce this issue with relevant mods only?: Yes

Hey!

Jade seems to conflict with Concrete Conversion Tech mod, causing it to not load when launching: https://www.curseforge.com/minecraft/mc-mods/concrete-conversion-tech

Crashlog: https://pastebin.com/Yrbi8FBg

I hope this helps!

Ben

**Comment by Snownee** [comment]
same issue: https://github.com/mrp-v2/ConcreteConversionTech/issues/2
