### ISSUE TITLE
[1.12.2] chest contents sometimes just stops working

### ISSUE THREAD

**Issue by xemnes** [Snownee/Jade#7]
* Minecraft Version: 1.12.2
 * Mod Version: 0.1.0

pretty much the title, though not sure how else to explain it.
i noticed that when i was looking at my regular chests, it wasnt showing their contents, even with sneak.
this is on a server so i wondered if it was some kinda of sync issue. i then moved to a village and looked at those and it started working again. so i went back to my chests and i could see whats inside them again.
not sure what causes it really, sometimes it works, sometimes it doesnt.

**Comment by Snownee** [comment]
1.12 is no longer being maintained
