### ISSUE TITLE
Jade mod doesn't show contents of chests etc. on server

### ISSUE THREAD

**Issue by RHVGamer** [Snownee/Jade#73]
* Forge Version: 37.0.74
 * Mod Version: 3.3.1
 * Can you reproduce this issue with relevant mods only?: yes

Paste your crash report to somewhere like https://pastebin.com/ , instead of directly here. (No crash reports)

**Comment by Snownee** [comment]
why do you delete the issue template?

**Comment by RHVGamer** [comment]
> why do you delete the issue template?

ok sorry i changed it

**Comment by Snownee** [comment]
this feature requires server have Jade installed
