### ISSUE TITLE
Always show container preview

### ISSUE THREAD

**Issue by PolarBroOmega** [Snownee/Jade#75]
Pretty much just the title, allowing just hovering a container to show the contents inside without requiring shifting to see them.

**Comment by Lippiece** [comment]
I can't see the preview even with shift. Where do I enable it?

Edit: you "toggle overlay" with NUM1.

**Comment by Snownee** [comment]
@Lippiece it is not added in Fabric

**Comment by Lippiece** [comment]
> @Lippiece it is not added in Fabric

@Snownee I'm a little confused:
![2022-05-24_16 37 33](https://user-images.githubusercontent.com/47634624/170063066-d54ad2c6-5a78-4cd8-b8cd-af189a745da3.png)

**Comment by Snownee** [comment]
@Lippiece you are using WTHIT
