### ISSUE TITLE
[Suggestion] Center block vertically

### ISSUE THREAD

**Issue by Toadby** [Snownee/Jade#76]
Currently the block preview is anchored to the top of the overlay. I think it would look better centered vertically. If other people prefer it this way, it would be nice to have options in the config to reposition it.

Now:
<img width="249" alt="Image of current overlay" src="https://user-images.githubusercontent.com/16440384/143493051-6d8869f3-a2c2-4242-bb31-0a1438ac2527.png">
My edit:
<img width="249" alt="Same image edited with suggested changes" src="https://user-images.githubusercontent.com/16440384/143494511-144f5cc7-ec36-43e6-ad73-6a9cbc1b341e.png">

**Comment by Snownee** [comment]
I think you can change this in configuration

**Comment by Toadby** [comment]
Could you please point me to the option? I looked but couldn't find it.
Edit: My bad, I found it under "Display Item". Thanks!
