### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by JaisDK** [Snownee/Jade#78]
### Mod loader

Forge

### Minecraft version

1.18

### Mod version

1.18-4.0.1

### Modloader version

1.18-38.0.14

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Do you have the API documentation anywhere?

**Comment by Snownee** [comment]
Do you have experience developing a WAILA plugin? They are pretty similar. Or you can refer to the vanilla plugins in Jade.

**Comment by JaisDK** [comment]
I do and I have a plugin made, but I remember there was documentation for WAILA (or HWYLA) but I can't find it any more. I am having trouble with my TE not being updated in the tooltip and I wanted to check with the docs if I was missing something.

**Comment by Snownee** [comment]
I don't know there was a documentation before.

And Jade will not sync whole BlockEntity data like Hwyla if there is no IServerDataProvider registered, due to security concerns.

**Comment by JaisDK** [comment]
Sounds like I'm making an IServerDataProvider :)
