### ISSUE TITLE
Whenever I put jade into my mods folder and load up minecraft it says " fml.modloading.dupedmod "

### ISSUE THREAD

**Issue by Kokadoe** [Snownee/Jade#79]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.0

### Modloader version

Forge 36.2.9

### Modpack info

Just a bunch of mods I put together

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Whenever I put jade into my mods folder and load up minecraft it says " fml.modloading.dupedmod " how do I fix this?

**Comment by Snownee** [comment]
I think it means you have already installed Jade (or Hwyla)
