### ISSUE TITLE
Incompatible to Resynth Mod

### ISSUE THREAD

**Issue by smallerYeet** [Snownee/Jade#8]
* Minecraft Version: 1.16.3
 * Mod Version: 2.2.1

When I look at a block, my game crashes.

[latest.log](https://github.com/Snownee/Jade/files/5649521/latest.log)

[crash-2020-12-06_21.52.02-client.txt](https://github.com/Snownee/Jade/files/5649523/crash-2020-12-06_21.52.02-client.txt)

https://drive.google.com/file/d/1jSHOlaSCWfngyeBCXheonDQhqCc5OOXD/view?usp=sharing

Those are my Latest log, crash log and debug.

**Comment by Snownee** [comment]
I can't reduplicate your issue. your log shows waila mod is not loaded, that is weird. could you test with Jade only and see if this issue happens?

**Comment by smallerYeet** [comment]
Only the Mod itself works.
So it's one of the Mods in my Pack.
Here is a list of them:
https://github.com/Darkhax-Minecraft/Cursed/files/5650736/listmods.txt

**Comment by Snownee** [comment]
I have no idea. I tried some suspects but they work fine. if you have time you can do some binary search. I give up >_>

**Comment by smallerYeet** [comment]
How to do that?
Also, I can send you a Zip file with my Modpack if you like to, maybe that will help

**Comment by Snownee** [comment]
> Also, I can send you a Zip file with my Modpack if you like to, maybe that will help

ok

**Comment by smallerYeet** [comment]
Here you go. 

https://drive.google.com/file/d/1hOQ5b5inbXiu7-62-TkI67RaPGIkuOHY/view?usp=sharing

**Comment by Snownee** [comment]
It's Resynth Mod. The way they implements Waila and TOP API is completely wrong.
Edit: I tried to fix it but I gave up.
