### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by Kagenokami** [Snownee/Jade#80]
### Mod loader

Fabric

### Minecraft version

1.18

### Mod version

1.18

### Modloader version

Latest

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

This is literally the best mod for tooltips I have come across. It is the only one that appears to give relevant info such as enchantment table level. Please please PLEASE make a Fabric fork. Most good mods for 1.18 are made using Fabric but as much as I love this mod I cannot bring myself to drop the other good utility mods I've found just for this one mod.

**Comment by Snownee** [comment]
That is impossible because the API Jade is using now is different with Waila. So it will break many things
