### ISSUE TITLE
Black particles upon breaking blocks quickly

### ISSUE THREAD

**Issue by shrad1994** [Snownee/Jade#82]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

4.0.2

### Modloader version

39.0.5

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

Black particles appear briefly when breaking blocks too quickly. Any block broken in the past 2 seconds also produces black particles repeatedly until that window passes. You can see in the screenshots how some swings will complete with the black particles "loading". 

EDIT: I did not take screenshots after all, but the problem was reproduced with only Jade and Forge with equal results.
***_There are two screenshots where you don't see the "FPS counter" in the top corner - those are with only Jade 4.0.2 and Forge 39.0.5 installed._***

To reproduce:
1.) Install Forge 39.0.5 and Jade 4.0.2 (the latest available as of 12.31.2021)
2.) Create single player world and go to the nether
3.) Give yourself a pickaxe with efficiency 5
4.) Give yourself haste 2
5.) Mine netherrack
6.) Profit

![2021-12-31_05 39 14](https://user-images.githubusercontent.com/96917010/147828697-60c715c2-136e-4196-89ac-db04d0a6a74b.png)
![2021-12-31_05 39 15](https://user-images.githubusercontent.com/96917010/147828698-16d2ff01-70a8-48b2-93ac-0dd45b199897.png)
![2021-12-31_05 39 16](https://user-images.githubusercontent.com/96917010/147828703-ceaa1603-70ef-435a-9943-37fba5a176dd.png)
![2021-12-31_05 56 47](https://user-images.githubusercontent.com/96917010/147828706-3dde4904-8427-4367-b1a5-849a1fbd2db4.png)
![2021-12-31_06 07 42](https://user-images.githubusercontent.com/96917010/147828710-1ffae7fc-4d86-4d06-b581-7e258819f057.png)
![2021-12-31_05 39 07](https://user-images.githubusercontent.com/96917010/147828712-b29b2942-f8b5-45fb-af0a-e306913db8fb.png)
![2021-12-31_05 39 13](https://user-images.githubusercontent.com/96917010/147828695-418c93fe-0173-46fc-b990-dbb4f18a7e59.png)
![2021-12-31_05 39 11](https://user-images.githubusercontent.com/96917010/147828691-4a07da23-d515-440e-8c16-5a7cb20cf777.png)
![2021-12-31_05 39 12](https://user-images.githubusercontent.com/96917010/147828693-d1384b04-796a-438b-a362-42ab1edbb34e.png)

**Comment by Snownee** [comment]
I can't reproduce it. Please provide your latest.log

**Comment by shrad1994** [comment]
Just ran the game with only Jade and Forge, here's a screenshot from that, my resource pack doesn't seem to have any effect as it happens loaded or unloaded:

![2021-12-31_16 22 18](https://user-images.githubusercontent.com/96917010/147841571-b940b5a2-63b0-4a9b-ba11-2156a87d473e.png)

My "latest.log"
[latest.log](https://github.com/Snownee/Jade/files/7797246/latest.log)
In looking at it I've noticed a bunch of "world was started with such and such mod" so I put only Jade and Forge, created a new world and couldn't reproduce the problem anymore.. 

So in removing jade mid-playthrough I'm able to solve the black particles problem.. but removing all other mods mid-playthrough doesn't. 

Maybe Jade isn't playing nice with mods being removed?
Latest.log from my attempt with a fresh world with only jade and forge where I was unable to reproduce the issue.
[latestafter.log](https://github.com/Snownee/Jade/files/7797251/latestafter.log)

**Comment by StormDragon-64** [comment]
This is a problem with forge, update to a newer version.

![image](https://user-images.githubusercontent.com/80718549/149642947-4ed511ae-0f17-4cf8-9f40-b5d7076bb294.png)

**Comment by MaryKirschner** [comment]
Im having this issue even on the latest version of forge
