### ISSUE TITLE
Is there a way to disable item viewing without disabling entity viewing?

### ISSUE THREAD

**Issue by chrisgates301** [Snownee/Jade#83]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

4.1.0

### Modloader version

Forge 39.0.10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Basically what the title says, i get items on the floor displayed on the Jade GUI, the only way to disable this is by turning off the entity feature in the config, but that also takes away being able to see how much health a mob has, is there a way to disable items on the floor being displayed?

**Comment by Snownee** [comment]
why would you disable that?

**Comment by chrisgates301** [comment]
I dont want to disable items on the floor, just the tooltip that shows wich item is and how many of them are there. I already use another mod for items named LootBeams, so i was wondering if there was any way of disabling just the item entities

**Comment by Snownee** [comment]
it is in plugin config

**Comment by chrisgates301** [comment]
The config file in the config folder? I guess the option is not in the in-game config because i was not able to find it, i´ll check on the config file. Thanks!

**Comment by Snownee** [comment]
just press numpad 0

**Comment by chrisgates301** [comment]
Yes that takes me to the in-game config, i have already done this, but all i could find to disable items on the floor being displayed on the GUI was Display entities

**Comment by Snownee** [comment]
Minecraft > Item tooltip

**Comment by chrisgates301** [comment]
Ok Thanks very much, i'll try this one as soon as i can!
