### ISSUE TITLE
Blocks/items shown by Jade are affected by shaders

### ISSUE THREAD

**Issue by Auuki** [Snownee/Jade#91]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

4.1.2

### Modloader version

Forge 39.0.58

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Auuki/9254fb027d45b18d5c463856df0a6eb5

### Issue description

When using shaders (tested with BSL and Sildur's), blocks/items shown by Jade are weirdly shaded (should not be shaded at all cause it's UI). Given it happens with at least two different shaders and I never had that issue in the past using Sildur's and HWYLA, I've decided to report it here.
![image](https://user-images.githubusercontent.com/4561467/150691082-b40546fd-542a-413a-a6d5-1824ba8e79f8.png)

**Comment by Snownee** [comment]
Do you have JEI? Is JEI affected?

**Comment by Auuki** [comment]
It is not, no other UI mod is affected.
