### ISSUE TITLE
Crash when placing some blocks

### ISSUE THREAD

**Issue by EvergreenSystems** [Snownee/Jade#92]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

4.1.2

### Modloader version

39.0.59

### Modpack info

Homebrewed pack, modlist here: https://gist.github.com/Shedao-Shai/15feb5b3ecfc5995a89ccf95f0d85849

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Shedao-Shai/051c669549ce9e7c53a21a3425cfc361

### Issue description

When placing certain blocks Jade (presumably from my reading of the crash log) has a fit and causes a crash. This has happened twice; once when placing an easyvillagers iron farm, and once placing a vanilla furnace (crash log: easyvillagers https://gist.github.com/Shedao-Shai/554953cfff25eb160e4cda07014c609a vanilla https://gist.github.com/Shedao-Shai/f682af6690caad845fc494905fec8fd9 ).

Upon reloading of the world it's fine, it just crashes upon the placement of the block.

**Comment by Snownee** [comment]
The vanilla one shows you didn't use the latest version. And please update easy villagers
