### ISSUE TITLE
[1.18.1] Game crashes with easy villagers mod

### ISSUE THREAD

**Issue by Alexande11k** [Snownee/Jade#93]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

4.1.2

### Modloader version

Forge 39.0.55

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/k4wFm8yN

### Issue description

Minecraft crashes when seeing the breeder block from the Easy Villagers mod

**Comment by Snownee** [comment]
please update easy villagers mod
