### ISSUE TITLE
若头颅nbt中带有text标签，jade无法正确显示其名称

### ISSUE THREAD

**Issue by luoxiawuchen** [Snownee/Jade#97]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.1

### Modloader version

forge-36.2.22

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

当我去获取一个自定义头颅并放置时
![image](https://user-images.githubusercontent.com/64759847/156909338-0fcb14db-d9e3-4297-9d1e-56488c5ddb06.png)
![image](https://user-images.githubusercontent.com/64759847/156909347-fed7122b-295f-4a9a-a75a-c39e6187f5b2.png)
这个头颅带有nbt标签，自定义了名称
![image](https://user-images.githubusercontent.com/64759847/156909393-a3dc3a2f-dd7d-4506-8256-a8f71647f476.png)
<img width="275" alt="1646541345(1)" src="https://user-images.githubusercontent.com/64759847/156909402-430e12b9-3d17-4953-bb83-03d1cdd3d664.png">

如果只是普通玩家头颅，则正常显示名字
![image](https://user-images.githubusercontent.com/64759847/156909421-4ee0fdf9-aff7-41a1-b2ea-130aa84d42c0.png)

希望当头颅为自定义材质时，能根据头颅设定的展示名展示名称。

**Comment by Snownee** [comment]
所以你把头颅破坏掉名字还会保留吗？

**Comment by luoxiawuchen** [comment]
> 

![image](https://user-images.githubusercontent.com/64759847/156910733-4fcd6f6a-aae7-469e-87e1-059480b06c05.png)
破坏以后没有保留，会显示为玩家头颅

**Comment by Snownee** [comment]
所以此问题与Jade无关
